import json,pathlib,re,html
p=pathlib.Path(__file__).parent;dest=p.parent/'16-20.json';P=json.loads(dest.read_text());R=json.loads((p/'retrieval.json').read_text());reviews={e['id']:e for e in json.loads((p/'render-review.json').read_text())['entries']}
labels={'polish_ambient':('Michał Jacaszek','Q6110522'),'pop_ambient':('Wolfgang Voigt','Q85367'),'ritual_ambient':('Lustmord','Q913245'),'warm_drone':('Rafael Anton Irisarri',None),'world_meditation':('Nawang Khechog','Q2721088')}
visual={'polish_ambient':'Jacaszek stands at a laptop, mixer and cabled electronics; a music-practice photograph, not a landscape.','pop_ambient':'Wolfgang Voigt in the Kompakt record shop; an identified curator portrait with records and label material.','ritual_ambient':'Lustmord performs at an electronic workstation and laptop on a dark stage.','warm_drone':'Irisarri performs at a laptop and cabled electronic workstation at Café Oto; matching documented performance context.','world_meditation':'Nawang Khechog plays a transverse flute on a stage with microphones at the Tibetan cultural festival.'}
justifications={
'polish_ambient':'Quiet acoustic/electronic layering, extended resonance and spacious processing model the documented Jacaszek palette. Naturally-reverberant describes the Pentral church-recording strand specifically, rather than attributing a national scale or folk articulation.',
'pop_ambient':'Sustained, soft layered ambient texture and contemplative pace describe the beat-free Kompakt compilation practice; melodic and warm-glowing follow the documented chords and piano alongside sculpted samples. No pop-song groove or vocal band is implied.',
'ritual_ambient':'Dark, resonant layers, sustained drones and slow ritual pacing describe the documented Lustmord/Phurpa sound. Overtone-singing is a documented strand; the voice defaults keep register, cultural tradition and mechanism unspecified rather than claim one compulsory chant technique.',
'warm_drone':'Warm-glowing, warmed and low-mid-rich color a soft, sustained guitar/bass/keyboard drone model supported by Windy & Carl; the signature describes a listening texture, not an asserted instrument construction or regional technique.',
'world_meditation':'Soft sustained resonances, quiet onsets, melodic flute/erhu and contemplative tempo model the sourced Deuter/Nawang instrumental meditation recordings. Naturally-reverberant is excluded because the modeled studio hall effect does not establish a natural recording space.'}
for e in P['entries']:
 k=e['id'];r=R['photos'][k];api=r['api'];m=api['extmetadata'];plain=lambda key:html.unescape(re.sub('<[^>]+>','',m[key]['value']))
 actor,q=labels[k];full=r['full_delivery'];thumb=r['thumb_delivery'];assert full['status']==thumb['status']==200 and full['content_type']==thumb['content_type']=='image/jpeg'
 manifest={'kind':'tradition','id':k,'name':e['tradition']['name'],'source':'Wikimedia Commons','source_page':api['descriptionurl'],'image_url':full['final_url'],'thumb_url':thumb['final_url'],'license':plain('LicenseShortName'),'license_raw':plain('UsageTerms'),'credit':plain('Artist')+' / Wikimedia Commons / '+plain('LicenseShortName'),'match_confidence':'high','matched_label':actor,'license_url':plain('LicenseUrl')}
 if q:manifest['wikidata']=q
 verification={'checked_date':'2026-09-30','checked':True,'rights_metadata':'actual_commons_file_page_and_imageinfo_API_read','metadata_dimensions':[api['width'],api['height']],'metadata_mime_type':'image/jpeg','canonical_original_url':api['url'].split('?')[0],'canonical_original_fetch_result':r['full'].get('error','checked'),'delivery_note':'Manifest image_url is a Commons full-subject resized delivery, not the canonical original. Original URL and failed original fetch are preserved here. Full subject and aspect ratio are retained.','http_status':200,'final_full_url':full['final_url'],'final_thumb_url':thumb['final_url'],'full':full,'thumbnail':thumb,'bytes_checked':True,'visual_checked':True,'visual_review':visual[k],'thumbnail_visual_review':'Actual separate thumbnail checked in thumb-visual-review.jpg; same subject and framing as full delivery.','license_creator_checked':True,'checked_method':'Public HTTPS fetch via retained environment proxy; JPEG dimensions decoded from actual downloaded bytes with Pillow; actual file page text, full image and separate thumbnail visually inspected.','evidence_file':'docs/everynoise-work/001/packets/16-20-evidence/retrieval.json'}
 if k=='warm_drone':verification['relevance_basis']='Artist/label album Una Presencia En La Brisa explicitly describes Irisarri/Fresco warm harmonic drones; separate Café Oto artist recording credits processing and bowed guitar. Exact Every Noise membership remains pending.'
 e['photo']={'manifest':manifest,'verification':verification};e.pop('photo_candidates',None)
 e['sources'].append({'url':api['descriptionurl'],'title':'File:'+api['descriptionurl'].split('File:')[-1]+' — Wikimedia Commons','checked_date':'2026-09-30','inspection':'actual_file_page_HTML_read_and_API_metadata_compared','supported_claims':['Photo subject: '+actor,'Creator: '+plain('Artist'),'License: '+plain('LicenseShortName')+' ('+plain('LicenseUrl')+')','Full-subject delivered JPEG and separate thumbnail were fetched, decoded and visually checked; canonical original returned HTTP 429.']})
 e['signature_rationale']=justifications[k]
 e['production_validation']={'status':'production_node_four_formats_reviewed_pending_parent_browser_overlay','checked':False,'node_four_formats_checked':True,'browser_parity_checked':False,'review_file':'docs/everynoise-work/001/packets/16-20-evidence/render-review.json','actual_prefaces':reviews[k]['prefaces'],'review':'Rich/tags/prose/compact reviewed; no erhuang, stride-trotting, kora-cascading, samul-percussive or street-pulsing attribution. Parts/environment are authored source-informed models, not documented exact equipment. Existing classified sonic/style vocabulary only.'}
 e['blockers']=[b for b in e['blockers'] if b.startswith('Exact Every Noise')]
 e['membership']['escalated_retrieval_receipts']=R['membership'][e['source_label']]
 e['membership']['www_mirror_url']='https://www.furia.com/everynoise_public/engenremap-'+e['source_label'].replace(' ','')+'.html'
 e['membership']['www_mirror_inspection']='actual_HTTP_502_Bad_Gateway; browse_tool_restricted_URL'
 if k=='warm_drone':
  e['sources'].append({'url':'https://leandrofrescorafaelantonirisarri.bandcamp.com/album/una-presencia-en-la-brisa','title':'Una Presencia En La Brisa | Leandro Fresco & Rafael Anton Irisarri','checked_date':'2026-09-30','inspection':'search_result_full_text_read; direct_page_open_restricted','supported_claims':['Artist/label release text explicitly documents warm harmonic drones, engineering by Rafael Anton Irisarri, remote Buenos Aires/New York collaboration, textures and manipulated voices.','Supports warm-drone photographic relevance independently; does not claim verified Every Noise membership.']})
  e['extras']['exemplars'].append('Leandro Fresco & Rafael Anton Irisarri — Una Presencia En La Brisa')
P['remaining_validation']='Parent must rerun production source overlay/browser parity and address exact Every Noise artist membership for polish ambient, warm drone and world meditation before counting them complete. All five photos now have actual rights, HTTP/MIME, decoded dimensions and visual full/thumbnail receipts for the manifest delivery URLs; canonical originals return 429 and are preserved separately.'
P['photo_evidence_file']='docs/everynoise-work/001/packets/16-20-evidence/retrieval.json';P['render_review_file']='docs/everynoise-work/001/packets/16-20-evidence/render-review.json'
dest.write_text(json.dumps(P,indent=2,ensure_ascii=False)+'\n')
