#!/usr/bin/env node
// Build references/08_asset_manifest.js from vendored SVGs in references/_assets/icons/.
//
// ⚠ ORDERING FOOTGUN: this FULL-OVERWRITES 08_asset_manifest.js with only
// ICON_PATHS/ICON_ALIASES. `assets:emoji` (EMOJI_*) instead reads the existing
// file and appends its own section. So run `npm run assets:icons` FIRST, then
// `assets:emoji` — running it AFTER silently drops the emoji registry.
// (Proper fix: merge like build_emoji.js does.)
//
// Outputs:
//   const ICON_PATHS   = {  slug: '<inner svg markup>',  ... };
//   const ICON_ALIASES = {  codex-canonical-name: lucide-slug,  ... };
//
// src/app.js's icon() function resolves callers like
// icon('alert-circle') → ICON_ALIASES['alert-circle'] = 'circle-alert' →
// ICON_PATHS['circle-alert'] → wrapped in <svg> and returned.

const fs = require('fs');
const path = require('path');

const ICONS_DIR = path.join(__dirname, '..', 'references', '_assets', 'icons');
const MANIFEST_OUT = path.join(__dirname, '..', 'references', '08_asset_manifest.js');

// Codex-canonical name → Lucide slug. Existing icon() callers in the codex use
// these older / shorter names; the registry resolves them at lookup time so
// no caller code has to change.
const ICON_ALIASES = {
  'alert-circle': 'circle-alert',
  'more-horizontal': 'ellipsis',
  sidebar: 'panel-left',
  checkbox: 'square-check',
  edit: 'pencil',
  delete: 'trash-2',
  cancel: 'x',
  add: 'plus',
  menu: 'menu',
  export: 'upload',
  import: 'download',
  warning: 'triangle-alert',
  load: 'folder-open',
  // The app bar spells these `undo` / `redo`; Lucide vendors them as the
  // numbered variants. Without the aliases icon() returns '' and both
  // buttons render as empty squares.
  undo: 'undo-2',
  redo: 'redo-2',
};

// Extract the inner content from a Lucide SVG file (strip the outer <svg> wrapper).
// Lucide format:
//   <!-- @license ... -->
//   <svg ... attributes ... >
//     <path d="..."/>
//     ...
//   </svg>
function extractInner(svgText) {
  // Drop license comment
  let s = svgText.replace(/<!--[\s\S]*?-->/g, '');
  // Capture content between opening <svg ...> and closing </svg>
  const m = s.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!m) throw new Error('Malformed SVG: no <svg>...</svg> pair found');
  // Collapse whitespace between elements to a single space
  return m[1].trim().replace(/\s+/g, ' ').replace(/>\s+</g, '><');
}

function main() {
  const files = fs
    .readdirSync(ICONS_DIR)
    .filter((f) => f.endsWith('.svg'))
    .sort();

  const pathMap = {};
  for (const f of files) {
    const slug = f.replace(/\.svg$/, '');
    const svg = fs.readFileSync(path.join(ICONS_DIR, f), 'utf8');
    try {
      pathMap[slug] = extractInner(svg);
    } catch (e) {
      console.error('  ✗', slug, '—', e.message);
    }
  }

  // Verify every aliased target exists in pathMap
  for (const [alias, target] of Object.entries(ICON_ALIASES)) {
    if (!pathMap[target]) {
      console.warn(`  ! alias '${alias}' → '${target}' has no vendored SVG`);
    }
  }

  // Emit the manifest as a single reference file
  const lines = [];
  lines.push('// AUTO-GENERATED by scripts/build_assets.js — do not edit by hand.');
  lines.push('// Source: references/_assets/icons/*.svg (lucide-static v1.16.0, ISC License)');
  lines.push('// To regenerate: node scripts/fetch_icons.js && node scripts/build_assets.js');
  lines.push('');
  lines.push('const ICON_PATHS = {');
  for (const slug of Object.keys(pathMap).sort()) {
    // Escape single quotes in path content (rare but possible)
    const safe = pathMap[slug].replace(/'/g, "\\'");
    lines.push(`  '${slug}': '${safe}',`);
  }
  lines.push('};');
  lines.push('');
  lines.push('const ICON_ALIASES = {');
  for (const [alias, target] of Object.entries(ICON_ALIASES).sort()) {
    lines.push(`  '${alias}': '${target}',`);
  }
  lines.push('};');
  lines.push('');

  fs.writeFileSync(MANIFEST_OUT, lines.join('\n'));
  console.log(`Wrote ${MANIFEST_OUT}`);
  console.log(`  ICON_PATHS: ${Object.keys(pathMap).length} icons`);
  console.log(`  ICON_ALIASES: ${Object.keys(ICON_ALIASES).length} aliases`);
}

main();
