#!/usr/bin/env node
// regression_recipes.js — snapshot-and-diff tests for canonical recipe outputs.
//
// Captures the recipe output for a curated set of fixture configurations
// into tests/regression_snapshot.json, then on subsequent runs diffs the
// current output against the snapshot and fails on any change. Forces
// intentional acknowledgment of every output change — catches the class
// of regression that "did the recipes still look right when I eyeballed
// them" misses.
//
// USAGE
//   node scripts/regression_recipes.js              # run tests, exit 1 on any diff
//   node scripts/regression_recipes.js --update       # regenerate snapshot from current output
//   node scripts/regression_recipes.js --verbose    # show full output for each fixture
//   node scripts/regression_recipes.js --fixture=<id> # run only a specific fixture
//
// EXIT CODES
//   0 — all fixtures match snapshot (or --update completed)
//   1 — at least one fixture diverged from snapshot
//   2 — bad arguments or missing snapshot (use --update first)
//
// FIXTURES
//   Edit the FIXTURES array below to add new test cases. Each fixture has:
//     - id: stable identifier, used as snapshot key (use tradition ids only,
//           never artist/album/song names)
//     - traditions: array of tradition ids; first is primary, rest stapled

const fs = require('fs');
const path = require('path');
const os = require('os');
const { Worker, isMainThread, workerData, parentPort } = require('worker_threads');
const { search, seedFromTradition } = require('./search.js');
const { translate } = require('./translate.js');

const SNAPSHOT_DIR = path.join(__dirname, '..', 'tests');
const SNAPSHOT_PATH = path.join(SNAPSHOT_DIR, 'regression_snapshot.json');

const FIXTURES = [
  // Single-tradition fixtures spanning major branches of the tree
  { id: 'afrobeat', traditions: ['afrobeat'] },
  { id: 'khayal', traditions: ['khayal'] },
  { id: 'fado', traditions: ['fado'] },
  { id: 'klezmer', traditions: ['klezmer'] },
  { id: 'reggae_roots', traditions: ['reggae_roots'] },
  { id: 'bluegrass', traditions: ['bluegrass'] },
  { id: 'post_punk', traditions: ['post_punk'] },
  { id: 'southern_trap', traditions: ['southern_trap'] },
  { id: 'mariachi', traditions: ['mariachi'] },
  { id: 'tropicalia', traditions: ['tropicalia'] },
  { id: 'hardcore_punk', traditions: ['hardcore_punk'] },
  { id: 'shoegaze', traditions: ['shoegaze'] },
  { id: 'chicago_blues', traditions: ['chicago_blues'] },
  { id: 'bluegrass_gospel', traditions: ['bluegrass_gospel'] },
  { id: 'mande_griot', traditions: ['mande_griot'] },
  { id: 'laiko', traditions: ['laiko'] },
  { id: 'rockabilly_50s', traditions: ['rockabilly_50s'] },
  { id: 'jibaro', traditions: ['jibaro'] },
  { id: 'wenrenyue', traditions: ['wenrenyue'] },
  { id: 'bambuco', traditions: ['bambuco'] },
  { id: 'qawwali', traditions: ['qawwali'] },
  { id: 'sufi_sama', traditions: ['sufi_sama'] },
  { id: 'southern_gospel_quartet', traditions: ['southern_gospel_quartet'] },
  { id: 'sahel_praise', traditions: ['sahel_praise'] },
  { id: 'pentecostal_gospel', traditions: ['pentecostal_gospel'] },
  { id: 'arena_rock', traditions: ['arena_rock'] },
  { id: 'hair_metal', traditions: ['hair_metal'] },
  { id: 'aor', traditions: ['aor'] },
  { id: 'heartland_rock', traditions: ['heartland_rock'] },
  { id: 'beijing_opera', traditions: ['beijing_opera'] },
  { id: 'mongolian_long_song', traditions: ['mongolian_long_song'] },
  { id: 'galician_kantautor', traditions: ['galician_kantautor'] },
  { id: 'wassoulou', traditions: ['wassoulou'] },
  { id: 'samba', traditions: ['samba'] },
  { id: 'tango', traditions: ['tango'] },
  { id: 'hindustani', traditions: ['hindustani'] },
  { id: 'new_orleans', traditions: ['new_orleans'] },
  { id: 'chinese_traditional_ensemble', traditions: ['chinese_traditional_ensemble'] },
  { id: 'vietnamese_traditional', traditions: ['vietnamese_traditional'] },
  { id: 'bengali_baul', traditions: ['bengali_baul'] },
  { id: 'finnish_kantele_folk', traditions: ['finnish_kantele_folk'] },
  { id: 'swedish_nyckelharpa_folk', traditions: ['swedish_nyckelharpa_folk'] },
  { id: 'russian_byliny', traditions: ['russian_byliny'] },
  { id: 'russian_folk_balalaika_choir', traditions: ['russian_folk_balalaika_choir'] },
  { id: 'hungarian_cimbalom_trad', traditions: ['hungarian_cimbalom_trad'] },
  { id: 'bulgarian_dance_traditional', traditions: ['bulgarian_dance_traditional'] },
  { id: 'breton_folk', traditions: ['breton_folk'] },
  { id: 'sardinian_traditional', traditions: ['sardinian_traditional'] },
  { id: 'italian_southern_folk', traditions: ['italian_southern_folk'] },
  { id: 'japanese_taiko_ensemble', traditions: ['japanese_taiko_ensemble'] },
  { id: 'armenian_traditional', traditions: ['armenian_traditional'] },
  { id: 'turkish_romani_cumbus', traditions: ['turkish_romani_cumbus'] },
  { id: 'hausa_court_music', traditions: ['hausa_court_music'] },
  { id: 'barbershop_quartet', traditions: ['barbershop_quartet'] },
  { id: 'british_brass_band', traditions: ['british_brass_band'] },
  { id: 'american_drumline', traditions: ['american_drumline'] },
  { id: 'tango_traditional', traditions: ['tango_traditional'] },
  // Stapled-tradition fixture (tests the merge-context path)
  {
    id: 'greenwich_village_confessional+delta_blues',
    traditions: ['greenwich_village_confessional', 'delta_blues'],
  },
  // Layer 11 expansion — one representative per previously-uncovered tree branch
  // (top-2 branch with ≥3 traditions and zero fixture coverage). Plus the three
  // traditions added this session (jamaican_dancehall, philly_soul_intl, hawaiian_slack_key).
  { id: 'jamaican_dancehall', traditions: ['jamaican_dancehall'] },
  { id: 'philly_soul_intl', traditions: ['philly_soul_intl'] },
  { id: 'hawaiian_slack_key', traditions: ['hawaiian_slack_key'] },
  { id: 'doom', traditions: ['doom'] },
  { id: 'son_cubano', traditions: ['son_cubano'] },
  { id: 'chicago_house', traditions: ['chicago_house'] },
  { id: 'calypso', traditions: ['calypso'] },
  { id: 'greenwich_village_confessional', traditions: ['greenwich_village_confessional'] },
  { id: 'dream_pop', traditions: ['dream_pop'] },
  { id: 'candomble_ceremonial', traditions: ['candomble_ceremonial'] },
  { id: 'rai', traditions: ['rai'] },
  { id: 'cumbia_colombiana', traditions: ['cumbia_colombiana'] },
  { id: 'delta_blues', traditions: ['delta_blues'] },
  { id: 'highlife', traditions: ['highlife'] },
  { id: 'bhajan', traditions: ['bhajan'] },
  { id: 'city_pop', traditions: ['city_pop'] },
  { id: 'psychedelic_rock', traditions: ['psychedelic_rock'] },
  { id: 'tibetan_yang_chant', traditions: ['tibetan_yang_chant'] },
  { id: 'eurovision_pop', traditions: ['eurovision_pop'] },
  { id: 'psytrance', traditions: ['psytrance'] },
  { id: 'baile_funk', traditions: ['baile_funk'] },
  { id: 'vaporwave', traditions: ['vaporwave'] },
  { id: 'soukous', traditions: ['soukous'] },
  { id: 'bachata', traditions: ['bachata'] },
  { id: 'eurodance_90s', traditions: ['eurodance_90s'] },
  { id: 'uk_garage_2step', traditions: ['uk_garage_2step'] },
  { id: 'lovers_rock', traditions: ['lovers_rock'] },
  { id: 'cantorial_khazonus', traditions: ['cantorial_khazonus'] },
  { id: 'quranic_recitation_tajweed', traditions: ['quranic_recitation_tajweed'] },
  { id: 'uilleann_pipe_solo', traditions: ['uilleann_pipe_solo'] },
  { id: 'cloud_rap_experimental', traditions: ['cloud_rap_experimental'] },
  { id: 'j_rock', traditions: ['j_rock'] },
  { id: 'tuvan_throat', traditions: ['tuvan_throat'] },
  { id: 'amapiano', traditions: ['amapiano'] },
  { id: 'jam_band', traditions: ['jam_band'] },
  { id: 'musique_concrete', traditions: ['musique_concrete'] },
  // Layer 11 expansion — covers traditions fixed during Layer 13 sweep
  // (genre-pollution corrections, room/instrument fixes) so future regressions
  // catch any reversion of those fixes
  { id: 'basque_kantautor', traditions: ['basque_kantautor'] },
  { id: 'polish_poezja_spiewana', traditions: ['polish_poezja_spiewana'] },
  { id: 'fusion', traditions: ['fusion'] },
  { id: 'jersey_club', traditions: ['jersey_club'] },
  { id: 'garifuna_paranda', traditions: ['garifuna_paranda'] },
  { id: 'hi_nrg', traditions: ['hi_nrg'] },
  { id: 'shomyo_japanese', traditions: ['shomyo_japanese'] },
  { id: 'algerian_rap', traditions: ['algerian_rap'] },
  { id: 'cumbia_peruvian', traditions: ['cumbia_peruvian'] },
  { id: 'jangle_pop', traditions: ['jangle_pop'] },
  { id: 'k_pop_modern', traditions: ['k_pop_modern'] },
  // Layer 11 expansion — broader uncovered-tradition stratified sample
  { id: 'country_rap_hick_hop', traditions: ['country_rap_hick_hop'] },
  { id: 'russian_bard_song', traditions: ['russian_bard_song'] },
  { id: 'javali', traditions: ['javali'] },
  { id: 'pansori', traditions: ['pansori'] },
  { id: 'mandopop', traditions: ['mandopop'] },
  { id: 'bossa_nova', traditions: ['bossa_nova'] },
  { id: 'salsa_cubana_timba', traditions: ['salsa_cubana_timba'] },
  { id: 'schlager_german', traditions: ['schlager_german'] },
  { id: 'pre_commercial_country', traditions: ['pre_commercial_country'] },
  { id: 'parang_trini', traditions: ['parang_trini'] },
  { id: 'nashville_sound', traditions: ['nashville_sound'] },
  { id: 'ethio_pop_modern', traditions: ['ethio_pop_modern'] },
  { id: 'guqin', traditions: ['guqin'] },
  { id: 'power_pop', traditions: ['power_pop'] },
  { id: 'candombe_uruguayan', traditions: ['candombe_uruguayan'] },
  { id: 'newfoundland_outport', traditions: ['newfoundland_outport'] },
  { id: 'red_dirt', traditions: ['red_dirt'] },
  // Layer 11 expansion — recently-fixed traditions and rare-instrument coverage
  { id: 'fado_coimbra_university', traditions: ['fado_coimbra_university'] },
  { id: 'koto', traditions: ['koto'] },
  { id: 'kulintang', traditions: ['kulintang'] },
  { id: 'krautrock', traditions: ['krautrock'] },
  { id: 'twee_pop', traditions: ['twee_pop'] },
  { id: 'sophisti_pop', traditions: ['sophisti_pop'] },
  { id: 'noise_music', traditions: ['noise_music'] },
  { id: 'idm', traditions: ['idm'] },
  { id: 'hyperpop', traditions: ['hyperpop'] },
  { id: 'hyperpop_rap', traditions: ['hyperpop_rap'] },
  { id: 'rage_rap', traditions: ['rage_rap'] },
  { id: 'sami_yoik', traditions: ['sami_yoik'] },
  { id: 'sevdalinka', traditions: ['sevdalinka'] },
  { id: 'rebetiko', traditions: ['rebetiko'] },
  { id: 'taarab', traditions: ['taarab'] },
  { id: 'persian_dastgah', traditions: ['persian_dastgah'] },
  { id: 'turkish_makam', traditions: ['turkish_makam'] },
  { id: 'sardinian_polyphony', traditions: ['sardinian_polyphony'] },
  { id: 'kirtan', traditions: ['kirtan'] },
  { id: 'thumri', traditions: ['thumri'] },
  { id: 'parchman_prison_song', traditions: ['parchman_prison_song'] },
  { id: 'piedmont_fingerpicking', traditions: ['piedmont_fingerpicking'] },
  { id: 'italo_dance', traditions: ['italo_dance'] },
  { id: 'italo_house_piano', traditions: ['italo_house_piano'] },
  { id: 'lofi_house_aesthetic', traditions: ['lofi_house_aesthetic'] },
  { id: 'tech_house_classic', traditions: ['tech_house_classic'] },
  { id: 'microhouse', traditions: ['microhouse'] },
  { id: 'progressive_trance', traditions: ['progressive_trance'] },
  { id: 'mbalax', traditions: ['mbalax'] },
  { id: 'ndombolo', traditions: ['ndombolo'] },
  { id: 'kuduro', traditions: ['kuduro'] },
  { id: 'kwaito', traditions: ['kwaito'] },
  { id: 'rumba_columbia', traditions: ['rumba_columbia'] },
  { id: 'rumba_yambu', traditions: ['rumba_yambu'] },
  { id: 'choro', traditions: ['choro'] },
  { id: 'mariachi', traditions: ['mariachi'] },
  { id: 'son_jarocho', traditions: ['son_jarocho'] },
  // Layer 11 second expansion — recently-fixed traditions and previously-buggy canaries
  { id: 'baiao', traditions: ['baiao'] },
  { id: 'javanese_gamelan', traditions: ['javanese_gamelan'] },
  { id: 'soca', traditions: ['soca'] },
  { id: 'black_metal_norwegian', traditions: ['black_metal_norwegian'] },
  { id: 'yemenite_torah_cantillation', traditions: ['yemenite_torah_cantillation'] },
  { id: 'salsa_nuyorican', traditions: ['salsa_nuyorican'] },
  { id: 'gospel_quartet_male', traditions: ['gospel_quartet_male'] },
  { id: 'stoner_metal', traditions: ['stoner_metal'] },
  { id: 'bakersfield', traditions: ['bakersfield'] },
  { id: 'charanga', traditions: ['charanga'] },
  { id: 'vocal_trance', traditions: ['vocal_trance'] },
  { id: 'bubblegum_pop', traditions: ['bubblegum_pop'] },
  { id: 'hardanger_fiddle', traditions: ['hardanger_fiddle'] },
  { id: 'south_slavic_kantautor', traditions: ['south_slavic_kantautor'] },
  { id: 'palm_wine', traditions: ['palm_wine'] },
  { id: 'mento', traditions: ['mento'] },
  { id: 'gabber', traditions: ['gabber'] },
  { id: 'maskandi', traditions: ['maskandi'] },
  { id: 'bulgarian_womens_choir', traditions: ['bulgarian_womens_choir'] },
  { id: 'sacred_steel', traditions: ['sacred_steel'] },
  { id: 'danzon', traditions: ['danzon'] },
  { id: 'czech_pisnicka', traditions: ['czech_pisnicka'] },
  { id: 'chanson_classique', traditions: ['chanson_classique'] },
  { id: 'mbira_tradition', traditions: ['mbira_tradition'] },
  { id: 'ethio_jazz', traditions: ['ethio_jazz'] },
  { id: 'tin_pan_alley_song', traditions: ['tin_pan_alley_song'] },
  { id: 'vocaloid_synth_voice', traditions: ['vocaloid_synth_voice'] },
  { id: 'dhrupad', traditions: ['dhrupad'] },
  { id: 'modal_jazz', traditions: ['modal_jazz'] },
  // Layer 11 third expansion — multi-tradition blend canaries (exercise staple selection more thoroughly)
  { id: 'blend_afrobeat_fusion', traditions: ['afrobeat', 'fusion'] },
  { id: 'blend_qawwali_drone', traditions: ['qawwali', 'mongolian_long_song'] },
  { id: 'blend_chicago_blues_modern', traditions: ['chicago_blues', 'modern_rb'] },
  { id: 'blend_bossa_jazz', traditions: ['bossa_nova', 'modal_jazz'] },
  { id: 'blend_klezmer_balkan', traditions: ['klezmer', 'sevdalinka'] },
  { id: 'blend_synth_baroque', traditions: ['synthwave', 'baroque_period'] },
  { id: 'blend_postpunk_dub', traditions: ['post_punk', 'dub'] },
  { id: 'blend_carnatic_minimalist', traditions: ['carnatic_vocal', 'minimalist'] },
  { id: 'blend_techno_industrial', traditions: ['detroit_techno', 'industrial'] },
  { id: 'blend_country_jazz', traditions: ['outlaw_country', 'gypsy_jazz'] },
  { id: 'blend_fado_chanson', traditions: ['fado', 'chanson_classique'] },

  // Layer 12 — 60 additional multi-tradition blend canaries (cross-era, cross-family, cross-region, modern fusions, recording-aesthetic crosses)
  { id: 'blend_gagaku_ambient', traditions: ['gagaku', 'ambient'] },
  { id: 'blend_dhrupad_drone', traditions: ['dhrupad', 'drone_dark_ambient'] },
  { id: 'blend_ragtime_bebop', traditions: ['ragtime', 'bebop'] },
  { id: 'blend_classic_blues_neo_soul', traditions: ['classic_blues_women', 'neo_soul_classic'] },
  { id: 'blend_doowop_modern_rb', traditions: ['doo_wop', 'modern_rb'] },
  { id: 'blend_new_orleans_acid_jazz', traditions: ['new_orleans', 'acid_jazz_uk_90s'] },
  { id: 'blend_swing_west_coast_cool', traditions: ['swing_big_band', 'cool_jazz_west_coast'] },
  { id: 'blend_baroque_minimalist', traditions: ['baroque_period', 'minimalist'] },
  { id: 'blend_medieval_drone_metal', traditions: ['medieval_latin_chant_organum', 'drone_metal'] },
  { id: 'blend_tin_pan_synthpop', traditions: ['tin_pan_alley_song', 'synthpop_classic_80s'] },
  { id: 'blend_thrash_opera_seria', traditions: ['thrash_metal', 'opera_seria_baroque'] },
  { id: 'blend_hardcore_boom_bap', traditions: ['hardcore_punk', 'boom_bap'] },
  { id: 'blend_bluegrass_dub', traditions: ['bluegrass', 'dub'] },
  { id: 'blend_gospel_house_chicago', traditions: ['southern_gospel', 'chicago_house'] },
  { id: 'blend_celtic_techno', traditions: ['celtic_irish_trad', 'detroit_techno'] },
  { id: 'blend_classical_jazz_third_stream', traditions: ['string_quartet', 'third_stream'] },
  { id: 'blend_carnatic_jazz_fusion', traditions: ['carnatic_vocal', 'fusion'] },
  { id: 'blend_western_swing_outlaw', traditions: ['western_swing', 'outlaw_country'] },
  { id: 'blend_doom_drone_metal', traditions: ['doom', 'drone_metal'] },
  { id: 'blend_gypsy_jazz_flamenco', traditions: ['gypsy_jazz', 'flamenco'] },
  { id: 'blend_pansori_blues', traditions: ['pansori', 'delta_blues'] },
  { id: 'blend_taiko_metal', traditions: ['japanese_taiko_ensemble', 'thrash_metal'] },
  { id: 'blend_baroque_metal_power', traditions: ['baroque_period', 'power_metal_european'] },
  { id: 'blend_funk_jazz_fusion', traditions: ['funk', 'fusion_70s_electric'] },
  { id: 'blend_disco_house_garage', traditions: ['disco', 'garage_house_paradise'] },
  { id: 'blend_afrobeat_mande_griot', traditions: ['afrobeat', 'mande_griot'] },
  { id: 'blend_gnawa_qawwali_sufi', traditions: ['gnawa', 'qawwali'] },
  { id: 'blend_carnatic_hindustani', traditions: ['carnatic_vocal', 'hindustani'] },
  { id: 'blend_bossa_choro', traditions: ['bossa_nova', 'choro'] },
  { id: 'blend_samba_pagode', traditions: ['samba', 'pagode'] },
  { id: 'blend_tuvan_sami', traditions: ['tuvan_throat', 'sami_yoik'] },
  { id: 'blend_persian_azerbaijan', traditions: ['persian_dastgah', 'azerbaijani_mugham'] },
  { id: 'blend_javanese_balinese', traditions: ['javanese_gamelan', 'balinese_gamelan'] },
  { id: 'blend_jingju_cantonese_opera', traditions: ['beijing_opera', 'cantonese_opera'] },
  { id: 'blend_thai_classical_thai_luk', traditions: ['thai_classical', 'thai_luk_thung'] },
  { id: 'blend_maracatu_candomble', traditions: ['maracatu', 'candomble_ceremonial'] },
  { id: 'blend_mariachi_ranchera', traditions: ['mariachi', 'ranchera'] },
  { id: 'blend_amapiano_afro_house', traditions: ['amapiano', 'afro_house'] },
  { id: 'blend_afrobeats_atlanta_trap', traditions: ['afrobeats_naija', 'atlanta_trap_modern'] },
  { id: 'blend_reggaeton_dancehall', traditions: ['reggaeton', 'jamaican_dancehall'] },
  { id: 'blend_kpop_big_room', traditions: ['k_pop_modern', 'big_room_house'] },
  { id: 'blend_bedroom_lofi_hip', traditions: ['bedroom_pop', 'lofi_hiphop'] },
  { id: 'blend_vaporwave_drone_ambient', traditions: ['vaporwave', 'drone_dark_ambient'] },
  { id: 'blend_hyperpop_dance_pop', traditions: ['hyperpop', 'dance_pop_2010s'] },
  { id: 'blend_garage_revival_post_punk', traditions: ['garage_rock_revival_2000s', 'post_punk'] },
  { id: 'blend_uk_drill_brooklyn', traditions: ['uk_drill', 'brooklyn_drill'] },
  { id: 'blend_phonk_drift_old_memphis', traditions: ['drift_phonk_modern', 'phonk_old_memphis'] },
  { id: 'blend_afro_cuban_bebop', traditions: ['latin_jazz', 'bebop'] },
  { id: 'blend_spiritual_southern_gospel', traditions: ['spiritual_jazz', 'southern_gospel'] },
  { id: 'blend_punk_thrash', traditions: ['punk', 'thrash_metal'] },
  { id: 'blend_ambient_dub_techno', traditions: ['ambient', 'dub_techno'] },
  { id: 'blend_post_rock_minimalist', traditions: ['math_rock_post_rock', 'minimalist'] },
  { id: 'blend_g_funk_west_coast', traditions: ['g_funk', 'west_coast_hip_hop_classic'] },
  { id: 'blend_neo_soul_jazzy_hip_hop', traditions: ['neo_soul_classic', 'jazzy_hip_hop'] },
  { id: 'blend_emo_pop_punk', traditions: ['emo', 'pop_punk'] },
  { id: 'blend_field_blues_studio_chicago', traditions: ['delta_blues', 'chicago_blues'] },
  { id: 'blend_ethnographic_studio_morna', traditions: ['cape_verdean_funana_maritime', 'morna'] },
  {
    id: 'blend_field_holler_spiritual',
    traditions: ['field_holler_solo', 'spirituals_african_american'],
  },
  { id: 'blend_acapella_doowop', traditions: ['barbershop_quartet', 'doo_wop'] },
  { id: 'blend_jug_band_old_time', traditions: ['jug_band', 'old_time'] },

  // Function-branch fixtures — solos + intra-function pairs + cross-style stacks
  // covering all 12 universal-function branches added in the rollout
  { id: 'lullaby_japanese_komoriuta', traditions: ['japanese_komoriuta'] },
  { id: 'lullaby_persian_lalai', traditions: ['persian_lalai'] },
  { id: 'lullaby_cross_pair', traditions: ['scottish_gaelic_taladh', 'japanese_komoriuta'] },
  { id: 'lament_persian_rowzeh', traditions: ['persian_rowzehkhwani'] },
  { id: 'lament_greek_moirologi', traditions: ['greek_moirologi'] },
  { id: 'lament_lullaby_cross', traditions: ['greek_moirologi', 'spanish_nana'] },
  { id: 'wedding_indian_baraat', traditions: ['indian_baraat'] },
  { id: 'wedding_klezmer_bulgar', traditions: ['yiddish_wedding_bulgar'] },
  { id: 'wedding_drinking_cross', traditions: ['yiddish_wedding_bulgar', 'polish_biesiadne'] },
  { id: 'protest_chilean_nueva_cancion', traditions: ['chilean_nueva_cancion'] },
  { id: 'protest_hip_hop', traditions: ['american_political_hip_hop'] },
  { id: 'protest_anglo_pair', traditions: ['american_folk_revival_protest', 'irish_rebel_song'] },
  { id: 'praise_mande_jeli', traditions: ['mande_griot'] },
  { id: 'praise_yoruba_oriki', traditions: ['yoruba_oriki'] },
  {
    id: 'praise_three_continents',
    traditions: ['mande_griot', 'hindu_stuti_bhajan', 'hawaiian_mele_inoa'],
  },
  { id: 'nursery_english', traditions: ['english_nursery_rhyme'] },
  { id: 'nursery_japanese_warabe', traditions: ['japanese_warabe_uta'] },
  { id: 'nursery_handgame_pair', traditions: ['american_handgame_clapping', 'mexican_rondas'] },
  { id: 'drinking_german_trinklied', traditions: ['german_trinklied'] },
  { id: 'drinking_georgian_supra', traditions: ['georgian_supra_drinking'] },
  { id: 'drinking_celtic_pair', traditions: ['irish_pub_song', 'scottish_bothy_ballad'] },
  { id: 'shanty_english_halyard', traditions: ['english_halyard_shanty'] },
  { id: 'shanty_russian_volga', traditions: ['russian_volga_boat_song'] },
  {
    id: 'shanty_atlantic_pair',
    traditions: ['english_halyard_shanty', 'newfoundland_outport_shanty'],
  },
  { id: 'carnival_trinidad_road', traditions: ['trinidad_road_march'] },
  { id: 'carnival_brazilian_samba', traditions: ['brazilian_samba_school_enredo'] },
  { id: 'carnival_caribbean_brazil', traditions: ['trinidad_road_march', 'caribbean_junkanoo'] },
  { id: 'fieldwork_delta_holler', traditions: ['field_holler_solo'] },
  { id: 'fieldwork_bulgarian_zhetvarski', traditions: ['bulgarian_zhetvarski'] },
  { id: 'fieldwork_slavic_pair', traditions: ['romanian_colinde_seceris', 'russian_zhnitvenye'] },
  { id: 'hunting_mongolian_khoomei', traditions: ['mongolian_hunting_khoomei'] },
  { id: 'hunting_inuit_katajjaq', traditions: ['inuit_katajjaq'] },
  { id: 'hunting_subsaharan_pair', traditions: ['baaka_hunting_polyphony', 'san_bushman_hunting'] },
  { id: 'domestic_hebridean_waulking', traditions: ['hebridean_waulking'] },
  { id: 'domestic_andean_quechua', traditions: ['andean_quechua_spinning'] },
  { id: 'domestic_textile_cross', traditions: ['romanian_cantece_de_tors', 'irish_spinning_song'] },

  // === Coverage expansion (2026-05-24) ===
  { id: 'girl_group_60s', traditions: ['girl_group_60s'] },
  { id: 'brill_building_pop', traditions: ['brill_building_pop'] },
  { id: 'baroque_pop_60s', traditions: ['baroque_pop_60s'] },
  { id: 'british_invasion_rb', traditions: ['british_invasion_rb'] },
  { id: 'mod_60s_british', traditions: ['mod_60s_british'] },
  { id: 'skiffle', traditions: ['skiffle'] },
  { id: 'merseybeat', traditions: ['merseybeat'] },
  { id: 'ragtime', traditions: ['ragtime'] },
  { id: 'new_orleans', traditions: ['new_orleans'] },
  { id: 'chicago_jazz_1920s', traditions: ['chicago_jazz_1920s'] },
  { id: 'southern_soul', traditions: ['southern_soul'] },
  { id: 'memphis_rap_horrorcore', traditions: ['memphis_rap_horrorcore'] },
  { id: 'phonk_old_memphis', traditions: ['phonk_old_memphis'] },
  { id: 'kansas_city_swing', traditions: ['kansas_city_swing'] },
  { id: 'big_band', traditions: ['big_band'] },
  { id: 'western_swing', traditions: ['western_swing'] },
  { id: 'jump_blues', traditions: ['jump_blues'] },
  { id: 'dub_poetry', traditions: ['dub_poetry'] },
  { id: 'reggae_fusion_modern', traditions: ['reggae_fusion_modern'] },
  { id: 'minimal_microhouse_classic', traditions: ['minimal_microhouse_classic'] },
  { id: 'minimal_tech_house', traditions: ['minimal_tech_house'] },
  { id: 'g_funk', traditions: ['g_funk'] },
  { id: 'northern_soul_motown', traditions: ['northern_soul_motown'] },
  { id: 'ska_revival_2tone', traditions: ['ska_revival_2tone'] },
  { id: 'britfolk_revival', traditions: ['britfolk_revival'] },
  { id: 'garage_rock_revival_2000s', traditions: ['garage_rock_revival_2000s'] },
  { id: 'bedroom_singer_song', traditions: ['bedroom_singer_song'] },
  { id: 'lofi_hiphop', traditions: ['lofi_hiphop'] },
  { id: 'future_funk_vaporwave', traditions: ['future_funk_vaporwave'] },
  { id: 'hypnagogic_pop', traditions: ['hypnagogic_pop'] },
  { id: 'bedroom_pop_2010s', traditions: ['bedroom_pop_2010s'] },
  { id: 'reggaeton', traditions: ['reggaeton'] },
  { id: 'latin_trap', traditions: ['latin_trap'] },
  { id: 'new_jack_swing', traditions: ['new_jack_swing'] },
  { id: 'neo_soul_classic', traditions: ['neo_soul_classic'] },
  { id: 'alt_rnb', traditions: ['alt_rnb'] },
  { id: 'city_pop_modern', traditions: ['city_pop_modern'] },
  { id: 'k_indie', traditions: ['k_indie'] },
  { id: 'dance_pop_2010s', traditions: ['dance_pop_2010s'] },
  { id: 'sophistipop_80s', traditions: ['sophistipop_80s'] },
  { id: 'bolero_mexicano', traditions: ['bolero_mexicano'] },
  { id: 'progressive_rock', traditions: ['progressive_rock'] },
  { id: 'art_rock', traditions: ['art_rock'] },
  { id: 'glam_rock', traditions: ['glam_rock'] },
  { id: 'gothic_rock', traditions: ['gothic_rock'] },
  { id: 'southern_rock', traditions: ['southern_rock'] },
  { id: 'country_rock', traditions: ['country_rock'] },
  { id: 'new_wave', traditions: ['new_wave'] },
  { id: 'folk_rock', traditions: ['folk_rock'] },
  { id: 'garage_rock', traditions: ['garage_rock'] },
  { id: 'hard_rock', traditions: ['hard_rock'] },
  { id: 'surf_rock', traditions: ['surf_rock'] },
  { id: 'black_metal', traditions: ['black_metal'] },
  { id: 'punk', traditions: ['punk'] },
  { id: 'alternative_rock', traditions: ['alternative_rock'] },
  { id: 'grunge', traditions: ['grunge'] },
  { id: 'thrash_metal', traditions: ['thrash_metal'] },
  { id: 'death_metal', traditions: ['death_metal'] },
  { id: 'pop_punk', traditions: ['pop_punk'] },
  { id: 'britpop', traditions: ['britpop'] },
  { id: 'post_punk_late_70s', traditions: ['post_punk_late_70s'] },
  { id: 'industrial_rock', traditions: ['industrial_rock'] },
  { id: 'post_rock_extended', traditions: ['post_rock_extended'] },
  { id: 'gangsta_rap', traditions: ['gangsta_rap'] },
  { id: 'conscious_hip_hop', traditions: ['conscious_hip_hop'] },
  { id: 'boom_bap', traditions: ['boom_bap'] },
  { id: 'drill', traditions: ['drill'] },
  { id: 'cloud_rap', traditions: ['cloud_rap'] },
  { id: 'uk_drill', traditions: ['uk_drill'] },
  { id: 'french_rap', traditions: ['french_rap'] },
  { id: 'east_coast_hip_hop_classic', traditions: ['east_coast_hip_hop_classic'] },
  { id: 'west_coast_hip_hop_classic', traditions: ['west_coast_hip_hop_classic'] },
  { id: 'jazzy_hip_hop', traditions: ['jazzy_hip_hop'] },
  { id: 'k_rap', traditions: ['k_rap'] },
  { id: 'pre_sampling_hip_hop_1979_1985', traditions: ['pre_sampling_hip_hop_1979_1985'] },
  { id: 'golden_age_hip_hop_1986_1991', traditions: ['golden_age_hip_hop_1986_1991'] },
  { id: 'detroit_hip_hop', traditions: ['detroit_hip_hop'] },
  { id: 'australian_hip_hop', traditions: ['australian_hip_hop'] },
  { id: 'thai_classical', traditions: ['thai_classical'] },
  { id: 'symphonic', traditions: ['symphonic'] },
  { id: 'string_quartet', traditions: ['string_quartet'] },
  { id: 'gagaku', traditions: ['gagaku'] },
  { id: 'beijing_opera', traditions: ['beijing_opera'] },
  { id: 'cantonese_opera', traditions: ['cantonese_opera'] },
  { id: 'hindustani_sarod', traditions: ['hindustani_sarod'] },
  { id: 'andalusi_nuba', traditions: ['andalusi_nuba'] },
  { id: 'baroque_period', traditions: ['baroque_period'] },
  { id: 'opera_seria_baroque', traditions: ['opera_seria_baroque'] },
  { id: 'historical_informed_performance', traditions: ['historical_informed_performance'] },
  { id: 'carnatic_vocal', traditions: ['carnatic_vocal'] },
  { id: 'carnatic_instrumental', traditions: ['carnatic_instrumental'] },
  { id: 'anglican_choral_evensong', traditions: ['anglican_choral_evensong'] },
  { id: 'russian_orthodox_chant', traditions: ['russian_orthodox_chant'] },
  { id: 'coptic_orthodox_chant', traditions: ['coptic_orthodox_chant'] },
  { id: 'verismo_opera', traditions: ['verismo_opera'] },
  { id: 'bel_canto_opera', traditions: ['bel_canto_opera'] },
  { id: 'minimalist', traditions: ['minimalist'] },
  { id: 'gypsy_jazz', traditions: ['gypsy_jazz'] },
  { id: 'darmstadt_school_total_serialism', traditions: ['darmstadt_school_total_serialism'] },
  { id: 'chinese_kunqu_opera', traditions: ['chinese_kunqu_opera'] },
  { id: 'sichuan_opera_chuanju', traditions: ['sichuan_opera_chuanju'] },
  { id: 'acid_house', traditions: ['acid_house'] },
  { id: 'peak_techno', traditions: ['peak_techno'] },
  { id: 'dub_techno', traditions: ['dub_techno'] },
  { id: 'ambient', traditions: ['ambient'] },
  { id: 'footwork', traditions: ['footwork'] },
  { id: 'hardstyle', traditions: ['hardstyle'] },
  { id: 'synthwave', traditions: ['synthwave'] },
  { id: 'industrial', traditions: ['industrial'] },
  { id: 'freestyle_music', traditions: ['freestyle_music'] },
  { id: 'dubstep_140', traditions: ['dubstep_140'] },
  { id: 'plunderphonics', traditions: ['plunderphonics'] },
  { id: 'goa_trance', traditions: ['goa_trance'] },
  { id: 'jungle', traditions: ['jungle'] },
  { id: 'desert_blues', traditions: ['desert_blues'] },
  { id: 'flamenco', traditions: ['flamenco'] },
  { id: 'morna', traditions: ['morna'] },
  { id: 'milonga', traditions: ['milonga'] },
  { id: 'pagode', traditions: ['pagode'] },
  { id: 'juju', traditions: ['juju'] },
  { id: 'gnawa', traditions: ['gnawa'] },
  { id: 'capoeira_music', traditions: ['capoeira_music'] },
  { id: 'bebop', traditions: ['bebop'] },
  { id: 'hard_bop', traditions: ['hard_bop'] },
  { id: 'free_jazz', traditions: ['free_jazz'] },
  { id: 'cool_jazz_west_coast', traditions: ['cool_jazz_west_coast'] },
  { id: 'latin_jazz', traditions: ['latin_jazz'] },
  { id: 'fusion_70s_electric', traditions: ['fusion_70s_electric'] },
  { id: 'soul_jazz', traditions: ['soul_jazz'] },
  { id: 'stride_piano', traditions: ['stride_piano'] },
  { id: 'honky_tonk', traditions: ['honky_tonk'] },
  { id: 'singer_songwriter', traditions: ['singer_songwriter'] },
  { id: 'polish_village_fiddle', traditions: ['polish_village_fiddle'] },
  { id: 'celtic_irish_trad', traditions: ['celtic_irish_trad'] },
  { id: 'sacred_harp_singing', traditions: ['sacred_harp_singing'] },
  { id: 'work_songs_hollers', traditions: ['work_songs_hollers'] },
  { id: 'early_rock_and_roll_50s', traditions: ['early_rock_and_roll_50s'] },
  { id: 'old_time', traditions: ['old_time'] },
  { id: 'piedmont_blues', traditions: ['piedmont_blues'] },
  { id: 'southern_gospel', traditions: ['southern_gospel'] },
  { id: 'boogie_woogie', traditions: ['boogie_woogie'] },
  { id: 'funk', traditions: ['funk'] },
  { id: 'doo_wop', traditions: ['doo_wop'] },
  { id: 'gothic_country', traditions: ['gothic_country'] },
  { id: 'norteno', traditions: ['norteno'] },
  { id: 'sertanejo_universitario', traditions: ['sertanejo_universitario'] },
  { id: 'sludge_metal', traditions: ['sludge_metal'] },
  { id: 'mathcore', traditions: ['mathcore'] },
  { id: 'atmospheric_black_metal', traditions: ['atmospheric_black_metal'] },

  { id: 'bedroom_pop', traditions: ['bedroom_pop'] },
  { id: 'ecm_jazz_aesthetic', traditions: ['ecm_jazz_aesthetic'] },

  // === Field-recording expansion (2026-05-24) ===
  { id: 'mongolian_khoomei', traditions: ['mongolian_khoomei'] },
  { id: 'mongolian_long_song', traditions: ['mongolian_long_song'] },
  { id: 'tuvan_kargyraa', traditions: ['tuvan_kargyraa'] },
  { id: 'tuvan_sygyt', traditions: ['tuvan_sygyt'] },
  { id: 'sakha_olonkho_epic', traditions: ['sakha_olonkho_epic'] },
  { id: 'ainu_yukar_epic', traditions: ['ainu_yukar_epic'] },
  { id: 'kazakh_kuy', traditions: ['kazakh_kuy'] },
  { id: 'kazakh_aitys', traditions: ['kazakh_aitys'] },
  { id: 'kyrgyz_manaschi_epic', traditions: ['kyrgyz_manaschi_epic'] },
  { id: 'vedic_chant', traditions: ['vedic_chant'] },
  { id: 'powada_marathi', traditions: ['powada_marathi'] },
  { id: 'borgeet_assamese', traditions: ['borgeet_assamese'] },
  { id: 'divya_prabandham_tamil_vaishnav', traditions: ['divya_prabandham_tamil_vaishnav'] },
  { id: 'thiruvaachakam_shaivite', traditions: ['thiruvaachakam_shaivite'] },
  { id: 'sinhala_vannama', traditions: ['sinhala_vannama'] },
  { id: 'nepali_lok', traditions: ['nepali_lok'] },
  { id: 'vietnamese_ca_tru', traditions: ['vietnamese_ca_tru'] },
  { id: 'lao_lam_saravane', traditions: ['lao_lam_saravane'] },
  { id: 'indonesian_jaipongan', traditions: ['indonesian_jaipongan'] },
  { id: 'balinese_gamelan', traditions: ['balinese_gamelan'] },
  { id: 'balinese_kecak', traditions: ['balinese_kecak'] },
  { id: 'acehnese_saman', traditions: ['acehnese_saman'] },
  { id: 'japanese_noh_utai', traditions: ['japanese_noh_utai'] },
  { id: 'japanese_nagauta_kabuki', traditions: ['japanese_nagauta_kabuki'] },
  { id: 'korean_chongmyo_jeryeak', traditions: ['korean_chongmyo_jeryeak'] },
  { id: 'samoan_siva_fagufagu', traditions: ['samoan_siva_fagufagu'] },
  { id: 'fijian_meke', traditions: ['fijian_meke'] },
  { id: 'tahitian_himene_ru_au', traditions: ['tahitian_himene_ru_au'] },
  { id: 'polynesian_himene_tarava', traditions: ['polynesian_himene_tarava'] },
  { id: 'maori_waiata', traditions: ['maori_waiata'] },
  {
    id: 'australian_didgeridoo_yidaki_extended',
    traditions: ['australian_didgeridoo_yidaki_extended'],
  },
  { id: 'papua_new_guinean_polyphony', traditions: ['papua_new_guinean_polyphony'] },
  { id: 'solomon_islands_panpipe', traditions: ['solomon_islands_panpipe'] },
  { id: 'vanuatu_water_drumming', traditions: ['vanuatu_water_drumming'] },
  { id: 'wagogo_nindo_cipande', traditions: ['wagogo_nindo_cipande'] },
  { id: 'juhoansi_healing_nom', traditions: ['juhoansi_healing_nom'] },
  { id: 'xhosa_umngqokolo_overtone', traditions: ['xhosa_umngqokolo_overtone'] },
  { id: 'tuareg_tende_pestle', traditions: ['tuareg_tende_pestle'] },
  { id: 'maasai_adumu_olaranyani', traditions: ['maasai_adumu_olaranyani'] },
  { id: 'ethiopian_zema_yared', traditions: ['ethiopian_zema_yared'] },
  { id: 'berber_ahidus_ahwash', traditions: ['berber_ahidus_ahwash'] },
  { id: 'powwow', traditions: ['powwow'] },
  { id: 'lakota_peyote_song', traditions: ['lakota_peyote_song'] },
  { id: 'navajo_healing_chantways', traditions: ['navajo_healing_chantways'] },
  { id: 'apache_crown_dance', traditions: ['apache_crown_dance'] },
  { id: 'yaqui_pascola_matachin', traditions: ['yaqui_pascola_matachin'] },
  { id: 'maya_marimba', traditions: ['maya_marimba'] },
  { id: 'quechua_wayno_traditional', traditions: ['quechua_wayno_traditional'] },
  { id: 'mapuche_ulkantun', traditions: ['mapuche_ulkantun'] },
  { id: 'haitian_vodou', traditions: ['haitian_vodou'] },
  { id: 'santeria_lucumi', traditions: ['santeria_lucumi'] },
  { id: 'jongo', traditions: ['jongo'] },
  { id: 'bomba_puertorican', traditions: ['bomba_puertorican'] },
  { id: 'punta_garifuna', traditions: ['punta_garifuna'] },
  { id: 'chouval_bwa', traditions: ['chouval_bwa'] },
  { id: 'piobaireachd', traditions: ['piobaireachd'] },
  { id: 'sean_nos_solo', traditions: ['sean_nos_solo'] },
  { id: 'cape_breton_milling', traditions: ['cape_breton_milling'] },
  { id: 'corsican_paghjella', traditions: ['corsican_paghjella'] },
  { id: 'georgian_three_voice_polyphony', traditions: ['georgian_three_voice_polyphony'] },
  { id: 'bulgarian_diaphonic_womens', traditions: ['bulgarian_diaphonic_womens'] },
  { id: 'albanian_iso_polyphony', traditions: ['albanian_iso_polyphony'] },
  { id: 'alpine_yodel', traditions: ['alpine_yodel'] },
  { id: 'gwerz_breton', traditions: ['gwerz_breton'] },
  { id: 'tarantella_napoletana', traditions: ['tarantella_napoletana'] },
  { id: 'pizzica_salentina', traditions: ['pizzica_salentina'] },
  { id: 'cante_jondo_siguiriya', traditions: ['cante_jondo_siguiriya'] },
  { id: 'romanian_doina', traditions: ['romanian_doina'] },
  { id: 'greek_nisiotika', traditions: ['greek_nisiotika'] },
  { id: 'cretan_lyra', traditions: ['cretan_lyra'] },
  { id: 'icelandic_rimur', traditions: ['icelandic_rimur'] },
  { id: 'norwegian_stev_solo', traditions: ['norwegian_stev_solo'] },
  { id: 'silbo_gomero', traditions: ['silbo_gomero'] },
  { id: 'karelian_rune_singing', traditions: ['karelian_rune_singing'] },
  { id: 'byzantine_chant', traditions: ['byzantine_chant'] },
  { id: 'hasidic_niggun', traditions: ['hasidic_niggun'] },
  { id: 'medieval_latin_chant_organum', traditions: ['medieval_latin_chant_organum'] },
  { id: 'beompae_korean', traditions: ['beompae_korean'] },
  { id: 'theravada_pali_chant', traditions: ['theravada_pali_chant'] },
  { id: 'vajrayana_broader', traditions: ['vajrayana_broader'] },
  { id: 'sacred_harp_singing', traditions: ['sacred_harp_singing'] },
  { id: 'umbanda_brazilian', traditions: ['umbanda_brazilian'] },
  { id: 'talking_blues_dustbowl', traditions: ['talking_blues_dustbowl'] },
  { id: 'bothy_ballad_doric', traditions: ['bothy_ballad_doric'] },

  // === Family rebalance expansion (2026-05-24) ===
  { id: 'baltimore_club', traditions: ['baltimore_club'] },
  { id: 'happy_hardcore', traditions: ['happy_hardcore'] },
  { id: 'classical_period_18c', traditions: ['classical_period_18c'] },

  { id: 'synthpop', traditions: ['synthpop'] },
  { id: 'drone_dark_ambient', traditions: ['drone_dark_ambient'] },
  { id: 'singeli_tanzanian', traditions: ['singeli_tanzanian'] },
  { id: 'amapiano_sa', traditions: ['amapiano_sa'] },
  { id: 'berlin_techno_basic_channel', traditions: ['berlin_techno_basic_channel'] },
  { id: 'industrial_techno', traditions: ['industrial_techno'] },
  { id: 'melodic_techno', traditions: ['melodic_techno'] },
  { id: 'neurofunk', traditions: ['neurofunk'] },
  { id: 'atmospheric_dnb', traditions: ['atmospheric_dnb'] },
  { id: 'brostep', traditions: ['brostep'] },
  { id: 'future_garage', traditions: ['future_garage'] },
  { id: 'juke_chicago', traditions: ['juke_chicago'] },
  { id: 'miami_bass', traditions: ['miami_bass'] },
  { id: 'dark_ambient_industrial', traditions: ['dark_ambient_industrial'] },
  { id: 'dungeon_synth', traditions: ['dungeon_synth'] },
  { id: 'outrun_synthwave', traditions: ['outrun_synthwave'] },
  { id: 'ebm_european_body', traditions: ['ebm_european_body'] },
  { id: 'chiptune_8bit', traditions: ['chiptune_8bit'] },
  { id: 'breakcore', traditions: ['breakcore'] },
  { id: 'drill_n_bass', traditions: ['drill_n_bass'] },
  { id: 'future_bass', traditions: ['future_bass'] },
  { id: 'moombahton', traditions: ['moombahton'] },
  { id: 'electro_house_2000s', traditions: ['electro_house_2000s'] },
  { id: 'big_room_house', traditions: ['big_room_house'] },
  { id: 'afro_house', traditions: ['afro_house'] },
  { id: 'speed_garage_1990s', traditions: ['speed_garage_1990s'] },
  { id: 'arab_tarab', traditions: ['arab_tarab'] },
  { id: 'shakuhachi_honkyoku', traditions: ['shakuhachi_honkyoku'] },
  { id: 'samul_nori', traditions: ['samul_nori'] },
  { id: 'azerbaijani_mugham', traditions: ['azerbaijani_mugham'] },
  { id: 'shashmaqam_central_asian', traditions: ['shashmaqam_central_asian'] },
  { id: 'khmer_pinpeat', traditions: ['khmer_pinpeat'] },
  { id: 'renaissance_sacred_polyphony', traditions: ['renaissance_sacred_polyphony'] },
  { id: 'korean_gagok', traditions: ['korean_gagok'] },
  { id: 'tibetan_yang_chant', traditions: ['tibetan_yang_chant'] },
  { id: 'iraqi_maqam', traditions: ['iraqi_maqam'] },
  { id: 'coptic_orthodox_chant', traditions: ['coptic_orthodox_chant'] },
  { id: 'andalusi_nuba', traditions: ['andalusi_nuba'] },
  { id: 'tunisian_malouf', traditions: ['tunisian_malouf'] },
  { id: 'uyghur_muqam', traditions: ['uyghur_muqam'] },
  { id: 'huangmei_opera_chinese', traditions: ['huangmei_opera_chinese'] },
  { id: 'korean_sanjo_solo', traditions: ['korean_sanjo_solo'] },
  { id: 'vietnamese_cai_luong', traditions: ['vietnamese_cai_luong'] },
  { id: 'balinese_gamelan_gong_kebyar', traditions: ['balinese_gamelan_gong_kebyar'] },
  { id: 'burmese_mahagita', traditions: ['burmese_mahagita'] },
  { id: 'russian_five', traditions: ['russian_five'] },
  { id: 'second_viennese_school', traditions: ['second_viennese_school'] },
  { id: 'holy_minimalism', traditions: ['holy_minimalism'] },
  { id: 'american_minimalism', traditions: ['american_minimalism'] },
  { id: 'spectralism', traditions: ['spectralism'] },
  { id: 'indeterminacy_aleatoric', traditions: ['indeterminacy_aleatoric'] },
  { id: 'ars_antiqua_organum', traditions: ['ars_antiqua_organum'] },

  // === Room coverage expansion (2026-05-24) ===
  { id: 'interior_confessional_60s', traditions: ['interior_confessional_60s'] },
  { id: 'azmari_ethiopian', traditions: ['azmari_ethiopian'] },
  { id: 'iraqi_maqam', traditions: ['iraqi_maqam'] },
  { id: 'cape_verdean_batuko', traditions: ['cape_verdean_batuko'] },
  { id: 'jeju_haenyeo_songs', traditions: ['jeju_haenyeo_songs'] },
  { id: 'cajun', traditions: ['cajun'] },
  { id: 'croatian_klapa_dalmatian', traditions: ['croatian_klapa_dalmatian'] },
  { id: 'gothic_americana', traditions: ['gothic_americana'] },
  { id: 'aka_baka_polyphony', traditions: ['aka_baka_polyphony'] },
  { id: 'garifuna_paranda', traditions: ['garifuna_paranda'] },
  { id: 'sikh_gurmat_sangeet', traditions: ['sikh_gurmat_sangeet'] },
  { id: 'chimurenga', traditions: ['chimurenga'] },
  { id: 'folk_noir', traditions: ['folk_noir'] },
  { id: 'cantopop', traditions: ['cantopop'] },
  { id: 'inuit_katajjaq', traditions: ['inuit_katajjaq'] },
  { id: 'naat_devotional', traditions: ['naat_devotional'] },
  { id: 'zydeco', traditions: ['zydeco'] },
  { id: 'rajasthani_manganiyar', traditions: ['rajasthani_manganiyar'] },
  { id: 'maori_karanga_powhiri', traditions: ['maori_karanga_powhiri'] },
  { id: 'sephardi_bakkashot', traditions: ['sephardi_bakkashot'] },
  { id: 'swedish_kulning', traditions: ['swedish_kulning'] },
  { id: 'mapuche_tayil_ritual', traditions: ['mapuche_tayil_ritual'] },
  { id: 'cologne_karneval', traditions: ['cologne_karneval'] },
  { id: 'shipibo_icaros', traditions: ['shipibo_icaros'] },
  { id: 'kompa', traditions: ['kompa'] },
  { id: 'chutney_indo_caribbean', traditions: ['chutney_indo_caribbean'] },
  { id: 'bhangra_modern', traditions: ['bhangra_modern'] },
  { id: 'yemeni_sanaani', traditions: ['yemeni_sanaani'] },
  { id: 'embolada', traditions: ['embolada'] },
  { id: 'sardinian_polyphony', traditions: ['sardinian_polyphony'] },
  { id: 'estonian_setu_leelo', traditions: ['estonian_setu_leelo'] },
  { id: 'shidaiqu', traditions: ['shidaiqu'] },
  { id: 'spiritual_jazz', traditions: ['spiritual_jazz'] },
  { id: 'minneapolis_synth_funk_pop', traditions: ['minneapolis_synth_funk_pop'] },
  { id: 'riot_grrrl', traditions: ['riot_grrrl'] },
  { id: 'american_primitive', traditions: ['american_primitive'] },
  { id: 'brazilian_samba_de_roda', traditions: ['brazilian_samba_de_roda'] },
  { id: 'tongan_lakalaka', traditions: ['tongan_lakalaka'] },
  { id: 'tigrinya_music_eritrean', traditions: ['tigrinya_music_eritrean'] },

  { id: 'rapso', traditions: ['rapso'] },
  { id: 'art_pop', traditions: ['art_pop'] },
  { id: 'proto_punk', traditions: ['proto_punk'] },

  // === Variant coverage expansion (2026-05-24) ===
  { id: 'japanese_minyo', traditions: ['japanese_minyo'] },
  { id: 'vallenato', traditions: ['vallenato'] },
  { id: 'sertanejo', traditions: ['sertanejo'] },
  { id: 'hawaiian_oli_mele', traditions: ['hawaiian_oli_mele'] },
  { id: 'hungarian_verbunkos', traditions: ['hungarian_verbunkos'] },
  { id: 'joropo', traditions: ['joropo'] },
  { id: 'anadolu_rock', traditions: ['anadolu_rock'] },
  { id: 'freak_folk', traditions: ['freak_folk'] },
  { id: 'alt_country_americana', traditions: ['alt_country_americana'] },
  { id: 'fuji', traditions: ['fuji'] },
  { id: 'merengue_dominicano', traditions: ['merengue_dominicano'] },
  { id: 'freak_folk_2000s', traditions: ['freak_folk_2000s'] },
  { id: 'english_broadside_revival', traditions: ['english_broadside_revival'] },
  { id: 'lithuanian_sutartines', traditions: ['lithuanian_sutartines'] },
  { id: 'saidi_upper_egyptian', traditions: ['saidi_upper_egyptian'] },
  { id: 'portuguese_musica_de_intervencao', traditions: ['portuguese_musica_de_intervencao'] },
  { id: 'disco', traditions: ['disco'] },
  { id: 'isicathamiya', traditions: ['isicathamiya'] },
  { id: 'samba_jazz', traditions: ['samba_jazz'] },
  { id: 'indie_pop_modern', traditions: ['indie_pop_modern'] },
  { id: 'didgeridoo_yidaki_solo', traditions: ['didgeridoo_yidaki_solo'] },
  { id: 'hokum_blues_vaudeville', traditions: ['hokum_blues_vaudeville'] },
  { id: 'maracatu', traditions: ['maracatu'] },
  { id: 'mormon_tabernacle_choir', traditions: ['mormon_tabernacle_choir'] },
  { id: 'garage_punk_60s', traditions: ['garage_punk_60s'] },
  { id: 'venice_carnevale', traditions: ['venice_carnevale'] },
  { id: 'jug_band', traditions: ['jug_band'] },
  { id: 'deathcore', traditions: ['deathcore'] },
  { id: 'mongolian_khoomei', traditions: ['mongolian_khoomei'] },
  { id: 'easy_listening_orchestral', traditions: ['easy_listening_orchestral'] },
  { id: 'tropical_bolero', traditions: ['tropical_bolero'] },
  { id: 'welsh_hymn_balladry', traditions: ['welsh_hymn_balladry'] },
  { id: 'cambodian_chapei_dang_veng', traditions: ['cambodian_chapei_dang_veng'] },
  { id: 'croatian_istrian_diaphonic', traditions: ['croatian_istrian_diaphonic'] },
  { id: 'macedonian_glasoechko', traditions: ['macedonian_glasoechko'] },
  { id: 'kabyle_music_algerian', traditions: ['kabyle_music_algerian'] },
  { id: 'korean_sinawi', traditions: ['korean_sinawi'] },
  { id: 'tyrolean_schuhplattler', traditions: ['tyrolean_schuhplattler'] },
  { id: 'descarga_cubana', traditions: ['descarga_cubana'] },
  { id: 'korean_kok', traditions: ['korean_kok'] },
  { id: 'lebanese_arab_takht_wedding', traditions: ['lebanese_arab_takht_wedding'] },
  { id: 'chinese_chayang_diao', traditions: ['chinese_chayang_diao'] },
  { id: 'welsh_moliannu_cerdd_dant', traditions: ['welsh_moliannu_cerdd_dant'] },
  { id: 'black_gospel_choir', traditions: ['black_gospel_choir'] },
  { id: 'mexican_cantina_drinking', traditions: ['mexican_cantina_drinking'] },
  { id: 'okinawan_sanshin_eisa', traditions: ['okinawan_sanshin_eisa'] },
  { id: 'noise_rock', traditions: ['noise_rock'] },
  { id: 'spirituals_african_american', traditions: ['spirituals_african_american'] },
  { id: 'jubilee_quartet', traditions: ['jubilee_quartet'] },
  { id: 'dangdut', traditions: ['dangdut'] },
  { id: 'mor_lam', traditions: ['mor_lam'] },
  { id: 'marinera', traditions: ['marinera'] },
  { id: 'symphonic_metal_classic', traditions: ['symphonic_metal_classic'] },
  { id: 'funeral_doom', traditions: ['funeral_doom'] },
  { id: 'tarab_egyptian', traditions: ['tarab_egyptian'] },
  { id: 'anglican_choral_cathedral', traditions: ['anglican_choral_cathedral'] },
  { id: 'armenian_duduk_chant', traditions: ['armenian_duduk_chant'] },
  { id: 'sabar_drumming_wolof', traditions: ['sabar_drumming_wolof'] },
  { id: 'vietnamese_hat_cheo', traditions: ['vietnamese_hat_cheo'] },
  { id: 'french_musette', traditions: ['french_musette'] },
  { id: 'balkan_brass_fanfara', traditions: ['balkan_brass_fanfara'] },
  { id: 'hardingfele_slatt', traditions: ['hardingfele_slatt'] },
  { id: 'acousmatic_music', traditions: ['acousmatic_music'] },
  { id: 'tribal_house', traditions: ['tribal_house'] },
  { id: 'german_wiegenlied', traditions: ['german_wiegenlied'] },
  { id: 'yiddish_vigndlid', traditions: ['yiddish_vigndlid'] },
  { id: 'korean_jajanga', traditions: ['korean_jajanga'] },
  { id: 'berber_ahidus_wedding', traditions: ['berber_ahidus_wedding'] },
  { id: 'indian_sangeet', traditions: ['indian_sangeet'] },
  { id: 'zulu_izibongo', traditions: ['zulu_izibongo'] },
  { id: 'bengali_bhatiali', traditions: ['bengali_bhatiali'] },
  { id: 'apache_hunting_medicine', traditions: ['apache_hunting_medicine'] },

  { id: 'rap_metal', traditions: ['rap_metal'] },

  // === Tree node coverage expansion (2026-05-24) ===
  { id: 'yacht_rock', traditions: ['yacht_rock'] },
  { id: 'ranchera', traditions: ['ranchera'] },
  { id: 'corrido', traditions: ['corrido'] },
  { id: 'enka', traditions: ['enka'] },
  { id: 'congolese_rumba', traditions: ['congolese_rumba'] },
  { id: 'modern_vocal_jazz', traditions: ['modern_vocal_jazz'] },
  { id: 'emo', traditions: ['emo'] },
  { id: 'laurel_canyon_70s', traditions: ['laurel_canyon_70s'] },
  { id: 'antifolk_nyc', traditions: ['antifolk_nyc'] },
  { id: 'texas_country_folk_storyteller', traditions: ['texas_country_folk_storyteller'] },
  { id: 'child_ballad_revival', traditions: ['child_ballad_revival'] },
  { id: 'field_holler_solo', traditions: ['field_holler_solo'] },
  { id: 'classic_blues_women', traditions: ['classic_blues_women'] },
  { id: 'cantautore_italiano', traditions: ['cantautore_italiano'] },
  { id: 'greek_entechno', traditions: ['greek_entechno'] },
  { id: 'nwobhm', traditions: ['nwobhm'] },
  { id: 'drone_metal', traditions: ['drone_metal'] },
  { id: 'progressive_metal_classic', traditions: ['progressive_metal_classic'] },
  { id: 'power_metal_european', traditions: ['power_metal_european'] },
  { id: 'folk_metal_european', traditions: ['folk_metal_european'] },
  { id: 'post_metal', traditions: ['post_metal'] },
  { id: 'deep_house_soulful', traditions: ['deep_house_soulful'] },
  { id: 'garage_house_paradise', traditions: ['garage_house_paradise'] },
  { id: 'latin_house_percussion', traditions: ['latin_house_percussion'] },
  { id: 'tibetan_ache_lhamo', traditions: ['tibetan_ache_lhamo'] },
  { id: 'hindi_lori', traditions: ['hindi_lori'] },
  { id: 'chinese_xiqing_wedding', traditions: ['chinese_xiqing_wedding'] },
  { id: 'yoruba_aso_ebi_wedding', traditions: ['yoruba_aso_ebi_wedding'] },
  { id: 'andean_matrimonio_huayno', traditions: ['andean_matrimonio_huayno'] },
  { id: 'tamil_oppari', traditions: ['tamil_oppari'] },
  { id: 'yoruba_iremoje', traditions: ['yoruba_iremoje'] },
  { id: 'hawaiian_kanikau', traditions: ['hawaiian_kanikau'] },
  { id: 'hindi_nursery_rhyme', traditions: ['hindi_nursery_rhyme'] },
  { id: 'lebanese_egyptian_aghani_atfal', traditions: ['lebanese_egyptian_aghani_atfal'] },
  { id: 'yoruba_omo_iya', traditions: ['yoruba_omo_iya'] },
  { id: 'korean_jubu_ga', traditions: ['korean_jubu_ga'] },
  { id: 'sufi_munajat_naat', traditions: ['sufi_munajat_naat'] },
  { id: 'algerian_rai_political', traditions: ['algerian_rai_political'] },
  { id: 'korean_minjung_gayo', traditions: ['korean_minjung_gayo'] },
  { id: 'south_african_freedom_song', traditions: ['south_african_freedom_song'] },
  { id: 'greek_tabachaniotika', traditions: ['greek_tabachaniotika'] },
  { id: 'mande_wolof_harvest', traditions: ['mande_wolof_harvest'] },
  { id: 'andean_huayno_trabajo', traditions: ['andean_huayno_trabajo'] },
  { id: 'wolof_grain_grinding', traditions: ['wolof_grain_grinding'] },
  { id: 'korean_baennoraega', traditions: ['korean_baennoraega'] },
  { id: 'mardi_gras_indians', traditions: ['mardi_gras_indians'] },
  { id: 'bolivian_diablada_oruro', traditions: ['bolivian_diablada_oruro'] },
  { id: 'japanese_matsuri_taiko', traditions: ['japanese_matsuri_taiko'] },
  { id: 'indian_holi_diwali_processional', traditions: ['indian_holi_diwali_processional'] },

  { id: 'electroacoustic_improv', traditions: ['electroacoustic_improv'] },
  { id: 'microtonal_composition', traditions: ['microtonal_composition'] },
  { id: 'frevo', traditions: ['frevo'] },
  { id: 'indonesian_keroncong', traditions: ['indonesian_keroncong'] },
  { id: 'akan_kete_royal_praise', traditions: ['akan_kete_royal_praise'] },

  // === Fixture coverage push — 444 uncovered traditions ===
  { id: 'outlaw_country', traditions: ['outlaw_country'] },
  { id: 'texas_conjunto', traditions: ['texas_conjunto'] },
  { id: 'detroit_techno', traditions: ['detroit_techno'] },
  { id: 'dub', traditions: ['dub'] },
  { id: 'classic_rb', traditions: ['classic_rb'] },
  { id: 'math_rock_post_rock', traditions: ['math_rock_post_rock'] },
  { id: 'modern_rb', traditions: ['modern_rb'] },
  { id: 'ska_rocksteady', traditions: ['ska_rocksteady'] },
  { id: 'hiplife', traditions: ['hiplife'] },
  { id: 'afrobeats_naija', traditions: ['afrobeats_naija'] },
  { id: 'makossa', traditions: ['makossa'] },
  { id: 'gqom', traditions: ['gqom'] },
  { id: 'ghazal', traditions: ['ghazal'] },
  { id: 'hindi_filmi', traditions: ['hindi_filmi'] },
  { id: 'andean_huayno', traditions: ['andean_huayno'] },
  { id: 'kizomba', traditions: ['kizomba'] },
  { id: 'grindcore', traditions: ['grindcore'] },
  { id: 'melodic_death_metal', traditions: ['melodic_death_metal'] },
  { id: 'inuit_katajjaq', traditions: ['inuit_katajjaq'] },
  { id: 'great_american_songbook', traditions: ['great_american_songbook'] },
  { id: 'j_pop_classic', traditions: ['j_pop_classic'] },
  { id: 'shibuya_kei', traditions: ['shibuya_kei'] },
  { id: 'chanson_pop_modern', traditions: ['chanson_pop_modern'] },
  { id: 'scandi_pop', traditions: ['scandi_pop'] },
  { id: 'russian_estrada', traditions: ['russian_estrada'] },
  { id: 'portuguese_pop_modern', traditions: ['portuguese_pop_modern'] },
  { id: 'spanish_cancion_pop', traditions: ['spanish_cancion_pop'] },
  { id: 'kompa', traditions: ['kompa'] },
  { id: 'kizomba', traditions: ['kizomba'] },
  { id: 'mambo', traditions: ['mambo'] },
  { id: 'cha_cha_cha', traditions: ['cha_cha_cha'] },
  { id: 'guaracha', traditions: ['guaracha'] },
  { id: 'rumba_cubana', traditions: ['rumba_cubana'] },
  { id: 'guaguanco', traditions: ['guaguanco'] },
  { id: 'forro_brasileiro', traditions: ['forro_brasileiro'] },
  { id: 'uplifting_trance', traditions: ['uplifting_trance'] },
  { id: 'cumbia_electronica', traditions: ['cumbia_electronica'] },
  { id: 'tribal_guarachero', traditions: ['tribal_guarachero'] },
  { id: 'perreo_electronica', traditions: ['perreo_electronica'] },
  { id: 'tropical_bass', traditions: ['tropical_bass'] },
  { id: 'liquid_funk', traditions: ['liquid_funk'] },
  { id: 'athan_call_prayer', traditions: ['athan_call_prayer'] },
  { id: 'islamic_anasheed', traditions: ['islamic_anasheed'] },
  { id: 'chillwave', traditions: ['chillwave'] },
  { id: 'galician_pipe_solo', traditions: ['galician_pipe_solo'] },
  { id: 'mumble_rap', traditions: ['mumble_rap'] },
  { id: 'indie_folk_2000s', traditions: ['indie_folk_2000s'] },
  { id: 'avant_metal_classic', traditions: ['avant_metal_classic'] },
  { id: 'bro_country', traditions: ['bro_country'] },
  { id: 'hot_country_2010s', traditions: ['hot_country_2010s'] },
  { id: 'country_pop_crossover', traditions: ['country_pop_crossover'] },
  { id: 'traditional_doom', traditions: ['traditional_doom'] },
  { id: 'melodic_death_metal', traditions: ['melodic_death_metal'] },
  { id: 'technical_death_metal', traditions: ['technical_death_metal'] },
  { id: 'brutal_death_metal', traditions: ['brutal_death_metal'] },
  { id: 'contemporary_urban_gospel', traditions: ['contemporary_urban_gospel'] },
  { id: 'cool_jazz_vocal', traditions: ['cool_jazz_vocal'] },
  { id: 'dsbm_black_metal', traditions: ['dsbm_black_metal'] },
  { id: 'free_improvisation', traditions: ['free_improvisation'] },
  { id: 'russian_rock', traditions: ['russian_rock'] },
  { id: 'latin_alternative', traditions: ['latin_alternative'] },
  { id: 'electroacoustic_composition', traditions: ['electroacoustic_composition'] },
  { id: 'contemporary_rb_late_90s_2000s', traditions: ['contemporary_rb_late_90s_2000s'] },
  { id: 'tiktok_era_streaming_pop', traditions: ['tiktok_era_streaming_pop'] },
  { id: 'globalized_african_pop_crossover', traditions: ['globalized_african_pop_crossover'] },
  { id: 'tappa', traditions: ['tappa'] },
  { id: 'dadra', traditions: ['dadra'] },
  { id: 'tarana', traditions: ['tarana'] },
  { id: 'kriti', traditions: ['kriti'] },
  { id: 'padam', traditions: ['padam'] },
  { id: 'tillana', traditions: ['tillana'] },
  { id: 'mpb', traditions: ['mpb'] },
  { id: 'axe_music', traditions: ['axe_music'] },
  { id: 'plena_puertorican', traditions: ['plena_puertorican'] },
  { id: 'cadence_lypso', traditions: ['cadence_lypso'] },
  { id: 'kompa_direkt', traditions: ['kompa_direkt'] },
  { id: 'bouyon', traditions: ['bouyon'] },
  { id: 'soca_soul', traditions: ['soca_soul'] },
  { id: 'shaabi_egyptian', traditions: ['shaabi_egyptian'] },
  { id: 'mahraganat', traditions: ['mahraganat'] },
  { id: 'chaabi_moroccan', traditions: ['chaabi_moroccan'] },
  { id: 'arabesk_turkish', traditions: ['arabesk_turkish'] },
  { id: 'mizrahi_israeli', traditions: ['mizrahi_israeli'] },
  { id: 'persian_pop_los_angeles', traditions: ['persian_pop_los_angeles'] },
  { id: 'lebanese_pop_tarab', traditions: ['lebanese_pop_tarab'] },
  { id: 'malhun_maghrebi', traditions: ['malhun_maghrebi'] },
  { id: 'pure_land_buddhist', traditions: ['pure_land_buddhist'] },
  { id: 'bongo_flava', traditions: ['bongo_flava'] },
  { id: 'genge_kenyan', traditions: ['genge_kenyan'] },
  { id: 'hyperion_classical_aesthetic', traditions: ['hyperion_classical_aesthetic'] },
  { id: 'manhattan_chamber_loft', traditions: ['manhattan_chamber_loft'] },
  { id: 'sfyria_antia', traditions: ['sfyria_antia'] },
  { id: 'mbaqanga', traditions: ['mbaqanga'] },
  { id: 'vietnamese_quan_ho', traditions: ['vietnamese_quan_ho'] },
  { id: 'vietnamese_hat_xoan', traditions: ['vietnamese_hat_xoan'] },
  { id: 'ifugao_hudhud_chants', traditions: ['ifugao_hudhud_chants'] },
  { id: 'japanese_gidayu_bushi', traditions: ['japanese_gidayu_bushi'] },
  { id: 'sami_northern_luohti', traditions: ['sami_northern_luohti'] },
  { id: 'sami_skolt_leudd', traditions: ['sami_skolt_leudd'] },
  { id: 'sami_southern_vuelie', traditions: ['sami_southern_vuelie'] },
  { id: 'maori_haka_taparahi', traditions: ['maori_haka_taparahi'] },
  { id: 'oromo_music_ethiopian', traditions: ['oromo_music_ethiopian'] },
  { id: 'somali_qaraami', traditions: ['somali_qaraami'] },
  { id: 'sudanese_aghani_al_banat', traditions: ['sudanese_aghani_al_banat'] },
  { id: 'nubian_music_nile', traditions: ['nubian_music_nile'] },
  { id: 'donsongoni_hunter_harp', traditions: ['donsongoni_hunter_harp'] },
  { id: 'apala_yoruba', traditions: ['apala_yoruba'] },
  { id: 'sakara_yoruba', traditions: ['sakara_yoruba'] },
  { id: 'were_music_yoruba', traditions: ['were_music_yoruba'] },
  { id: 'coupe_decale_ivorian', traditions: ['coupe_decale_ivorian'] },
  { id: 'zouglou_ivorian', traditions: ['zouglou_ivorian'] },
  { id: 'kapuka_kenyan', traditions: ['kapuka_kenyan'] },
  { id: 'algerian_chaabi', traditions: ['algerian_chaabi'] },
  { id: 'libyan_maluf', traditions: ['libyan_maluf'] },
  { id: 'sufi_inshad_egyptian', traditions: ['sufi_inshad_egyptian'] },
  { id: 'khaliji_gulf', traditions: ['khaliji_gulf'] },
  { id: 'sawt_bahraini_kuwaiti', traditions: ['sawt_bahraini_kuwaiti'] },
  { id: 'bahraini_fjiri', traditions: ['bahraini_fjiri'] },
  { id: 'kurdish_dengbej', traditions: ['kurdish_dengbej'] },
  { id: 'syriac_orthodox_chant', traditions: ['syriac_orthodox_chant'] },
  { id: 'maronite_chant', traditions: ['maronite_chant'] },
  { id: 'assyrian_beth_gazo', traditions: ['assyrian_beth_gazo'] },
  { id: 'rabindra_sangeet', traditions: ['rabindra_sangeet'] },
  { id: 'nazrul_geeti', traditions: ['nazrul_geeti'] },
  { id: 'lavani_maharashtra', traditions: ['lavani_maharashtra'] },
  { id: 'telugu_kirtana', traditions: ['telugu_kirtana'] },
  { id: 'yueju_shanghai_opera', traditions: ['yueju_shanghai_opera'] },
  { id: 'pingju_northern_chinese', traditions: ['pingju_northern_chinese'] },
  { id: 'qinqiang_shaanxi', traditions: ['qinqiang_shaanxi'] },
  { id: 'yu_opera_henan', traditions: ['yu_opera_henan'] },
  { id: 'korean_trot', traditions: ['korean_trot'] },
  { id: 'vietnamese_don_ca_tai_tu', traditions: ['vietnamese_don_ca_tai_tu'] },
  { id: 'thai_luk_thung', traditions: ['thai_luk_thung'] },
  { id: 'thai_luk_krung', traditions: ['thai_luk_krung'] },
  { id: 'indonesian_dangdut_classic', traditions: ['indonesian_dangdut_classic'] },
  { id: 'filipino_kundiman', traditions: ['filipino_kundiman'] },
  { id: 'filipino_harana', traditions: ['filipino_harana'] },
  { id: 'burmese_hsaing_waing', traditions: ['burmese_hsaing_waing'] },
  { id: 'singaporean_xinyao', traditions: ['singaporean_xinyao'] },
  { id: 'bal_folk_revival_french', traditions: ['bal_folk_revival_french'] },
  { id: 'chanson_realiste', traditions: ['chanson_realiste'] },
  { id: 'saltarello_italian_central', traditions: ['saltarello_italian_central'] },
  { id: 'stornelli', traditions: ['stornelli'] },
  { id: 'flamenco_solea', traditions: ['flamenco_solea'] },
  { id: 'flamenco_buleria', traditions: ['flamenco_buleria'] },
  { id: 'flamenco_alegria', traditions: ['flamenco_alegria'] },
  { id: 'catalan_sardana', traditions: ['catalan_sardana'] },
  { id: 'romanian_lautari', traditions: ['romanian_lautari'] },
  { id: 'hungarian_magyar_nota', traditions: ['hungarian_magyar_nota'] },
  { id: 'polish_goralski', traditions: ['polish_goralski'] },
  { id: 'pontic_greek', traditions: ['pontic_greek'] },
  { id: 'cypriot_tsiattista', traditions: ['cypriot_tsiattista'] },
  { id: 'latvian_dainas', traditions: ['latvian_dainas'] },
  { id: 'faroese_kvaedi', traditions: ['faroese_kvaedi'] },
  { id: 'swedish_polska_traditional', traditions: ['swedish_polska_traditional'] },
  { id: 'asturian_gaita', traditions: ['asturian_gaita'] },
  { id: 'basque_bertsolaritza', traditions: ['basque_bertsolaritza'] },
  { id: 'corsican_paghjella_modern', traditions: ['corsican_paghjella_modern'] },
  { id: 'banda_sinaloense', traditions: ['banda_sinaloense'] },
  { id: 'sonidero', traditions: ['sonidero'] },
  { id: 'cumbia_rebajada', traditions: ['cumbia_rebajada'] },
  { id: 'son_huasteco', traditions: ['son_huasteco'] },
  { id: 'son_istmeno', traditions: ['son_istmeno'] },
  { id: 'trio_romantico_mexicano', traditions: ['trio_romantico_mexicano'] },
  { id: 'trova_cubana', traditions: ['trova_cubana'] },
  { id: 'filin_cubano', traditions: ['filin_cubano'] },
  { id: 'songo_cubano', traditions: ['songo_cubano'] },
  { id: 'salsa_dura', traditions: ['salsa_dura'] },
  { id: 'salsa_romantica', traditions: ['salsa_romantica'] },
  { id: 'salsa_colombiana', traditions: ['salsa_colombiana'] },
  { id: 'merengue_urbano', traditions: ['merengue_urbano'] },
  { id: 'merengue_tipico', traditions: ['merengue_tipico'] },
  { id: 'twoubadou_haitian', traditions: ['twoubadou_haitian'] },
  { id: 'rasin_haitian', traditions: ['rasin_haitian'] },
  { id: 'garifuna_punta_rock', traditions: ['garifuna_punta_rock'] },
  { id: 'aguinaldo_puertorican', traditions: ['aguinaldo_puertorican'] },
  { id: 'chamame_argentine', traditions: ['chamame_argentine'] },
  { id: 'chacarera_argentina', traditions: ['chacarera_argentina'] },
  { id: 'zamba_argentina', traditions: ['zamba_argentina'] },
  { id: 'cueca_chilena', traditions: ['cueca_chilena'] },
  { id: 'festejo_afroperuano', traditions: ['festejo_afroperuano'] },
  { id: 'lando_afroperuano', traditions: ['lando_afroperuano'] },
  { id: 'currulao_pacifico', traditions: ['currulao_pacifico'] },
  { id: 'champeta_cartagenera', traditions: ['champeta_cartagenera'] },
  { id: 'forro_pe_de_serra', traditions: ['forro_pe_de_serra'] },
  { id: 'brega_tecnobrega', traditions: ['brega_tecnobrega'] },
  { id: 'pisadinha_arrocha', traditions: ['pisadinha_arrocha'] },
  { id: 'repente_embolada', traditions: ['repente_embolada'] },
  { id: 'lambada_carimbo', traditions: ['lambada_carimbo'] },
  { id: 'coco_brasileiro', traditions: ['coco_brasileiro'] },
  { id: 'jongo_brasileiro', traditions: ['jongo_brasileiro'] },
  { id: 'quechua_wayno_traditional', traditions: ['quechua_wayno_traditional'] },
  { id: 'maya_marimba', traditions: ['maya_marimba'] },
  { id: 'early_romantic_19c', traditions: ['early_romantic_19c'] },
  { id: 'late_romantic_19c', traditions: ['late_romantic_19c'] },
  { id: 'les_six_french', traditions: ['les_six_french'] },
  { id: 'neoclassicism_interwar', traditions: ['neoclassicism_interwar'] },
  { id: 'polish_avant_garde_sonorism', traditions: ['polish_avant_garde_sonorism'] },
  { id: 'new_complexity', traditions: ['new_complexity'] },
  { id: 'soundscape_composition', traditions: ['soundscape_composition'] },
  { id: 'fluxus_intermedia', traditions: ['fluxus_intermedia'] },
  { id: 'ars_nova_french', traditions: ['ars_nova_french'] },
  { id: 'burgundian_school', traditions: ['burgundian_school'] },
  { id: 'ambrosian_chant_milanese', traditions: ['ambrosian_chant_milanese'] },
  { id: 'mozarabic_chant', traditions: ['mozarabic_chant'] },
  { id: 'sarum_chant_english', traditions: ['sarum_chant_english'] },
  { id: 'beneventan_chant', traditions: ['beneventan_chant'] },
  { id: 'lutheran_chorale', traditions: ['lutheran_chorale'] },
  { id: 'methodist_hymnody', traditions: ['methodist_hymnody'] },
  { id: 'shakers_singing', traditions: ['shakers_singing'] },
  { id: 'byzantine_psaltic', traditions: ['byzantine_psaltic'] },
  { id: 'renaissance_madrigal', traditions: ['renaissance_madrigal'] },
  { id: 'grand_opera_french', traditions: ['grand_opera_french'] },
  { id: 'zarzuela_spanish', traditions: ['zarzuela_spanish'] },
  { id: 'canzone_napoletana', traditions: ['canzone_napoletana'] },
  { id: 'swing_big_band', traditions: ['swing_big_band'] },
  { id: 'smooth_jazz_80s', traditions: ['smooth_jazz_80s'] },
  { id: 'acid_jazz_uk_90s', traditions: ['acid_jazz_uk_90s'] },
  { id: 'nu_jazz_2000s', traditions: ['nu_jazz_2000s'] },
  { id: 'm_base_collective', traditions: ['m_base_collective'] },
  { id: 'third_stream', traditions: ['third_stream'] },
  { id: 'klezmer_jazz_fusion', traditions: ['klezmer_jazz_fusion'] },
  { id: 'punk_jazz_70s_80s', traditions: ['punk_jazz_70s_80s'] },
  { id: 'anarcho_punk_crass', traditions: ['anarcho_punk_crass'] },
  { id: 'crust_punk', traditions: ['crust_punk'] },
  { id: 'd_beat_swedish', traditions: ['d_beat_swedish'] },
  { id: 'powerviolence', traditions: ['powerviolence'] },
  { id: 'screamo_skramz', traditions: ['screamo_skramz'] },
  { id: 'folk_punk', traditions: ['folk_punk'] },
  { id: 'ska_punk_third_wave', traditions: ['ska_punk_third_wave'] },
  { id: 'midwest_emo', traditions: ['midwest_emo'] },
  { id: 'slowcore', traditions: ['slowcore'] },
  { id: 'sadcore', traditions: ['sadcore'] },
  { id: 'madchester_baggy', traditions: ['madchester_baggy'] },
  { id: 'slacker_rock', traditions: ['slacker_rock'] },
  { id: 'chamber_pop_high_llamas', traditions: ['chamber_pop_high_llamas'] },
  { id: 'speed_metal', traditions: ['speed_metal'] },
  { id: 'groove_metal', traditions: ['groove_metal'] },
  { id: 'industrial_metal', traditions: ['industrial_metal'] },
  { id: 'gothic_metal', traditions: ['gothic_metal'] },
  { id: 'stoner_rock', traditions: ['stoner_rock'] },
  { id: 'desert_rock_palm', traditions: ['desert_rock_palm'] },
  { id: 'space_rock', traditions: ['space_rock'] },
  { id: 'zeuhl_french', traditions: ['zeuhl_french'] },
  { id: 'canterbury_scene', traditions: ['canterbury_scene'] },
  { id: 'nu_metal_korn_limp', traditions: ['nu_metal_korn_limp'] },
  { id: 'funk_metal', traditions: ['funk_metal'] },
  { id: 'latin_rock', traditions: ['latin_rock'] },
  { id: 'greek_rock', traditions: ['greek_rock'] },
  { id: 'aussie_pub_rock', traditions: ['aussie_pub_rock'] },
  { id: 'southern_hip_hop_classic', traditions: ['southern_hip_hop_classic'] },
  { id: 'bay_area_hyphy', traditions: ['bay_area_hyphy'] },
  { id: 'atlanta_trap_classic', traditions: ['atlanta_trap_classic'] },
  { id: 'atlanta_trap_modern', traditions: ['atlanta_trap_modern'] },
  { id: 'houston_chopped_screwed', traditions: ['houston_chopped_screwed'] },
  { id: 'dc_go_go', traditions: ['dc_go_go'] },
  { id: 'crunk', traditions: ['crunk'] },
  { id: 'snap_music', traditions: ['snap_music'] },
  { id: 'drift_phonk_modern', traditions: ['drift_phonk_modern'] },
  { id: 'plugg', traditions: ['plugg'] },
  { id: 'pluggnb', traditions: ['pluggnb'] },
  { id: 'sad_rap_emo_trap', traditions: ['sad_rap_emo_trap'] },
  { id: 'soundcloud_rap', traditions: ['soundcloud_rap'] },
  { id: 'chicago_drill', traditions: ['chicago_drill'] },
  { id: 'brooklyn_drill', traditions: ['brooklyn_drill'] },
  { id: 'christian_hip_hop', traditions: ['christian_hip_hop'] },
  { id: 'uk_grime_classic', traditions: ['uk_grime_classic'] },
  { id: 'german_deutschrap', traditions: ['german_deutschrap'] },
  { id: 'japanese_hip_hop', traditions: ['japanese_hip_hop'] },
  { id: 'korean_hip_hop', traditions: ['korean_hip_hop'] },
  { id: 'south_african_kwaito', traditions: ['south_african_kwaito'] },
  { id: 'future_house', traditions: ['future_house'] },
  { id: 'slap_house', traditions: ['slap_house'] },
  { id: 'melodic_house', traditions: ['melodic_house'] },
  { id: 'fidget_house', traditions: ['fidget_house'] },
  { id: 'jackin_house', traditions: ['jackin_house'] },
  { id: 'schranz_hard_techno', traditions: ['schranz_hard_techno'] },
  { id: 'hard_techno_2020s', traditions: ['hard_techno_2020s'] },
  { id: 'broken_beat_uk', traditions: ['broken_beat_uk'] },
  { id: 'jump_up_dnb', traditions: ['jump_up_dnb'] },
  { id: 'ragga_jungle', traditions: ['ragga_jungle'] },
  { id: 'sambass_brazilian_dnb', traditions: ['sambass_brazilian_dnb'] },
  { id: 'riddim_dubstep', traditions: ['riddim_dubstep'] },
  { id: 'melodic_dubstep_2010s', traditions: ['melodic_dubstep_2010s'] },
  { id: 'bassline_uk', traditions: ['bassline_uk'] },
  { id: 'ghetto_house_dance_mania', traditions: ['ghetto_house_dance_mania'] },
  { id: 'ghettotech_detroit', traditions: ['ghettotech_detroit'] },
  { id: 'philly_club', traditions: ['philly_club'] },
  { id: 'darksynth', traditions: ['darksynth'] },
  { id: 'dark_electro_aggrotech', traditions: ['dark_electro_aggrotech'] },
  { id: 'witch_house_2010s', traditions: ['witch_house_2010s'] },
  { id: 'broken_beat_4hero', traditions: ['broken_beat_4hero'] },
  { id: 'festival_trap', traditions: ['festival_trap'] },
  { id: 'glitch_2000s', traditions: ['glitch_2000s'] },
  { id: 'mallsoft', traditions: ['mallsoft'] },
  { id: 'prog_rb', traditions: ['prog_rb'] },
  { id: 'alt_rnb', traditions: ['alt_rnb'] },
  { id: 'modern_indie_rock_2010s', traditions: ['modern_indie_rock_2010s'] },
  { id: 'math_rock_classic', traditions: ['math_rock_classic'] },
  { id: 'post_hardcore_90s', traditions: ['post_hardcore_90s'] },
  { id: 'emo_revival_2010s', traditions: ['emo_revival_2010s'] },
  { id: 'dreampop_modern', traditions: ['dreampop_modern'] },
  { id: 'j_indie', traditions: ['j_indie'] },
  { id: 'mandopop_modern', traditions: ['mandopop_modern'] },
  { id: 'vapor_aesthetic', traditions: ['vapor_aesthetic'] },
  { id: 'hauntology_uk_2010s', traditions: ['hauntology_uk_2010s'] },
  { id: 'liquid_dnb', traditions: ['liquid_dnb'] },
  { id: 'uk_hardcore_breakbeat', traditions: ['uk_hardcore_breakbeat'] },
  { id: 'chillwave_glo_fi', traditions: ['chillwave_glo_fi'] },
  { id: 'drone_metal_sustained', traditions: ['drone_metal_sustained'] },
  { id: 'funeral_doom', traditions: ['funeral_doom'] },
  { id: 'teen_pop_late_90s', traditions: ['teen_pop_late_90s'] },
  { id: 'post_metal_2000s', traditions: ['post_metal_2000s'] },
  { id: 'djent', traditions: ['djent'] },
  { id: 'black_metal_norwegian', traditions: ['black_metal_norwegian'] },
  { id: 'blackgaze', traditions: ['blackgaze'] },
  { id: 'dsbm_black_metal', traditions: ['dsbm_black_metal'] },
  { id: 'post_punk_revival', traditions: ['post_punk_revival'] },
  { id: 'synthpop_classic_80s', traditions: ['synthpop_classic_80s'] },
  { id: 'new_wave_late_70s_early_80s', traditions: ['new_wave_late_70s_early_80s'] },
  { id: 'darkwave', traditions: ['darkwave'] },
  { id: 'spanish_nana', traditions: ['spanish_nana'] },
  { id: 'russian_kolybelnaya', traditions: ['russian_kolybelnaya'] },
  { id: 'italian_ninna_nanna', traditions: ['italian_ninna_nanna'] },
  { id: 'french_berceuse', traditions: ['french_berceuse'] },
  { id: 'portuguese_acalanto', traditions: ['portuguese_acalanto'] },
  { id: 'brazilian_cantiga_de_ninar', traditions: ['brazilian_cantiga_de_ninar'] },
  { id: 'greek_nanourisma', traditions: ['greek_nanourisma'] },
  { id: 'irish_suantrai', traditions: ['irish_suantrai'] },
  { id: 'scottish_gaelic_taladh', traditions: ['scottish_gaelic_taladh'] },
  { id: 'persian_lalai', traditions: ['persian_lalai'] },
  { id: 'arabic_tahwidah', traditions: ['arabic_tahwidah'] },
  { id: 'tamil_thalattu', traditions: ['tamil_thalattu'] },
  { id: 'bengali_ghum_paranir_gan', traditions: ['bengali_ghum_paranir_gan'] },
  { id: 'mandarin_yaolanqu', traditions: ['mandarin_yaolanqu'] },
  { id: 'japanese_komoriuta', traditions: ['japanese_komoriuta'] },
  { id: 'irish_caoineadh', traditions: ['irish_caoineadh'] },
  { id: 'scottish_coronach', traditions: ['scottish_coronach'] },
  { id: 'greek_moirologi', traditions: ['greek_moirologi'] },
  { id: 'sardinian_atitidu', traditions: ['sardinian_atitidu'] },
  { id: 'corsican_voceru', traditions: ['corsican_voceru'] },
  { id: 'romanian_bocet', traditions: ['romanian_bocet'] },
  { id: 'finnish_itkuvirsi', traditions: ['finnish_itkuvirsi'] },
  { id: 'russian_plach', traditions: ['russian_plach'] },
  { id: 'albanian_vajtim', traditions: ['albanian_vajtim'] },
  { id: 'persian_rowzehkhwani', traditions: ['persian_rowzehkhwani'] },
  { id: 'arabic_naha', traditions: ['arabic_naha'] },
  { id: 'bengali_kanna', traditions: ['bengali_kanna'] },
  { id: 'maori_waiata_tangi', traditions: ['maori_waiata_tangi'] },
  { id: 'yiddish_wedding_bulgar', traditions: ['yiddish_wedding_bulgar'] },
  { id: 'roma_svatba_balkan', traditions: ['roma_svatba_balkan'] },
  { id: 'sardinian_traditional', traditions: ['sardinian_traditional'] },
  { id: 'greek_gamilio_glendi', traditions: ['greek_gamilio_glendi'] },
  { id: 'albanian_dasma', traditions: ['albanian_dasma'] },
  { id: 'persian_aroosi', traditions: ['persian_aroosi'] },
  { id: 'indian_baraat', traditions: ['indian_baraat'] },
  { id: 'javanese_gamelan', traditions: ['javanese_gamelan'] },
  { id: 'ethiopian_eskista_wedding', traditions: ['ethiopian_eskista_wedding'] },
  { id: 'american_folk_revival_protest', traditions: ['american_folk_revival_protest'] },
  { id: 'chilean_nueva_cancion', traditions: ['chilean_nueva_cancion'] },
  { id: 'argentine_canto_nuevo', traditions: ['argentine_canto_nuevo'] },
  { id: 'italian_canti_partigiani', traditions: ['italian_canti_partigiani'] },
  { id: 'catalan_nova_canco', traditions: ['catalan_nova_canco'] },
  {
    id: 'egyptian_sayyed_darwish_sheikh_imam',
    traditions: ['egyptian_sayyed_darwish_sheikh_imam'],
  },
  { id: 'polish_sung_poetry_protest', traditions: ['polish_sung_poetry_protest'] },
  { id: 'vietnamese_nhac_phan_chien', traditions: ['vietnamese_nhac_phan_chien'] },
  { id: 'american_political_hip_hop', traditions: ['american_political_hip_hop'] },
  { id: 'brazilian_mpb_protest', traditions: ['brazilian_mpb_protest'] },
  { id: 'greek_entechno_politicized', traditions: ['greek_entechno_politicized'] },
  { id: 'irish_rebel_song', traditions: ['irish_rebel_song'] },
  { id: 'yoruba_oriki', traditions: ['yoruba_oriki'] },
  { id: 'shona_mbira_praise', traditions: ['shona_mbira_praise'] },
  { id: 'hindu_stuti_bhajan', traditions: ['hindu_stuti_bhajan'] },
  { id: 'sikh_shabad_kirtan', traditions: ['sikh_shabad_kirtan'] },
  { id: 'tibetan_thodrol_lama_praise', traditions: ['tibetan_thodrol_lama_praise'] },
  { id: 'hawaiian_mele_inoa', traditions: ['hawaiian_mele_inoa'] },
  { id: 'maori_waiata_moteatea_patere', traditions: ['maori_waiata_moteatea_patere'] },
  { id: 'arabic_madh_qasida', traditions: ['arabic_madh_qasida'] },
  { id: 'mande_griot', traditions: ['mande_griot'] },
  { id: 'english_nursery_rhyme', traditions: ['english_nursery_rhyme'] },
  { id: 'french_comptines', traditions: ['french_comptines'] },
  { id: 'german_kinderlieder', traditions: ['german_kinderlieder'] },
  { id: 'italian_filastrocche', traditions: ['italian_filastrocche'] },
  { id: 'spanish_rondas', traditions: ['spanish_rondas'] },
  { id: 'russian_poteshki', traditions: ['russian_poteshki'] },
  { id: 'romanian_cantece_pentru_copii', traditions: ['romanian_cantece_pentru_copii'] },
  { id: 'korean_dongyo', traditions: ['korean_dongyo'] },
  { id: 'japanese_warabe_uta', traditions: ['japanese_warabe_uta'] },
  { id: 'mandarin_tongyao', traditions: ['mandarin_tongyao'] },
  { id: 'tamil_children_song', traditions: ['tamil_children_song'] },
  { id: 'bengali_chhotoder_chora', traditions: ['bengali_chhotoder_chora'] },
  { id: 'american_handgame_clapping', traditions: ['american_handgame_clapping'] },
  { id: 'mexican_rondas', traditions: ['mexican_rondas'] },
  { id: 'brazilian_cantigas_de_roda', traditions: ['brazilian_cantigas_de_roda'] },
  { id: 'german_trinklied', traditions: ['german_trinklied'] },
  { id: 'irish_pub_song', traditions: ['irish_pub_song'] },
  { id: 'french_chansons_a_boire', traditions: ['french_chansons_a_boire'] },
  { id: 'italian_canti_goliardici', traditions: ['italian_canti_goliardici'] },
  { id: 'scottish_bothy_ballad', traditions: ['scottish_bothy_ballad'] },
  { id: 'czech_pijacka', traditions: ['czech_pijacka'] },
  { id: 'hungarian_bordal', traditions: ['hungarian_bordal'] },
  { id: 'polish_biesiadne', traditions: ['polish_biesiadne'] },
  { id: 'russian_zastolnaya', traditions: ['russian_zastolnaya'] },
  { id: 'macedonian_kafana_drinking', traditions: ['macedonian_kafana_drinking'] },
  { id: 'georgian_supra_drinking', traditions: ['georgian_supra_drinking'] },
  { id: 'japanese_izakaya_enka', traditions: ['japanese_izakaya_enka'] },
  { id: 'american_drinking_song', traditions: ['american_drinking_song'] },
  { id: 'english_halyard_shanty', traditions: ['english_halyard_shanty'] },
  { id: 'american_clipper_shanty', traditions: ['american_clipper_shanty'] },
  { id: 'norwegian_skipperslatter', traditions: ['norwegian_skipperslatter'] },
  { id: 'russian_volga_boat_song', traditions: ['russian_volga_boat_song'] },
  { id: 'hebridean_iorram', traditions: ['hebridean_iorram'] },
  { id: 'cape_verdean_funana_maritime', traditions: ['cape_verdean_funana_maritime'] },
  { id: 'newfoundland_outport_shanty', traditions: ['newfoundland_outport_shanty'] },
  { id: 'trinidad_road_march', traditions: ['trinidad_road_march'] },
  { id: 'brazilian_samba_school_enredo', traditions: ['brazilian_samba_school_enredo'] },
  { id: 'new_orleans_brass_parade', traditions: ['new_orleans_brass_parade'] },
  { id: 'caribbean_junkanoo', traditions: ['caribbean_junkanoo'] },
  {
    id: 'caribbean_carnival_steelpan_panorama',
    traditions: ['caribbean_carnival_steelpan_panorama'],
  },
  { id: 'field_holler_solo', traditions: ['field_holler_solo'] },
  { id: 'bulgarian_zhetvarski', traditions: ['bulgarian_zhetvarski'] },
  { id: 'romanian_colinde_seceris', traditions: ['romanian_colinde_seceris'] },
  { id: 'hungarian_aratonota', traditions: ['hungarian_aratonota'] },
  { id: 'russian_zhnitvenye', traditions: ['russian_zhnitvenye'] },
  { id: 'korean_nongak_field', traditions: ['korean_nongak_field'] },
  { id: 'vietnamese_ho', traditions: ['vietnamese_ho'] },
  { id: 'japanese_taue_uta', traditions: ['japanese_taue_uta'] },
  { id: 'indonesian_padi_planting', traditions: ['indonesian_padi_planting'] },
  { id: 'west_african_rice_planting', traditions: ['west_african_rice_planting'] },
  { id: 'baaka_hunting_polyphony', traditions: ['baaka_hunting_polyphony'] },
  { id: 'san_bushman_hunting', traditions: ['san_bushman_hunting'] },
  { id: 'mongolian_hunting_khoomei', traditions: ['mongolian_hunting_khoomei'] },
  { id: 'sami_yoik_tracking', traditions: ['sami_yoik_tracking'] },
  { id: 'aboriginal_australian_songlines', traditions: ['aboriginal_australian_songlines'] },
  { id: 'hebridean_waulking', traditions: ['hebridean_waulking'] },
  { id: 'irish_spinning_song', traditions: ['irish_spinning_song'] },
  { id: 'sami_vuolle_domestic', traditions: ['sami_vuolle_domestic'] },
  { id: 'romanian_cantece_de_tors', traditions: ['romanian_cantece_de_tors'] },
  { id: 'andean_quechua_spinning', traditions: ['andean_quechua_spinning'] },
  { id: 'indian_jata_gita_grinding', traditions: ['indian_jata_gita_grinding'] },
  { id: 'yiddish_spinning_domestic', traditions: ['yiddish_spinning_domestic'] },
  { id: 'sardinian_boci_de_tela', traditions: ['sardinian_boci_de_tela'] },
  { id: 'faroese_kvaedi', traditions: ['faroese_kvaedi'] },
  { id: 'japanese_domestic_hataori', traditions: ['japanese_domestic_hataori'] },
];

// Compute one fixture's recipe exactly as recipe.js does: hill-climb search,
// then translate. Pure and deterministic in its tradition ids — which is what
// lets the run be sharded across CPU cores below without changing any output.
function computeFixture(fixture) {
  const [primary, ...staples] = fixture.traditions;
  const seed = seedFromTradition(primary, staples);
  if (!seed) return { error: `seedFromTradition failed for ${primary}` };
  try {
    const result = search(seed, { maxIters: 100 });
    return { output: translate(result.config), traditions: fixture.traditions };
  } catch (err) {
    return { error: err.message, traditions: fixture.traditions };
  }
}

// ── worker entry ──────────────────────────────────────────────────────────
// search() is CPU-bound and ~99% of this script's runtime (1198 fixtures ×
// ~0.5s each, single-threaded). Each fixture is independent and deterministic,
// so the full set is sharded round-robin across one worker per core. A worker
// requires this same file (so it has FIXTURES + computeFixture) and only runs
// its stripe, then posts {id: result} back. The `return` short-circuits the
// main flag-parsing/diff section below — workers never reach it.
if (!isMainThread) {
  const { workerIndex, nWorkers } = workerData;
  const out = {};
  for (let i = workerIndex; i < FIXTURES.length; i += nWorkers) {
    out[FIXTURES[i].id] = computeFixture(FIXTURES[i]);
  }
  parentPort.postMessage(out);
  return;
}

// Run every fixture across a worker pool (one per core), merging the shard
// results into a single id→result map identical to a sequential run.
function runFixturesParallel() {
  const nWorkers = Math.max(1, Math.min(os.cpus().length || 2, FIXTURES.length));
  return new Promise((resolve, reject) => {
    const results = {};
    let exited = 0;
    let aborted = false;
    for (let k = 0; k < nWorkers; k++) {
      const w = new Worker(__filename, { workerData: { workerIndex: k, nWorkers } });
      w.on('message', (msg) => Object.assign(results, msg));
      w.on('error', (err) => {
        if (!aborted) {
          aborted = true;
          reject(err);
        }
      });
      w.on('exit', (code) => {
        if (aborted) return;
        if (code !== 0) {
          aborted = true;
          reject(new Error(`worker ${k} exited with code ${code}`));
          return;
        }
        if (++exited === nWorkers) resolve(results);
      });
    }
  });
}

const args = process.argv.slice(2);
const flags = {};
for (let i = 0; i < args.length; i++) {
  const a = args[i];
  if (a.startsWith('--')) {
    const eq = a.indexOf('=');
    if (eq > 0) flags[a.slice(2, eq)] = a.slice(2 + eq + 1 - 2);
    else flags[a.slice(2)] = true;
  }
}
// Re-parse to handle --key=value properly
flags.__parsed = true;
for (let i = 0; i < args.length; i++) {
  const a = args[i];
  if (a.startsWith('--')) {
    const eq = a.indexOf('=');
    if (eq > 0) flags[a.slice(2, eq)] = a.slice(eq + 1);
  }
}

// Generate current output for each fixture. The full unfiltered set runs across
// a worker pool (one per core); a single --fixture, or REGRESSION_SERIAL=1, runs
// inline on this thread. Both paths call the same computeFixture, so the
// id→result map — and therefore the snapshot comparison — is identical either way.
async function runFixtures(filter) {
  const fixtures = filter ? FIXTURES.filter((f) => f.id === filter) : FIXTURES;
  if (filter && fixtures.length === 0) {
    console.error(`Unknown fixture: ${filter}`);
    console.error(`Available: ${FIXTURES.map((f) => f.id).join(', ')}`);
    process.exit(2);
  }
  if (!filter && !process.env.REGRESSION_SERIAL && fixtures.length > 1) {
    return runFixturesParallel();
  }
  const results = {};
  for (const fixture of fixtures) results[fixture.id] = computeFixture(fixture);
  return results;
}

(async () => {
  // ─────────────── --update mode ───────────────
  if (flags.update) {
    if (!fs.existsSync(SNAPSHOT_DIR)) fs.mkdirSync(SNAPSHOT_DIR, { recursive: true });
    const current = await runFixtures(flags.fixture);
    // If updating a single fixture, merge into existing snapshot rather than overwriting
    let snapshot = {};
    if (flags.fixture && fs.existsSync(SNAPSHOT_PATH)) {
      snapshot = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, 'utf8'));
    }
    for (const id of Object.keys(current)) snapshot[id] = current[id];
    fs.writeFileSync(SNAPSHOT_PATH, JSON.stringify(snapshot, null, 2) + '\n');
    console.log(`Snapshot updated: ${SNAPSHOT_PATH}`);
    console.log(`  ${Object.keys(current).length} fixture(s) written`);
    if (flags.verbose) {
      for (const [id, r] of Object.entries(current)) {
        console.log(`  ✓ ${id}`);
        if (r.output) console.log(`      ${r.output}`);
        if (r.error) console.log(`      ERROR: ${r.error}`);
      }
    }
    process.exit(0);
  }

  // ─────────────── default mode: diff ───────────────
  if (!fs.existsSync(SNAPSHOT_PATH)) {
    console.error(`No snapshot at ${SNAPSHOT_PATH}`);
    console.error(`Run with --update first to create one.`);
    process.exit(2);
  }

  const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT_PATH, 'utf8'));
  const current = await runFixtures(flags.fixture);

  const diffs = [];
  const missing = [];
  const newFixtures = [];

  for (const [id, r] of Object.entries(current)) {
    const snap = snapshot[id];
    if (!snap) {
      newFixtures.push(id);
      continue;
    }
    if (r.error || snap.error) {
      if ((r.error || '') !== (snap.error || '')) {
        diffs.push({ id, expected: snap, actual: r });
      }
      continue;
    }
    if (r.output !== snap.output) {
      diffs.push({ id, expected: snap.output, actual: r.output });
    }
  }
  for (const id of Object.keys(snapshot)) {
    if (!current[id] && !flags.fixture) missing.push(id);
  }

  // Report
  const passCount = Object.keys(current).length - diffs.length - newFixtures.length;
  console.log(
    `REGRESSION: ${passCount}/${Object.keys(current).length} fixture(s) match snapshot.\n`
  );

  if (flags.verbose) {
    for (const [id, r] of Object.entries(current)) {
      const status = diffs.find((d) => d.id === id) ? '✗' : newFixtures.includes(id) ? '?' : '✓';
      console.log(`  ${status} ${id}`);
      if (r.output) console.log(`      ${r.output}`);
    }
    console.log('');
  }

  if (diffs.length > 0) {
    console.log(`── DIFFS (${diffs.length}) ──\n`);
    for (const d of diffs) {
      console.log(`✗ ${d.id}`);
      console.log(
        `  expected: ${typeof d.expected === 'string' ? d.expected : JSON.stringify(d.expected)}`
      );
      console.log(
        `  actual:   ${typeof d.actual === 'string' ? d.actual : JSON.stringify(d.actual)}`
      );
      console.log('');
    }
    console.log(`To accept these changes, run:`);
    console.log(`  node scripts/regression_recipes.js --update`);
    console.log(`Or for a single fixture:`);
    console.log(`  node scripts/regression_recipes.js --update --fixture=<id>\n`);
  }

  if (newFixtures.length > 0) {
    console.log(`── NEW FIXTURES (not yet snapshotted) ──`);
    for (const id of newFixtures) console.log(`  ? ${id}`);
    console.log(`  Run --update to add these to the snapshot.\n`);
  }

  if (missing.length > 0) {
    console.log(`── REMOVED FIXTURES (in snapshot but not in code) ──`);
    for (const id of missing) console.log(`  - ${id}`);
    console.log(`  These will persist in the snapshot until --update is run.\n`);
  }

  // A fixture present in code but ABSENT from the snapshot (newFixtures), or a
  // snapshot entry whose fixture vanished (missing), means the baseline no longer
  // covers what it claims to — an emptied or truncated snapshot would otherwise
  // make every fixture "new" and the run pass vacuously. Both are failures: the
  // only path to green is an explicit, reviewed --update.
  if (diffs.length > 0 || newFixtures.length > 0 || missing.length > 0) process.exit(1);
  process.exit(0);
})().catch((err) => {
  console.error('REGRESSION: harness error —', err && err.stack ? err.stack : err);
  process.exit(2);
});
