// atlas.js — the Traditions Atlas: every placed tradition on an Equal Earth
// map, grouped by the catalog's own taxonomy roots rather than by geography.
//
// Loaded by atlas.html as a plain script (no build step — unlike codex.html,
// which is assembled by scripts/build_html.js because it inlines the catalog).
// The same file runs standalone and inside the app's Map view
// (atlas.html?embedded=1), where it asks the app to add a genre to Your recipe
// through postMessage and reports what actually arrived.
//
// TWO THINGS HERE ARE NOT IN THE ORIGINAL DESIGN, and they exist because the
// design could not be clicked:
//
//   1. Display coordinates come from data/atlas-geo.json, generated by
//      scripts/build_atlas_geo.js, which spreads co-located pins over a small
//      land-aware disc. data/geo.json puts many traditions on one coordinate,
//      so a stack projected to one screen point at every zoom.
//   2. openStack() — the location chooser. A bubble that cannot be zoomed apart
//      lists its members instead of zooming into a dead end. This is the floor
//      that makes every pin reachable no matter how deep the stack.
//
// See the header of scripts/build_atlas_geo.js for the measurements.
//
// COLOUR IS NEVER THE ONLY SIGNAL. There are more taxonomy roots than hues a
// reader can tell apart, so each root gets a (hue, shape) pair: seven palette
// hues from src/theme.css times circle / square / diamond / triangle. The
// map markers, the map key, the Genres list, the location chooser and every
// row draw the same pair from the same table, so a marker and its legend entry
// always agree, in either theme.

'use strict';

(function () {
  // ── configuration ──

  // Seven palette hues that stay apart in both themes (Dark's blue and indigo,
  // and Light's red and orange, are too close to share a shape), times four
  // shapes: 28 distinct pairs.
  var HUES = ['blue', 'red', 'green', 'amber', 'violet', 'teal', 'pink'];
  var SHAPES = ['circle', 'square', 'diamond', 'triangle'];

  var CELL = 58; // cluster bin, px
  var CLUSTER_MIN = 4; // a cell with this many pins draws as a bubble
  // With the spread in data/atlas-geo.json, x150 takes individually-clickable
  // pins to ~95%; past that the basemap is too coarse to be worth the extra
  // depth, and the location chooser covers what is left.
  var MAX_ZOOM_FACTOR = 150;
  var MIN_ZOOM_FACTOR = 0.8;
  var PICK_SLOP = 3; // px added to a hit radius
  var STACK_FILTER_MIN = 7; // the chooser gets a filter from this many members
  var STACK_GROUP_MIN = 7; // ...and group headings
  var KEY_ROWS = 5; // groups named in the on-map key
  var LIST_CAP = 14; // rows per region before "more in view"
  var PAN_STEP = 80; // px per arrow key on the map

  // A published Artifact runs under a CSP that blocks fetch, so the standalone
  // build (scripts/build_atlas_standalone.js) ships every sidecar inlined on
  // window.__ATLAS_DATA__ and this file reads from there instead. Same code
  // either way — the artifact is not a separate implementation that can drift.
  var INLINE =
    typeof window !== 'undefined' && window.__ATLAS_DATA__ ? window.__ATLAS_DATA__ : null;
  var CODEX_URL = (INLINE && INLINE.codexUrl) || 'codex.html';
  // The app's Map view loads the atlas as atlas.html?embedded=1. Being framed
  // is not enough: a published Artifact is framed by a host that is not the app.
  var EMBEDDED =
    typeof window !== 'undefined' &&
    window.parent !== window &&
    new URLSearchParams(location.search).get('embedded') === '1';
  document.documentElement.classList.toggle('atlas-embedded', EMBEDDED);
  // Optional, produced by a separate pipeline: id -> { thumbnail, credit,
  // licence }. Absent or unlisted, the inspector shows the group's glyph.
  var IMAGE_MANIFEST = 'references/_image_manifest.json';

  // Below this width the side panels, the chooser and the inspector are sheets
  // over the map instead of docked columns (src/map.css uses the same query).
  function overlay() {
    return !!(window.matchMedia && window.matchMedia('(max-width: 899px)').matches);
  }

  // Canvas colours are read from the shared tokens in src/theme.css (Light or
  // Dark, see src/theme.js) and re-read on a theme change. The DOM uses the
  // same tokens through var(), so a row's glyph and the marker it names match.
  var PAINT = { hues: {} };
  function readPaint() {
    var cs = getComputedStyle(document.documentElement);
    var token = function (name, fallback) {
      return cs.getPropertyValue(name).trim() || fallback;
    };
    PAINT.backdrop = token('--cm-map-backdrop', '#e8eaed');
    PAINT.label = token('--cm-map-label', '#202124');
    PAINT.halo = token('--cm-map-label-halo', 'rgba(255,255,255,0.85)');
    PAINT.ring = token('--cm-map-marker-ring', '#ffffff');
    PAINT.surface = token('--cm-surface', '#ffffff');
    PAINT.text = token('--cm-text', '#202124');
    PAINT.emphasis = token('--cm-emphasis', '#c5221f');
    PAINT.dim = token('--cm-text-disabled', '#9aa0a6');
    PAINT.land = token('--cm-surface-sunken', '#f1f3f4');
    HUES.forEach(function (h) {
      PAINT.hues[h] = token('--cm-' + h, '#1a73e8');
    });
  }

  // ── state ──

  var S = {
    pts: [],
    byId: {},
    nodes: {},
    sigs: {},
    tokenIdx: {},
    roots: [],
    style: {},
    rootCount: {},
    threadDefs: [],
    routes: [],
    land: null,
    meta: { verified: [] },
    images: {},
    cache: {},
    view: { cx: 0, cy: 0, scale: 0 },
    baseScale: 0,
    focus: new Set(),
    qmatch: null,
    hit: [],
    clusters: [],
    sel: null,
    kin: [],
    kinWhy: {},
    thread: null,
    stack: null, // { pts, filter }
    expanded: new Set(),
    routesOn: false,
    routeIndex: null,
    listOpen: false,
    recipeOpen: false,
    adds: {}, // id -> { state: 'adding' | 'done' | 'failed', added, expected }
    opener: null,
    w: 0,
    h: 0,
    dpr: 1,
  };

  var earth = new Image();
  earth.onload = function () {
    draw();
  };
  earth.src = (INLINE && INLINE.earthImage) || 'assets/earth-tiles/200407-v1/overview.webp';
  var tiles =
    !INLINE && window.AtlasTiles && typeof createImageBitmap === 'function'
      ? new window.AtlasTiles(draw)
      : null;
  var el = {};
  function $(id) {
    return document.getElementById(id);
  }

  // ── small helpers ──

  // Human-facing sorts name their locale: bare localeCompare() collates by the
  // runtime's locale and is banned repo-wide (see eslint.config.js).
  function byName(a, b) {
    return a.name.localeCompare(b.name, 'en');
  }
  function esc(s) {
    return String(s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }
  function plural(n, one, many) {
    return n.toLocaleString('en') + ' ' + (n === 1 ? one : many || one + 's');
  }
  function styleOf(r) {
    return S.style[r] || { hue: 'blue', shape: 'circle' };
  }
  function rootColor(r) {
    return PAINT.hues[styleOf(r).hue] || PAINT.text;
  }
  function rootLabel(r) {
    if (r === 'unplaced') return 'Awaiting tree placement';
    return S.nodes[r] ? S.nodes[r].n : r;
  }
  function branchNames(node) {
    var names = [];
    var cur = node;
    while (cur && S.nodes[cur]) {
      names.unshift(S.nodes[cur].n);
      cur = S.nodes[cur].p;
    }
    return names;
  }
  // The group's glyph as inline SVG, coloured by the same token the canvas reads.
  function mark(r, size) {
    var st = styleOf(r);
    var s = size || 12;
    var shape =
      st.shape === 'square'
        ? '<rect x="1.4" y="1.4" width="7.2" height="7.2" rx="1"/>'
        : st.shape === 'diamond'
          ? '<path d="M5 0.3L9.7 5 5 9.7 0.3 5z"/>'
          : st.shape === 'triangle'
            ? '<path d="M5 0.6L9.6 9.2H0.4z"/>'
            : '<circle cx="5" cy="5" r="4.3"/>';
    return (
      '<svg class="mark" width="' +
      s +
      '" height="' +
      s +
      '" viewBox="0 0 10 10" aria-hidden="true" style="fill:var(--cm-' +
      st.hue +
      ')">' +
      shape +
      '</svg>'
    );
  }
  var ICON = {
    close:
      '<svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 6l12 12M18 6L6 18"/></svg>',
    back: '<svg width="16" height="16" viewBox="0 0 24 24" aria-hidden="true"><path d="M19 12H5M11 6l-6 6 6 6"/></svg>',
    chevron:
      '<svg width="16" height="16" viewBox="0 0 24 24" aria-hidden="true"><path d="M9 6l6 6-6 6"/></svg>',
    external:
      '<svg width="16" height="16" viewBox="0 0 24 24" aria-hidden="true"><path d="M14 4h6v6M20 4l-9 9M18 14v5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h5"/></svg>',
    plus: '<svg width="16" height="16" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>',
    check:
      '<svg width="16" height="16" viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12.5l4.5 4.5L19 7.5"/></svg>',
    warn: '<svg width="16" height="16" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l10 18H2z"/><path d="M12 10v5M12 18v.1"/></svg>',
    copy: '<svg width="16" height="16" viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V5a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v10a1 1 0 0 0 1 1h3"/></svg>',
    doc: '<svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true"><path d="M6 3h8l4 4v14H6z"/><path d="M9 12h6M9 16h6"/></svg>',
    wave: '<svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12h3l2-6 4 12 3-9 2 3h6"/></svg>',
    layers:
      '<svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l9 5-9 5-9-5z"/><path d="M3 13l9 5 9-5"/></svg>',
    route:
      '<svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true"><circle cx="6" cy="18" r="2.5"/><circle cx="18" cy="6" r="2.5"/><path d="M8 16.5C13 14 11 8 15.8 7"/></svg>',
    pin: '<svg width="16" height="16" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21s7-6.2 7-11.5A7 7 0 0 0 5 9.5C5 14.8 12 21 12 21z"/><circle cx="12" cy="9.5" r="2.5"/></svg>',
    genre:
      '<svg width="16" height="16" viewBox="0 0 24 24" aria-hidden="true"><path d="M3 12l9-9h8v8l-9 9z"/><circle cx="15.5" cy="8.5" r="1.5"/></svg>',
  };

  // Equal Earth projection.
  function proj(lat, lng) {
    var A1 = 1.340264,
      A2 = -0.081106,
      A3 = 0.000893,
      A4 = 0.003796,
      M = Math.sqrt(3) / 2;
    var la = (lat * Math.PI) / 180,
      lo = (lng * Math.PI) / 180;
    var t = Math.asin(M * Math.sin(la)),
      t2 = t * t,
      t6 = t2 * t2 * t2;
    return [
      (lo * Math.cos(t)) / (M * (A1 + 3 * A2 * t2 + t6 * (7 * A3 + 9 * A4 * t2))),
      t * (A1 + A2 * t2 + t6 * (A3 + A4 * t2)),
    ];
  }

  function toScreen(x, y) {
    var v = S.view;
    return [(x - v.cx) * v.scale + S.w / 2, S.h / 2 - (y - v.cy) * v.scale];
  }
  function fromEvent(e) {
    var r = el.host.getBoundingClientRect();
    return [e.clientX - r.left, e.clientY - r.top];
  }

  // ── boot ──

  function boot() {
    readPaint();
    if (window.UITheme)
      window.UITheme.onChange(function () {
        readPaint();
        draw();
      });
    el.host = $('canvas-host');
    el.list = $('list');
    el.search = $('search');
    el.results = $('results');
    el.count = $('count');
    el.card = $('card');
    el.threadCard = $('thread-card');
    el.stack = $('stack');
    el.tip = $('tip');
    el.provenance = $('provenance');
    el.legendPanel = $('legend-panel');
    el.threadsPanel = $('threads-panel');
    el.routesPanel = $('routes-panel');
    el.key = $('legend-key');
    el.routeChip = $('route-chip');
    el.side = $('side');

    var get = function (u) {
      return fetch(u).then(function (r) {
        if (!r.ok) throw new Error(u + ' ' + r.status);
        return r.json();
      });
    };

    var sources = INLINE
      ? Promise.resolve([
          INLINE.index,
          INLINE.geo,
          INLINE.sigs,
          INLINE.world,
          INLINE.treeMap,
          INLINE.nodes,
          INLINE.routes,
          INLINE.threads,
          INLINE.meta,
        ])
      : Promise.all([
          get('api/traditions/index.json'),
          get('data/atlas-geo.json'),
          get('references/_tradition_signatures.json'),
          get('data/countries.geo.json'),
          get('data/tree-map.json'),
          get('data/tree-nodes.json'),
          get('data/routes.json'),
          get('data/threads.json'),
          get('data/geo-meta.json'),
        ]);

    sources
      .then(function (r) {
        ingest(r[0], r[1].coords, r[2], r[3], r[4], r[5], r[6], r[7], r[8]);
        setupCanvas();
        wireControls();
        $('loading').textContent = S.pts.length + ' traditions loaded.';
        $('loading').classList.add('sr-only');
        renderProvenance();
        renderLegend();
        renderThreads();
        renderRoutes();
        // Docked on a wide map, Genres starts open as the full legend.
        if (!overlay()) setPanel('territories');
        syncList();
        syncControls();
        loadImages();
        var deep = new URLSearchParams(location.search).get('trad');
        if (deep && S.byId[deep]) {
          select(S.byId[deep]);
          flyTo(S.byId[deep]);
        }
      })
      .catch(function (err) {
        el.count.textContent = 'Not loaded';
        $('loading').classList.remove('sr-only');
        $('loading').innerHTML =
          '<div class="cm-empty" data-tone="danger"><strong>The map did not load.</strong>' +
          '<span>' +
          esc(err && err.message ? err.message : 'The catalog could not be fetched.') +
          '</span><span class="cm-empty-actions"><button type="button" data-act="reload">Try again</button>' +
          '<a href="api/all.json">Every recipe as JSON</a></span></div>';
        var again = document.querySelector('[data-act="reload"]');
        if (again)
          again.addEventListener('click', function () {
            location.reload();
          });
        el.list.innerHTML =
          '<p class="list-empty">The catalog did not load. Every recipe is still available at ' +
          '<a href="api/all.json">api/all.json</a>.</p>';
      });
  }

  function ingest(idx, geo, sigs, world, treeMap, nodes, routes, threads, meta) {
    S.sigs = sigs;
    S.nodes = nodes;
    S.meta = meta;
    S.threadDefs = threads.threads;

    Object.keys(sigs).forEach(function (id) {
      sigs[id].forEach(function (t) {
        var k = t.toLowerCase();
        (S.tokenIdx[k] = S.tokenIdx[k] || []).push(id);
      });
    });

    S.roots = Object.keys(nodes).filter(function (k) {
      return nodes[k].p === null;
    });
    S.roots.push('unplaced');

    S.pts = idx.items
      .filter(function (t) {
        return geo[t.id];
      })
      .map(function (t) {
        var g = geo[t.id];
        var p = proj(g[0], g[1]);
        var node = treeMap[t.id] || null;
        var root = node ? node.split('.')[0] : 'unplaced';
        return {
          id: t.id,
          name: t.name.replace(/&amp;/g, '&'),
          node: node,
          root: root,
          lat: g[0],
          lng: g[1],
          place: g[2],
          // Sidebar bucket, from the table in scripts/_atlas_regions.js.
          region: g[3],
          x: p[0],
          y: p[1],
        };
      });
    S.pts.forEach(function (p) {
      S.byId[p.id] = p;
      S.rootCount[p.root] = (S.rootCount[p.root] || 0) + 1;
    });

    // Largest groups first get the plainest glyph (a circle); hues cycle
    // before shapes, so no two roots share a (hue, shape) pair until there
    // are more roots than HUES x SHAPES.
    S.roots = S.roots.filter(function (r) {
      return S.rootCount[r];
    });
    S.roots
      .slice()
      .sort(function (a, b) {
        return S.rootCount[b] - S.rootCount[a] || (a < b ? -1 : 1);
      })
      .forEach(function (r, i) {
        S.style[r] = {
          hue: HUES[i % HUES.length],
          shape: SHAPES[Math.floor(i / HUES.length) % SHAPES.length],
        };
      });

    S.land = new Path2D();
    var addRing = function (ring) {
      ring.forEach(function (c, i) {
        var p = proj(c[1], c[0]);
        if (i === 0) S.land.moveTo(p[0], p[1]);
        else S.land.lineTo(p[0], p[1]);
      });
      S.land.closePath();
    };
    world.features.forEach(function (f) {
      if (!f.geometry) return;
      if (f.geometry.type === 'Polygon') f.geometry.coordinates.forEach(addRing);
      else if (f.geometry.type === 'MultiPolygon')
        f.geometry.coordinates.forEach(function (poly) {
          poly.forEach(addRing);
        });
    });

    S.routes = routes.routes
      .map(function (r) {
        var end = function (e) {
          if (typeof e === 'string') return S.byId[e];
          var pr = proj(e[0], e[1]);
          return { x: pr[0], y: pr[1], name: e[2] };
        };
        var a = end(r.a),
          b = end(r.b);
        return a && b ? { ax: a.x, ay: a.y, bx: b.x, by: b.y, a: a, b: b, label: r.label } : null;
      })
      .filter(Boolean);
  }

  // The image manifest is optional and comes from a separate pipeline. Only an
  // entry with a thumbnail URL and a credit or licence is ever shown.
  function loadImages() {
    if (INLINE) {
      if (INLINE.images) S.images = INLINE.images;
      return;
    }
    fetch(IMAGE_MANIFEST)
      .then(function (r) {
        return r.ok ? r.json() : null;
      })
      .then(function (m) {
        if (!m || typeof m !== 'object') return;
        S.images = m.images && typeof m.images === 'object' ? m.images : m;
        if (S.sel) renderCard();
      })
      .catch(function () {
        /* No manifest: every inspector shows its group glyph instead. */
      });
  }
  function imageFor(id) {
    var e = S.images && S.images[id];
    if (!e || typeof e !== 'object') return null;
    var src = e.thumbnail || e.thumb || e.url || e.src;
    var licence = e.licence || e.license || '';
    var credit = e.credit || e.author || e.attribution || '';
    if (typeof src !== 'string' || !/^(https?:)?\/\/|^[\w./-]+$/.test(src)) return null;
    if (!credit && !licence) return null;
    return { src: src, credit: String(credit), licence: String(licence), link: e.source || e.page };
  }

  // One persistent live region: a re-rendered status node is often not read.
  function announce(text) {
    var live = $('map-live');
    if (!live) return;
    live.textContent = '';
    setTimeout(function () {
      live.textContent = text;
    }, 30);
  }

  function metaCount(v) {
    return typeof v === 'number' ? v : (v || []).length;
  }
  function renderProvenance() {
    // Two counts, never added together. A model re-derived every coordinate
    // blind and a person has checked none of them, and those are different
    // claims — collapsing them into one "verified" number is the overclaim
    // this panel exists to avoid. See the note in data/geo-meta.json.
    // Either shape: the live page fetches data/geo-meta.json and gets the id
    // lists, the standalone build inlines the COUNTS instead.
    var reviewed = metaCount(S.meta.reviewed);
    var verified = metaCount(S.meta.verified);
    var h =
      '<div class="info-head"><h2 id="info-title">Map information</h2>' +
      '<button class="icon-btn" type="button" data-act="close-info" aria-label="Close map information">' +
      ICON.close +
      '</button></div>' +
      '<p class="info-lead">Bubbles count documented scenes, not musical abundance. A bubble ' +
      'says how many catalogued traditions are placed there; a quiet region is under-documented, ' +
      'not silent.</p>' +
      '<dl class="info-stats">' +
      '<div><dt>Pins drawn</dt><dd>' +
      S.pts.length.toLocaleString('en') +
      '</dd></div>' +
      '<div><dt>Model-reviewed coordinates</dt><dd>' +
      reviewed.toLocaleString('en') +
      '</dd></div>' +
      '<div><dt>Human-verified coordinates</dt><dd>' +
      verified.toLocaleString('en') +
      '</dd></div></dl>' +
      '<p class="info-note">Model-reviewed means a model re-derived the place' +
      (S.meta.reviewed_on ? ' (' + esc(S.meta.reviewed_on) + ')' : '') +
      ' without seeing the file; no person has checked it. Human-verified is a separate list and ' +
      'is never counted together with it. Corrections welcome.</p>' +
      '<p class="info-note">Pins that share a place are spread up to 25 km apart so each can be ' +
      'clicked; the documented place name is unchanged.</p>' +
      '<h3>How filters combine</h3><ul class="info-rules">' +
      '<li>Choosing a route clears genre groups, a collection and search.</li>' +
      '<li>Choosing a collection replaces genre groups and search.</li>' +
      '<li>Typing a search or choosing a genre group ends a collection.</li>' +
      '<li>Genre groups and search can be combined with each other.</li></ul>' +
      '<p class="info-note">Satellite imagery: NASA Blue Marble Next Generation (July 2004), ' +
      'without borders. Equal Earth projection; detail tiles load as you zoom.</p>' +
      '<button class="cm-btn cm-btn-outline" type="button" data-act="reset-layout">Reset layout</button>';
    el.provenance.innerHTML = h;
  }

  function setInfo(open) {
    el.provenance.hidden = !open;
    $('t-info').setAttribute('aria-expanded', String(open));
    if (open) {
      var close = el.provenance.querySelector('[data-act="close-info"]');
      if (close) close.focus();
    }
  }

  // ── canvas ──

  function setupCanvas() {
    var cv = document.createElement('canvas');
    cv.style.cssText = 'position:absolute;inset:0;width:100%;height:100%;display:block;';
    cv.setAttribute('aria-hidden', 'true');
    el.host.appendChild(cv);
    S.cv = cv;

    var resize = function () {
      var r = el.host.getBoundingClientRect();
      var dpr = window.devicePixelRatio || 1;
      S.w = r.width;
      S.h = r.height;
      cv.width = r.width * dpr;
      cv.height = r.height * dpr;
      S.dpr = dpr;
      if (!S.view.scale && S.w && S.h) {
        S.baseScale = Math.min(S.w / 5.6, S.h / 2.75);
        S.view.scale = S.baseScale;
      }
      draw();
      scheduleListSync();
    };
    new ResizeObserver(resize).observe(el.host);
    resize();

    var drag = null,
      pinch = null,
      moved = false;
    el.host.addEventListener('pointerdown', function (e) {
      if (el.host.setPointerCapture && e.pointerId !== undefined)
        el.host.setPointerCapture(e.pointerId);
      if (pinch) return;
      drag = { x: e.clientX, y: e.clientY, cx: S.view.cx, cy: S.view.cy, id: e.pointerId };
      moved = false;
      el.host.style.cursor = 'grabbing';
    });
    el.host.addEventListener('pointermove', function (e) {
      if (drag && e.pointerId === drag.id) {
        var dx = e.clientX - drag.x,
          dy = e.clientY - drag.y;
        if (Math.abs(dx) + Math.abs(dy) > 3) moved = true;
        S.view.cx = drag.cx - dx / S.view.scale;
        S.view.cy = drag.cy + dy / S.view.scale;
        draw();
        scheduleListSync();
      } else {
        hover(e);
      }
    });
    el.host.addEventListener('pointerup', function (e) {
      if (drag && e.pointerId === drag.id) {
        el.host.style.cursor = 'grab';
        if (!moved) onMapClick(e);
        drag = null;
      }
    });
    el.host.addEventListener('pointercancel', function () {
      drag = null;
      el.host.style.cursor = 'grab';
    });
    el.host.addEventListener('pointerleave', function () {
      el.tip.hidden = true;
    });
    el.host.addEventListener(
      'wheel',
      function (e) {
        e.preventDefault();
        zoomAt(e.clientX, e.clientY, Math.exp(-e.deltaY * 0.0015));
      },
      { passive: false }
    );
    el.host.addEventListener(
      'touchmove',
      function (e) {
        if (e.touches.length === 2) {
          e.preventDefault();
          var a = e.touches[0],
            b = e.touches[1];
          var d = Math.hypot(a.clientX - b.clientX, a.clientY - b.clientY);
          if (pinch) zoomAt((a.clientX + b.clientX) / 2, (a.clientY + b.clientY) / 2, d / pinch);
          pinch = d;
          drag = null;
        }
      },
      { passive: false }
    );
    el.host.addEventListener(
      'touchend',
      function (e) {
        if (e.touches.length < 2) pinch = null;
      },
      { passive: true }
    );
    // The keyboard equivalent of drag and pinch, on the focusable map itself.
    el.host.addEventListener('keydown', function (e) {
      var r = el.host.getBoundingClientRect();
      var k = e.key;
      var step = (e.shiftKey ? 3 : 1) * PAN_STEP;
      if (k === 'ArrowLeft') S.view.cx -= step / S.view.scale;
      else if (k === 'ArrowRight') S.view.cx += step / S.view.scale;
      else if (k === 'ArrowUp') S.view.cy += step / S.view.scale;
      else if (k === 'ArrowDown') S.view.cy -= step / S.view.scale;
      else if (k === '+' || k === '=') return zoomKey(e, r, 1.7);
      else if (k === '-' || k === '_') return zoomKey(e, r, 1 / 1.7);
      else if (k === '0') {
        e.preventDefault();
        resetView();
        return;
      } else return;
      e.preventDefault();
      draw();
      scheduleListSync();
    });
  }
  function zoomKey(e, r, k) {
    e.preventDefault();
    zoomAt(r.left + S.w / 2, r.top + S.h / 2, k);
  }

  function maxScale() {
    return S.baseScale * MAX_ZOOM_FACTOR;
  }

  function zoomAt(clientX, clientY, k) {
    var v = S.view;
    var r = el.host.getBoundingClientRect();
    var sx = clientX - r.left,
      sy = clientY - r.top;
    var px = v.cx + (sx - S.w / 2) / v.scale,
      py = v.cy - (sy - S.h / 2) / v.scale;
    v.scale = Math.max(S.baseScale * MIN_ZOOM_FACTOR, Math.min(maxScale(), v.scale * k));
    v.cx = px - (sx - S.w / 2) / v.scale;
    v.cy = py + (sy - S.h / 2) / v.scale;
    draw();
    scheduleListSync();
  }

  function flyTo(pt, targetScale) {
    var v = S.view;
    var from = { cx: v.cx, cy: v.cy, s: v.scale };
    var to = {
      cx: pt.x,
      cy: pt.y,
      s: targetScale || Math.max(v.scale, S.baseScale * 10),
    };
    // A narrow map's inspector is a sheet over its lower part: land a chosen
    // tradition in the part that stays visible.
    if (pt.id && overlay() && !el.card.hidden) to.cy = pt.y - (0.28 * S.h) / to.s;
    var t0 = performance.now(),
      D = matchMedia('(prefers-reduced-motion: reduce)').matches ? 1 : 420;
    var step = function () {
      var t = Math.min(1, (performance.now() - t0) / D);
      var e = 1 - Math.pow(1 - t, 3);
      v.cx = from.cx + (to.cx - from.cx) * e;
      v.cy = from.cy + (to.cy - from.cy) * e;
      v.scale = from.s + (to.s - from.s) * e;
      draw();
      if (t < 1) requestAnimationFrame(step);
      else scheduleListSync();
    };
    step();
  }

  // Frame a set of projected points, never tighter than 20x the world view.
  function fitPoints(pts) {
    if (!pts.length) return;
    if (pts.length === 1) return flyTo(pts[0]);
    var xs = pts.map(function (p) {
        return p.x;
      }),
      ys = pts.map(function (p) {
        return p.y;
      });
    var x0 = Math.min.apply(null, xs),
      x1 = Math.max.apply(null, xs),
      y0 = Math.min.apply(null, ys),
      y1 = Math.max.apply(null, ys);
    var sc = Math.max(
      S.baseScale * MIN_ZOOM_FACTOR,
      Math.min(S.baseScale * 20, Math.min(S.w / (x1 - x0 + 0.35), S.h / (y1 - y0 + 0.35)) * 0.75)
    );
    flyTo({ x: (x0 + x1) / 2, y: (y0 + y1) / 2 }, sc);
  }

  function resetView() {
    closeStack();
    flyTo({ x: 0, y: 0 }, S.baseScale);
  }

  // What "Fit" frames right now, most specific first. Nothing: no button.
  function fitTarget() {
    if (S.routesOn && S.routeIndex !== null && S.routes[S.routeIndex]) {
      var r = S.routes[S.routeIndex];
      return { label: 'Fit route', pts: [r.a, r.b] };
    }
    if (S.thread)
      return {
        label: 'Fit collection',
        pts: S.thread.stops
          .map(function (id) {
            return S.byId[id];
          })
          .filter(Boolean),
      };
    if (S.sel && S.byId[S.sel.id]) {
      return { label: 'Fit selection', pts: [S.byId[S.sel.id]].concat(S.kin) };
    }
    if (S.focus.size || S.qmatch) {
      var vis = visiblePts();
      if (vis.length && vis.length < S.pts.length) return { label: 'Fit results', pts: vis };
    }
    return null;
  }
  function syncFit() {
    var t = fitTarget();
    var b = $('zoom-fit');
    b.hidden = !t;
    if (t) {
      b.textContent = t.label;
      b.title = t.label + ' in the map';
    }
  }

  // ── clustering ──

  function visiblePts() {
    var hasFocus = S.focus.size > 0,
      hasQ = !!S.qmatch;
    if (!hasFocus && !hasQ) return S.pts;
    return S.pts.filter(function (p) {
      return (!hasFocus || S.focus.has(p.root)) && (!hasQ || S.qmatch.has(p.id));
    });
  }

  function bubbleRadius(n) {
    return Math.max(12, Math.min(27, 8 + Math.sqrt(n) * 2.1));
  }

  function buildClusters() {
    var map = new Map();
    var vis = visiblePts();
    for (var i = 0; i < vis.length; i++) {
      var p = vis[i];
      var s = toScreen(p.x, p.y);
      if (s[0] < -40 || s[1] < -40 || s[0] > S.w + 40 || s[1] > S.h + 40) continue;
      var key = Math.floor(s[0] / CELL) + ':' + Math.floor(s[1] / CELL);
      var c = map.get(key);
      if (!c) {
        c = { sx: 0, sy: 0, pts: [] };
        map.set(key, c);
      }
      c.sx += s[0];
      c.sy += s[1];
      c.pts.push(p);
    }
    var cls = [];
    map.forEach(function (c) {
      cls.push({ sx: c.sx / c.pts.length, sy: c.sy / c.pts.length, pts: c.pts });
    });
    var merged = true;
    while (merged) {
      merged = false;
      outer: for (var a = 0; a < cls.length; a++) {
        if (cls[a].pts.length < CLUSTER_MIN) continue;
        for (var b = a + 1; b < cls.length; b++) {
          if (cls[b].pts.length < CLUSTER_MIN) continue;
          var A = cls[a],
            B = cls[b];
          if (
            Math.hypot(A.sx - B.sx, A.sy - B.sy) <
            (bubbleRadius(A.pts.length) + bubbleRadius(B.pts.length)) * 0.62
          ) {
            var n = A.pts.length + B.pts.length;
            A.sx = (A.sx * A.pts.length + B.sx * B.pts.length) / n;
            A.sy = (A.sy * A.pts.length + B.sy * B.pts.length) / n;
            A.pts = A.pts.concat(B.pts);
            cls.splice(b, 1);
            merged = true;
            break outer;
          }
        }
      }
    }
    return cls;
  }

  // Would zooming in actually break this bubble apart? Project its members at
  // the scale the click would land on; if they still share one bin, zooming is
  // theatre and the location chooser is the honest response.
  function canSplit(cluster) {
    var v = S.view;
    var target = Math.min(maxScale(), v.scale * 2.6);
    if (target <= v.scale * 1.001) return false; // already at max zoom
    var cx = v.cx + (cluster.sx - S.w / 2) / v.scale;
    var cy = v.cy - (cluster.sy - S.h / 2) / v.scale;
    var seen = null;
    for (var i = 0; i < cluster.pts.length; i++) {
      var p = cluster.pts[i];
      var sx = (p.x - cx) * target + S.w / 2;
      var sy = S.h / 2 - (p.y - cy) * target;
      var key = Math.floor(sx / CELL) + ':' + Math.floor(sy / CELL);
      if (seen === null) seen = key;
      else if (key !== seen) return true;
    }
    return false;
  }

  // ── drawing ──

  // One marker: the group's shape in the group's hue, ringed for contrast
  // on the imagery. The same pair the DOM glyph (mark()) draws.
  // Polygons go through Path2D, circles through arc(); fill and stroke take
  // whichever was built.
  function markPath(ctx, x, y, r, shape) {
    var pts =
      shape === 'square'
        ? [
            [-0.86, -0.86],
            [0.86, -0.86],
            [0.86, 0.86],
            [-0.86, 0.86],
          ]
        : shape === 'diamond'
          ? [
              [0, -1.15],
              [1.15, 0],
              [0, 1.15],
              [-1.15, 0],
            ]
          : shape === 'triangle'
            ? [
                [0, -1.15],
                [1.05, 0.8],
                [-1.05, 0.8],
              ]
            : null;
    if (!pts) {
      ctx.beginPath();
      ctx.arc(x, y, r, 0, 7);
      return null;
    }
    var path = new Path2D();
    pts.forEach(function (q, i) {
      if (i === 0) path.moveTo(x + q[0] * r, y + q[1] * r);
      else path.lineTo(x + q[0] * r, y + q[1] * r);
    });
    path.closePath();
    return path;
  }
  function drawMark(ctx, x, y, r, root, ringWidth) {
    var path = markPath(ctx, x, y, r, styleOf(root).shape);
    ctx.fillStyle = rootColor(root);
    ctx.strokeStyle = PAINT.ring;
    ctx.lineWidth = ringWidth || 1.2;
    if (path) {
      ctx.fill(path);
      ctx.stroke(path);
    } else {
      ctx.fill();
      ctx.stroke();
    }
  }

  function draw() {
    if (!S.cv || !S.land) return;
    var ctx = S.cv.getContext('2d');
    var v = S.view;
    ctx.setTransform(S.dpr, 0, 0, S.dpr, 0, 0);
    ctx.clearRect(0, 0, S.w, S.h);
    if (!PAINT.backdrop) readPaint();
    ctx.fillStyle = PAINT.backdrop;
    ctx.fillRect(0, 0, S.w, S.h);

    ctx.save();
    ctx.translate(S.w / 2, S.h / 2);
    ctx.scale(v.scale, -v.scale);
    ctx.translate(-v.cx, -v.cy);
    if (earth.complete && earth.naturalWidth) {
      ctx.save();
      ctx.translate(-2.70663, 1.317363);
      ctx.scale(1, -1);
      ctx.drawImage(earth, 0, 0, 5.41326, 2.634726);
      ctx.restore();
    } else {
      ctx.fillStyle = PAINT.land;
      ctx.fill(S.land);
    }
    if (tiles) tiles.draw(ctx, v, S.w, S.h, S.dpr);
    ctx.restore();

    if (S.routesOn) drawRoutes(ctx);

    var cls = buildClusters();
    S.clusters = cls;

    S.hit = [];
    drawDimmed(ctx);

    var stackIds = S.stack
      ? new Set(
          S.stack.pts.map(function (p) {
            return p.id;
          })
        )
      : null;

    for (var i = 0; i < cls.length; i++) {
      var c = cls[i];
      if (c.pts.length >= CLUSTER_MIN) {
        drawBubble(ctx, c, stackIds);
      } else {
        drawDots(ctx, c, stackIds);
      }
    }

    if (S.routesOn) {
      drawRouteEnds(ctx);
      for (var r = 0; r < S.routes.length; r++) {
        var rt = S.routes[r];
        if (rt._mx !== undefined)
          S.hit.push({ sx: rt._mx, sy: rt._my, r: 16, route: rt.label, routeIndex: r });
      }
    }

    drawThread(ctx);
    drawSelection(ctx);
  }

  function drawRoutes(ctx) {
    ctx.save();
    for (var i = 0; i < S.routes.length; i++) {
      var r = S.routes[i];
      // Off-screen routes must not retain hit targets from a previous view.
      delete r._mx;
      delete r._my;
      var a = toScreen(r.ax, r.ay),
        b = toScreen(r.bx, r.by);
      if (Math.max(a[0], b[0]) < -60 || Math.min(a[0], b[0]) > S.w + 60) continue;
      var on = S.routeIndex === i;
      // A drawn curve joins two catalogued endpoints; it claims no path or
      // intermediate stop, so it is dashed unless selected and never passes
      // through a labelled place.
      ctx.setLineDash(on ? [] : [5, 4]);
      ctx.globalAlpha = on ? 1 : S.routeIndex === null ? 0.7 : 0.35;
      ctx.strokeStyle = PAINT.emphasis;
      ctx.lineWidth = on ? 3 : 1.4;
      var mx = (a[0] + b[0]) / 2;
      var my = (a[1] + b[1]) / 2 - Math.min(110, Math.hypot(b[0] - a[0], b[1] - a[1]) * 0.22) - 10;
      ctx.beginPath();
      ctx.moveTo(a[0], a[1]);
      ctx.quadraticCurveTo(mx, my, b[0], b[1]);
      ctx.stroke();
      r._mx = (a[0] + 2 * mx + b[0]) / 4;
      r._my = (a[1] + 2 * my + b[1]) / 4;
    }
    ctx.restore();
  }

  // The selected route's endpoints, numbered in the catalog's own order.
  function drawRouteEnds(ctx) {
    var r = S.routeIndex !== null ? S.routes[S.routeIndex] : null;
    if (!r) return;
    [r.a, r.b].forEach(function (end, i) {
      var s = toScreen(end.x, end.y);
      ctx.beginPath();
      ctx.arc(s[0], s[1], 11, 0, 7);
      ctx.fillStyle = PAINT.surface;
      ctx.fill();
      ctx.strokeStyle = PAINT.emphasis;
      ctx.lineWidth = 2.5;
      ctx.stroke();
      ctx.fillStyle = PAINT.text;
      ctx.font = '700 12px Arial, sans-serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(String(i + 1), s[0], s[1] + 0.5);
      ctx.textAlign = 'left';
      ctx.lineWidth = 3;
      ctx.strokeStyle = PAINT.halo;
      ctx.font = '600 12px Arial, sans-serif';
      var label = end.id ? end.place : end.name;
      ctx.strokeText(label, s[0] + 15, s[1]);
      ctx.fillStyle = PAINT.label;
      ctx.fillText(label, s[0] + 15, s[1]);
      if (end.id) S.hit.push({ sx: s[0], sy: s[1], r: 12, pt: end });
    });
  }

  function drawDimmed(ctx) {
    if (S.focus.size === 0 && !S.qmatch) return;
    var lit = new Set(
      visiblePts().map(function (p) {
        return p.id;
      })
    );
    ctx.save();
    ctx.globalAlpha = 0.55;
    ctx.fillStyle = PAINT.dim;
    for (var i = 0; i < S.pts.length; i++) {
      var p = S.pts[i];
      if (lit.has(p.id)) continue;
      var s = toScreen(p.x, p.y);
      if (s[0] < -10 || s[1] < -10 || s[0] > S.w + 10 || s[1] > S.h + 10) continue;
      ctx.beginPath();
      ctx.arc(s[0], s[1], 2, 0, 7);
      ctx.fill();
      // Dimmed pins are hit-testable but sort last: a lit pin under the cursor
      // always wins (see pickAll).
      S.hit.push({ sx: s[0], sy: s[1], r: 6, pt: p, dim: true });
    }
    ctx.restore();
  }

  // A bubble is a count, not a category: a neutral disc with the count, and a
  // ring divided by the share of each group inside it.
  function groupCounts(pts) {
    var counts = {};
    for (var i = 0; i < pts.length; i++) counts[pts[i].root] = (counts[pts[i].root] || 0) + 1;
    return Object.keys(counts)
      .sort(function (a, b) {
        return counts[b] - counts[a] || (a < b ? -1 : 1);
      })
      .map(function (r) {
        return [r, counts[r]];
      });
  }
  function drawBubble(ctx, c, stackIds) {
    var r = bubbleRadius(c.pts.length);
    var open = stackIds && c.pts.length && stackIds.has(c.pts[0].id);
    ctx.save();
    if (open) {
      ctx.beginPath();
      ctx.arc(c.sx, c.sy, r + 5, 0, 7);
      ctx.strokeStyle = PAINT.emphasis;
      ctx.lineWidth = 2.5;
      ctx.stroke();
    }
    ctx.beginPath();
    ctx.arc(c.sx, c.sy, r, 0, 7);
    ctx.globalAlpha = 0.94;
    ctx.fillStyle = PAINT.surface;
    ctx.fill();
    ctx.globalAlpha = 1;
    var start = -Math.PI / 2;
    var groups = groupCounts(c.pts);
    ctx.lineWidth = 4;
    groups.forEach(function (g) {
      var sweep = (Math.PI * 2 * g[1]) / c.pts.length;
      ctx.beginPath();
      ctx.arc(c.sx, c.sy, r - 2, start, start + sweep);
      ctx.strokeStyle = rootColor(g[0]);
      ctx.stroke();
      start += sweep;
    });
    ctx.fillStyle = PAINT.text;
    ctx.font = '700 ' + (c.pts.length > 999 ? 10 : 12) + 'px Arial, sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(String(c.pts.length), c.sx, c.sy + 0.5);
    ctx.restore();
    S.hit.push({ sx: c.sx, sy: c.sy, r: r, cluster: c });
  }

  function drawDots(ctx, c, stackIds) {
    var labelZoom = S.view.scale > S.baseScale * 12;
    for (var i = 0; i < c.pts.length; i++) {
      var p = c.pts[i];
      var s = toScreen(p.x, p.y);
      var r = 4.5;
      if (stackIds && stackIds.has(p.id)) {
        ctx.beginPath();
        ctx.arc(s[0], s[1], r + 4.5, 0, 7);
        ctx.strokeStyle = PAINT.emphasis;
        ctx.lineWidth = 1.8;
        ctx.stroke();
      }
      drawMark(ctx, s[0], s[1], r, p.root);
      if (labelZoom) {
        ctx.font = '12px Arial, sans-serif';
        ctx.textAlign = 'left';
        ctx.textBaseline = 'middle';
        ctx.lineWidth = 3;
        ctx.strokeStyle = PAINT.halo;
        ctx.strokeText(p.name, s[0] + r + 5, s[1]);
        ctx.fillStyle = PAINT.label;
        ctx.fillText(p.name, s[0] + r + 5, s[1]);
      }
      S.hit.push({ sx: s[0], sy: s[1], r: r + 4, pt: p });
    }
  }

  function drawThread(ctx) {
    var th = S.thread;
    if (!th) return;
    var stops = th.stops
      .map(function (id) {
        return S.byId[id];
      })
      .filter(Boolean);
    ctx.save();
    // Collections group genres by theme; their list order is not a migration
    // path, so no line joins the stops.
    stops.forEach(function (p) {
      var s = toScreen(p.x, p.y);
      ctx.beginPath();
      ctx.arc(s[0], s[1], 10, 0, 7);
      ctx.strokeStyle = PAINT.ring;
      ctx.lineWidth = 3;
      ctx.stroke();
      ctx.strokeStyle = rootColor(p.root);
      ctx.lineWidth = 1.8;
      ctx.stroke();
      S.hit.push({ sx: s[0], sy: s[1], r: 11, pt: p });
    });
    ctx.restore();
  }

  function drawSelection(ctx) {
    if (!S.sel) return;
    var p = S.byId[S.sel.id];
    if (!p) return;
    var s = toScreen(p.x, p.y);
    for (var i = 0; i < S.kin.length; i++) {
      var kp = S.kin[i];
      var k = toScreen(kp.x, kp.y);
      var mx = (s[0] + k[0]) / 2;
      var my = (s[1] + k[1]) / 2 - Math.min(120, Math.hypot(k[0] - s[0], k[1] - s[1]) * 0.25) - 12;
      ctx.save();
      ctx.globalAlpha = 0.6;
      ctx.beginPath();
      ctx.moveTo(s[0], s[1]);
      ctx.quadraticCurveTo(mx, my, k[0], k[1]);
      ctx.strokeStyle = rootColor(kp.root);
      ctx.lineWidth = 1.4;
      ctx.stroke();
      ctx.restore();
      drawMark(ctx, k[0], k[1], 5, kp.root);
    }
    ctx.beginPath();
    ctx.arc(s[0], s[1], 9.5, 0, 7);
    ctx.strokeStyle = PAINT.emphasis;
    ctx.lineWidth = 2.5;
    ctx.stroke();
    drawMark(ctx, s[0], s[1], 5.5, p.root, 1.5);
  }

  // ── hit testing ──

  // Returns EVERY hit under the cursor, nearest first. Of two dots at the same
  // pixel the second must stay reachable, so callers decide what a tie means;
  // onMapClick turns it into the location chooser.
  function pickAll(e) {
    var m = fromEvent(e);
    var hits = [];
    for (var i = 0; i < S.hit.length; i++) {
      var h = S.hit[i];
      var d = Math.hypot(h.sx - m[0], h.sy - m[1]);
      if (d < h.r + PICK_SLOP) hits.push({ h: h, d: d });
    }
    hits.sort(function (a, b) {
      // lit before dimmed, then by distance
      var ad = a.h.dim ? 1 : 0,
        bd = b.h.dim ? 1 : 0;
      if (ad !== bd) return ad - bd;
      return a.d - b.d;
    });
    return hits;
  }

  function hover(e) {
    var hits = pickAll(e);
    var top = hits.length ? hits[0].h : null;
    el.host.style.cursor = top ? 'pointer' : 'grab';
    var m = fromEvent(e);
    var text = '';
    if (top && top.pt) {
      var coincident = hits.filter(function (x) {
        return x.h.pt;
      }).length;
      text = top.pt.name + ' · ' + rootLabel(top.pt.root);
      if (coincident > 1) text += ' · +' + (coincident - 1) + ' here';
    } else if (top && top.route) {
      text = 'Route: ' + top.route;
    } else if (top && top.cluster) {
      text =
        plural(top.cluster.pts.length, 'tradition') +
        ' documented here' +
        (canSplit(top.cluster) ? ' · click to zoom in' : ' · click to list them');
    }
    if (!text) {
      el.tip.hidden = true;
      return;
    }
    el.tip.textContent = text;
    el.tip.style.left = m[0] + 'px';
    el.tip.style.top = m[1] + 'px';
    el.tip.hidden = false;
  }

  function onMapClick(e) {
    var hits = pickAll(e);
    if (!hits.length) {
      closeStack();
      if (S.sel) select(null);
      renderThreadCard();
      return;
    }
    var top = hits[0].h;

    if (top.cluster) {
      if (canSplit(top.cluster)) {
        closeStack();
        var v = S.view;
        var px = v.cx + (top.sx - S.w / 2) / v.scale;
        var py = v.cy - (top.sy - S.h / 2) / v.scale;
        flyTo({ x: px, y: py }, Math.min(maxScale(), v.scale * 2.6));
      } else {
        openStack(top.cluster.pts);
      }
      return;
    }

    if (top.route) {
      pickRoute(top.routeIndex);
      setPanel('routes');
      return;
    }

    // Dots sharing a pixel: list them rather than silently picking one.
    var pts = [];
    var seen = {};
    for (var i = 0; i < hits.length; i++) {
      var h = hits[i].h;
      if (h.pt && !seen[h.pt.id]) {
        seen[h.pt.id] = 1;
        pts.push(h.pt);
      }
    }
    if (pts.length > 1) {
      openStack(pts);
      return;
    }
    closeStack();
    S.opener = null;
    select(top.pt);
  }

  // ── the location chooser ──
  //
  // Opened when a bubble cannot be zoomed apart, or when dots share a pixel.
  // Every member is listed, grouped, searchable and focusable, so no pin is
  // ever unreachable and the map has a keyboard route into stacked data that
  // the canvas cannot give. Docked, it takes the place of In view; as a sheet
  // it sits over the map. Either way Back returns to where you were.

  function openStack(pts) {
    var wasOpen = S.stack;
    S.stack = { pts: pts.slice(), filter: '', tab: wasOpen ? wasOpen.tab : openTab() };
    setCollapsed(false);
    // Docked, the chooser gets the whole column; Back restores the tab.
    if (S.stack.tab && !overlay()) hidePanels();
    renderStack();
    announce(plural(pts.length, 'tradition') + ' at this location. Choose one, or go back.');
    el.stack.hidden = false;
    el.list.hidden = true;
    syncSide();
    draw();
    var first =
      el.stack.querySelector('#stack-filter') || el.stack.querySelector('button[data-tid]');
    if (first) first.focus();
  }

  function closeStack(returnFocus) {
    if (!S.stack) return;
    var tab = S.stack.tab;
    S.stack = null;
    if (tab && !overlay() && !openTab()) {
      var panels = {
        territories: el.legendPanel,
        threads: el.threadsPanel,
        routes: el.routesPanel,
      };
      panels[tab].hidden = false;
      syncControls();
    }
    el.stack.hidden = true;
    el.stack.innerHTML = '';
    el.list.hidden = false;
    syncSide();
    draw();
    if (returnFocus) el.host.focus();
  }

  function stackPlaceLabel(pts) {
    var counts = {};
    for (var i = 0; i < pts.length; i++) counts[pts[i].place] = (counts[pts[i].place] || 0) + 1;
    var keys = Object.keys(counts);
    keys.sort(function (a, b) {
      return counts[b] - counts[a];
    });
    if (keys.length === 1) return keys[0];
    return keys[0] + ' and ' + (keys.length - 1) + ' nearby';
  }

  function stackMatches(q) {
    var st = S.stack;
    return q
      ? st.pts.filter(function (p) {
          return (
            p.name.toLowerCase().indexOf(q) >= 0 ||
            p.place.toLowerCase().indexOf(q) >= 0 ||
            rootLabel(p.root).toLowerCase().indexOf(q) >= 0
          );
        })
      : st.pts;
  }

  function renderStack() {
    var st = S.stack;
    if (!st) return;
    var head =
      '<div class="stack-head">' +
      '<button class="link-btn" type="button" data-act="close">' +
      ICON.back +
      (overlay() ? 'Back to the map' : 'Back to in view') +
      '</button>' +
      '<div class="stack-title" id="stack-title">' +
      ICON.pin +
      '<span>' +
      esc(stackPlaceLabel(st.pts)) +
      '</span></div>' +
      '<div class="stack-count">' +
      plural(st.pts.length, 'tradition') +
      ' at this location · choose one</div>';
    if (st.pts.length >= STACK_FILTER_MIN) {
      head +=
        '<label class="sr-only" for="stack-filter">Find a tradition here</label>' +
        '<input id="stack-filter" class="cm-input" type="text" autocomplete="off" placeholder="Find a tradition here…" value="' +
        esc(st.filter) +
        '" />';
    }
    head += '</div>';
    el.stack.innerHTML =
      head +
      '<div id="stack-list" role="list"></div><div id="stack-status" class="sr-only" role="status"></div>';
    renderStackList();
  }

  function renderStackList() {
    var st = S.stack;
    var q = st.filter.trim().toLowerCase();
    var shown = stackMatches(q);
    var body = '';
    if (!shown.length) {
      body =
        '<div class="list-empty">Nothing here matches &ldquo;' + esc(st.filter) + '&rdquo;.</div>';
    } else if (st.pts.length >= STACK_GROUP_MIN) {
      // A flat list of 100 is a wall. Grouping by taxonomy root turns London
      // into a handful of legible headings with the glyphs already on the map.
      groupCounts(shown).forEach(function (g) {
        body +=
          '<div class="group-head" role="presentation">' +
          mark(g[0], 12) +
          '<span class="group-name">' +
          esc(rootLabel(g[0])) +
          '</span><span class="group-n">' +
          g[1] +
          '</span></div>';
        body += shown
          .filter(function (p) {
            return p.root === g[0];
          })
          .sort(byName)
          .map(stackRow)
          .join('');
      });
    } else {
      body = shown.slice().sort(byName).map(stackRow).join('');
    }
    $('stack-list').innerHTML = body;
    $('stack-status').textContent = q
      ? plural(shown.length, 'match', 'matches') + ' of ' + st.pts.length
      : '';
  }

  function stackRow(p) {
    return (
      '<button class="rowbtn" type="button" role="listitem" data-tid="' +
      esc(p.id) +
      '">' +
      mark(p.root) +
      '<span class="rowtext"><span class="rowname">' +
      esc(p.name) +
      '</span><span class="rowplace">' +
      esc(p.place) +
      '</span></span>' +
      ICON.chevron +
      '</button>'
    );
  }

  function wireStack() {
    el.stack.addEventListener('click', function (e) {
      if (e.target.closest('[data-act="close"]')) {
        closeStack(true);
        return;
      }
      var row = e.target.closest('button[data-tid]');
      if (!row) return;
      var p = S.byId[row.dataset.tid];
      if (!p) return;
      closeStack();
      S.opener = null;
      select(p);
      flyTo(p);
    });
    el.stack.addEventListener('input', function (e) {
      if (e.target.id !== 'stack-filter') return;
      S.stack.filter = e.target.value;
      renderStackList();
    });
    // Roving focus so a long list is walkable without a mouse.
    el.stack.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') {
        e.stopPropagation();
        closeStack(true);
        return;
      }
      var rows = Array.prototype.slice.call(el.stack.querySelectorAll('button[data-tid]'));
      if (!rows.length) return;
      var i = rows.indexOf(document.activeElement);
      var next;
      if (e.key === 'ArrowDown') next = i < 0 ? 0 : (i + 1) % rows.length;
      else if (e.key === 'ArrowUp') next = i <= 0 ? rows.length - 1 : i - 1;
      else if (e.key === 'Home' && i >= 0) next = 0;
      else if (e.key === 'End' && i >= 0) next = rows.length - 1;
      else if (e.key === 'Enter' && e.target.id === 'stack-filter') next = 0;
      else return;
      e.preventDefault();
      rows[next].focus();
    });
  }

  // ── selection ──

  // Related results, with their basis: shared sound words when the catalog has
  // them for this tradition, otherwise a stated fallback (same classification
  // branch, nearest on the map). Neither is a claim of historical descent.
  function kinFor(p) {
    var sig = S.sigs[p.id];
    S.kinWhy = {};
    var ranked;
    if (sig) {
      var setOf = new Set(sig);
      ranked = Object.keys(S.sigs)
        .filter(function (id) {
          return id !== p.id && S.byId[id];
        })
        .map(function (id) {
          var other = S.sigs[id];
          var shared = [];
          for (var i = 0; i < other.length; i++) if (setOf.has(other[i])) shared.push(other[i]);
          return [id, shared.length / (setOf.size + other.length - shared.length), shared];
        })
        .filter(function (x) {
          return x[1] > 0.08;
        })
        .sort(function (a, b) {
          return b[1] - a[1];
        })
        .slice(0, 6)
        .map(function (x) {
          S.kinWhy[x[0]] = x[2];
          return x[0];
        });
    } else {
      var near = function (list) {
        return list
          .filter(function (q) {
            return q.id !== p.id;
          })
          .sort(function (a, b) {
            return Math.hypot(a.x - p.x, a.y - p.y) - Math.hypot(b.x - p.x, b.y - p.y);
          });
      };
      var sameNode = p.node
        ? near(
            S.pts.filter(function (q) {
              return q.node === p.node;
            })
          )
        : [];
      var sameRoot = near(
        S.pts.filter(function (q) {
          return q.root === p.root && (!p.node || q.node !== p.node);
        })
      );
      ranked = sameNode
        .concat(sameRoot)
        .slice(0, 6)
        .map(function (q) {
          return q.id;
        });
    }
    return ranked
      .map(function (id) {
        return S.byId[id];
      })
      .filter(Boolean);
  }

  function select(p) {
    if (!p) {
      S.sel = null;
      S.kin = [];
      S.recipeOpen = false;
      el.card.hidden = true;
      el.card.innerHTML = '';
      document.body.classList.remove('card-open');
      draw();
      syncList();
      syncFit();
      syncSide();
      return;
    }
    if (!S.sel || S.sel.id !== p.id) S.recipeOpen = false;
    S.kin = kinFor(p);
    S.sel = {
      id: p.id,
      name: p.name,
      place: p.place,
      root: p.root,
      branch: p.node ? branchNames(p.node) : ['Awaiting tree placement'],
      sigBasis: !!S.sigs[p.id],
      lineage: '',
      recipe: '',
      fetching: !S.cache[p.id],
      fetchError: false,
    };
    if (S.cache[p.id]) {
      S.sel.lineage = S.cache[p.id].lineage;
      S.sel.recipe = S.cache[p.id].recipe;
      S.sel.fetching = false;
    }
    renderCard();
    draw();
    syncList();
    syncFit();
    if (!S.cache[p.id]) fetchDetail(p.id);
  }

  function fetchDetail(id) {
    if (INLINE) {
      var d = INLINE.detail[id] || ['', ''];
      S.cache[id] = { lineage: d[0], recipe: d[1] };
      if (S.sel && S.sel.id === id) {
        S.sel.lineage = d[0];
        S.sel.recipe = d[1];
        S.sel.fetching = false;
        renderCard();
      }
      return;
    }
    // Relative, so a local checkout and a fork both read their own catalog.
    fetch('api/traditions/' + encodeURIComponent(id) + '.json')
      .then(function (r) {
        if (!r.ok) throw new Error(String(r.status));
        return r.json();
      })
      .then(function (d) {
        S.cache[id] = { lineage: d.lineage || '', recipe: d.recipe || '' };
      })
      .catch(function () {
        // Not cached: a transient failure should not poison the session, so
        // Retry (or the next click on this pin) tries again.
        if (S.sel && S.sel.id === id) {
          S.sel.fetchError = true;
          S.sel.fetching = false;
          renderCard();
        }
        throw null;
      })
      .then(function () {
        if (S.sel && S.sel.id === id && S.cache[id]) {
          S.sel.lineage = S.cache[id].lineage;
          S.sel.recipe = S.cache[id].recipe;
          S.sel.fetching = false;
          renderCard();
        }
      })
      .catch(function () {
        /* already surfaced above */
      });
  }

  function coordText(p) {
    var lat = Math.abs(p.lat).toFixed(2) + '°' + (p.lat >= 0 ? 'N' : 'S');
    var lng = Math.abs(p.lng).toFixed(2) + '°' + (p.lng >= 0 ? 'E' : 'W');
    return lat + ', ' + lng;
  }
  function coordStatus(id) {
    var has = function (v) {
      return Array.isArray(v) && v.indexOf(id) >= 0;
    };
    if (has(S.meta.verified)) return 'Human-verified.';
    if (has(S.meta.reviewed))
      return (
        'Model-reviewed' +
        (S.meta.reviewed_on ? ' on ' + esc(S.meta.reviewed_on) : '') +
        '; not yet verified by a person.'
      );
    if (typeof S.meta.reviewed === 'number')
      return (
        'This published copy carries review counts only: ' +
        S.meta.reviewed.toLocaleString('en') +
        ' model-reviewed, ' +
        metaCount(S.meta.verified).toLocaleString('en') +
        ' human-verified.'
      );
    return 'Drafted; neither model-reviewed nor human-verified.';
  }

  function addControl(s) {
    if (!EMBEDDED) {
      // On its own the atlas opens the app at this genre; that adds nothing.
      return (
        '<a class="cm-btn cm-btn-primary" href="' +
        CODEX_URL +
        '?trad=' +
        encodeURIComponent(s.id) +
        '">Open in Codex Musica</a>'
      );
    }
    var a = S.adds[s.id];
    if (a && a.state === 'adding')
      return '<button class="cm-btn cm-btn-primary" type="button" data-act="add" aria-disabled="true">Adding…</button>';
    return (
      '<button class="cm-btn cm-btn-primary" type="button" data-act="add">' +
      ICON.plus +
      (a && a.state === 'done'
        ? 'Add again'
        : a && a.state === 'failed'
          ? 'Retry adding'
          : 'Add genre') +
      '</button>'
    );
  }
  function addStatus(s) {
    var a = S.adds[s.id];
    if (!a || a.state === 'adding') return '';
    if (a.state === 'failed')
      return (
        '<div class="add-status" data-tone="danger">' +
        ICON.warn +
        '<span>Nothing was added to Your recipe. Retry, or add it from the Genre page.</span></div>'
      );
    var partial = a.expected && a.added < a.expected;
    return (
      '<div class="add-status" data-tone="' +
      (partial ? 'warning' : 'success') +
      '">' +
      (partial ? ICON.warn : ICON.check) +
      '<span>' +
      (a.expected
        ? 'Added ' + a.added + ' of ' + plural(a.expected, 'instrument') + ' to Your recipe'
        : 'Added ' + plural(a.added, 'instrument') + ' to Your recipe') +
      (a.times > 1 ? ' (' + a.times + ' times)' : '') +
      '. Undo is in the app.</span></div>'
    );
  }

  function renderCard() {
    var s = S.sel;
    if (!s) return;
    var p = S.byId[s.id];
    var img = imageFor(s.id);
    var h = '<div class="card-bar"><div class="card-tools"></div>';
    h +=
      '<button class="icon-btn" type="button" data-act="close-card" aria-label="Close tradition detail">' +
      ICON.close +
      '</button></div>';
    h +=
      '<nav class="crumbs" aria-label="Classification">' +
      mark(s.root, 12) +
      s.branch
        .map(function (n) {
          return '<span>' + esc(n) + '</span>';
        })
        .join('<span class="crumb-sep" aria-hidden="true">›</span>') +
      '</nav>';
    h += '<div class="card-hero">';
    if (img) {
      h +=
        '<figure class="card-figure"><img src="' +
        esc(img.src) +
        '" alt="" loading="lazy" data-fallback="' +
        esc(s.root) +
        '"><figcaption>' +
        (img.link
          ? '<a href="' +
            esc(img.link) +
            '" target="_blank" rel="noopener">' +
            esc(img.credit || 'Source') +
            '</a>'
          : esc(img.credit)) +
        (img.licence ? ' · ' + esc(img.licence) : '') +
        '</figcaption></figure>';
    } else {
      h += '<div class="card-glyph" aria-hidden="true">' + mark(s.root, 28) + '</div>';
    }
    h +=
      '<div class="card-id"><h2 id="card-title">' +
      esc(s.name) +
      '</h2><div class="card-place">' +
      esc(s.place) +
      ' · ' +
      esc(rootLabel(s.root)) +
      '</div></div></div>';
    h +=
      '<div class="card-actions"><a class="cm-btn cm-btn-outline" href="https://www.youtube.com/results?search_query=' +
      encodeURIComponent(s.name + ' music') +
      '" target="_blank" rel="noopener" title="Opens a YouTube search in a new tab">Listen ' +
      ICON.external +
      '</a>' +
      addControl(s) +
      '</div>';
    h += '<div class="add-live">' + addStatus(s) + '</div>';
    if (EMBEDDED)
      h +=
        '<button class="link-btn" type="button" data-act="genre-page">' +
        ICON.genre +
        'Open on the Genre page' +
        '</button>';

    if (s.lineage) h += '<p class="card-bg">' + esc(s.lineage) + '</p>';

    // The catalog's stock recipe for the tradition. The user's own recipe is
    // a different object: it lives in the app's Your recipe panel, and only
    // Add genre changes it; nothing in this section edits it.
    h +=
      '<section class="card-sec" aria-labelledby="sec-default"><div class="sec-head">' + ICON.doc;
    h += '<h3 id="sec-default">Default recipe</h3>';
    if (s.recipe)
      h +=
        '<button class="cm-btn cm-btn-outline sec-action" type="button" data-act="copy">' +
        ICON.copy +
        esc(S.copyLabel || 'Copy default') +
        '</button>';
    h +=
      '</div><div class="sec-note">The catalog’s stock recipe for this tradition — not Your recipe.</div>';
    if (s.recipe) {
      h +=
        '<div class="recipe' +
        (S.recipeOpen ? '' : ' clamped') +
        '" id="default-recipe">' +
        esc(s.recipe) +
        '</div><button class="link-btn" type="button" data-act="toggle-recipe" aria-controls="default-recipe" aria-expanded="' +
        S.recipeOpen +
        '">' +
        (S.recipeOpen ? 'Show less' : 'Show full default recipe') +
        '</button>';
    }
    if (s.fetching)
      h +=
        '<div class="card-wait" role="status"><span class="spinner"></span>Fetching the recipe…</div>';
    if (s.fetchError)
      h +=
        '<div class="add-status" data-tone="danger">' +
        ICON.warn +
        '<span>Could not reach the catalog for this recipe. Listen and Add still work.</span>' +
        '<button class="link-btn" type="button" data-act="retry-detail">Retry</button></div>';
    h += '</section>';

    if (S.kin.length) {
      h +=
        '<section class="card-sec" aria-labelledby="sec-kin"><div class="sec-head">' +
        ICON.wave +
        '<h3 id="sec-kin">' +
        (s.sigBasis ? 'Similar sounds' : 'Related') +
        '</h3><span class="sec-basis">' +
        (s.sigBasis ? 'Basis: shared sound words' : 'Basis: fallback') +
        '</span></div>';
      if (!s.sigBasis)
        h +=
          '<div class="sec-note">This tradition has no sound words on file, so these are the nearest ' +
          'traditions in the same classification branch — not a sound match and not a lineage.</div>';
      h += '<div class="kin-list">';
      h += S.kin
        .map(function (k) {
          var why = S.kinWhy[k.id];
          return (
            '<button class="rowbtn" type="button" data-tid="' +
            esc(k.id) +
            '">' +
            mark(k.root) +
            '<span class="rowtext"><span class="rowname">' +
            esc(k.name) +
            '</span><span class="rowplace">' +
            (why
              ? 'Shares ' +
                esc(why.slice(0, 3).join(', ')) +
                (why.length > 3 ? ' +' + (why.length - 3) : '')
              : esc(k.place) + ' · ' + esc(rootLabel(k.root))) +
            '</span></span>' +
            ICON.chevron +
            '</button>'
          );
        })
        .join('');
      h += '</div>';
      if (EMBEDDED)
        h +=
          '<button class="link-btn" type="button" data-act="genre-page">Explore similar sounds on the Genre page ' +
          ICON.chevron +
          '</button>';
      h += '</section>';
    }

    var inThreads = S.threadDefs.filter(function (t) {
      return t.stops.indexOf(s.id) >= 0;
    });
    var onRoutes = [];
    S.routes.forEach(function (r, i) {
      if (r.a.id === s.id || r.b.id === s.id) onRoutes.push(i);
    });
    if (inThreads.length || onRoutes.length) {
      h +=
        '<section class="card-sec" aria-labelledby="sec-coll"><div class="sec-head">' +
        ICON.layers +
        '<h3 id="sec-coll">Collections and routes</h3></div>';
      h += inThreads
        .map(function (t) {
          return (
            '<button class="rowbtn" type="button" data-open-thread="' +
            esc(t.id) +
            '"><span class="rowtext"><span class="rowname">' +
            esc(t.title) +
            '</span><span class="rowplace">Collection · ' +
            plural(t.stops.length, 'genre') +
            '</span></span>' +
            ICON.chevron +
            '</button>'
          );
        })
        .join('');
      h += onRoutes
        .map(function (i) {
          return (
            '<button class="rowbtn" type="button" data-open-route="' +
            i +
            '"><span class="rowtext"><span class="rowname">' +
            esc(S.routes[i].label) +
            '</span><span class="rowplace">Route · clears filters</span></span>' +
            ICON.chevron +
            '</button>'
          );
        })
        .join('');
      h += '</section>';
    }

    if (p) {
      h +=
        '<details class="cm-accordion card-sources"><summary>' +
        ICON.pin +
        'Location and sources</summary><dl>' +
        '<div><dt>Documented place</dt><dd>' +
        esc(p.place) +
        (p.region ? ' · ' + esc(p.region) : '') +
        '</dd></div>' +
        '<div><dt>Pin drawn at</dt><dd>' +
        coordText(p) +
        ' (spread up to 25 km when places are shared)</dd></div>' +
        '<div><dt>Coordinate</dt><dd>' +
        coordStatus(p.id) +
        '</dd></div>' +
        '<div><dt>Catalog id</dt><dd><code>' +
        esc(p.id) +
        '</code></dd></div></dl>' +
        (INLINE
          ? ''
          : '<a href="api/traditions/' +
            encodeURIComponent(p.id) +
            '.json" target="_blank" rel="noopener">This record as JSON</a>') +
        '</details>';
    }
    if (S.thread) {
      h +=
        '<button class="cm-btn cm-btn-outline card-back" type="button" data-act="back-thread">' +
        ICON.back +
        'Back to collection</button>';
    }
    el.card.innerHTML = h;
    el.card.setAttribute('aria-labelledby', 'card-title');
    el.card.hidden = false;
    document.body.classList.add('card-open');
    var im = el.card.querySelector('img[data-fallback]');
    if (im)
      im.addEventListener('error', function () {
        // A dead thumbnail falls back to the glyph, never a broken image.
        var fig = im.closest('figure');
        if (fig)
          fig.outerHTML =
            '<div class="card-glyph" aria-hidden="true">' + mark(s.root, 28) + '</div>';
      });
    if (overlay()) el.threadCard.hidden = true;
    syncSide();
  }

  function closeCard() {
    var opener = S.opener;
    select(null);
    renderThreadCard();
    S.opener = null;
    if (opener && opener.isConnected) opener.focus();
    else el.host.focus();
  }

  // ── In view ──

  var listTimer = null;
  function scheduleListSync() {
    clearTimeout(listTimer);
    listTimer = setTimeout(syncList, 180);
  }

  function inViewPts() {
    var vis = [];
    var all = visiblePts();
    for (var i = 0; i < all.length; i++) {
      var s = toScreen(all[i].x, all[i].y);
      if (s[0] >= 0 && s[1] >= 0 && s[0] <= S.w && s[1] <= S.h) vis.push(all[i]);
    }
    return vis;
  }

  function syncList() {
    if (!S.pts.length) return;
    var vis = inViewPts();
    var groups = {};
    vis.forEach(function (p) {
      var r = p.region;
      (groups[r] = groups[r] || []).push(p);
    });
    var names = Object.keys(groups).sort(function (a, b) {
      return groups[b].length - groups[a].length;
    });

    var html =
      '<div class="list-head"><h2 class="list-title">In view</h2><span class="list-n">' +
      plural(vis.length, 'tradition') +
      '</span></div>';
    if (!vis.length) {
      html +=
        '<p class="list-empty">Nothing in view' +
        (S.focus.size || S.qmatch ? ' with the filters in force' : '') +
        '. Zoom out, or clear filters.</p>';
    }
    names.forEach(function (name) {
      var rows = groups[name].slice().sort(byName);
      var open = S.expanded.has(name);
      var take = open ? rows : rows.slice(0, LIST_CAP);
      html += '<div class="list-group">';
      html +=
        '<div class="list-region"><span>' +
        esc(name) +
        '</span><span class="list-n">' +
        rows.length +
        '</span></div>';
      html += take
        .map(function (p) {
          return (
            '<button class="rowbtn" type="button" data-tid="' +
            esc(p.id) +
            '"' +
            (S.sel && S.sel.id === p.id ? ' aria-current="true"' : '') +
            '>' +
            mark(p.root) +
            '<span class="rowtext"><span class="rowname">' +
            esc(p.name) +
            '</span><span class="rowplace">' +
            esc(p.place) +
            '</span></span></button>'
          );
        })
        .join('');
      if (rows.length > LIST_CAP) {
        // Expanding in place always works; "zoom in" cannot split a shared
        // coordinate.
        html +=
          '<button class="link-btn" type="button" data-expand="' +
          esc(name) +
          '" aria-expanded="' +
          open +
          '">' +
          (open ? 'Show fewer' : 'Show all ' + rows.length + ' in ' + esc(name)) +
          '</button>';
      }
      html += '</div>';
    });
    el.list.innerHTML = html;

    var shown =
      vis.length === S.pts.length
        ? S.pts.length.toLocaleString('en')
        : vis.length.toLocaleString('en') + ' in view';
    el.count.textContent = shown + ' on map';
    renderKey(vis);
  }

  // The on-map key: the groups in view (most first) with the exact glyphs the
  // markers use, what a bubble means, and the way to every group.
  function renderKey(vis) {
    var groups = groupCounts(vis);
    var h =
      '<div class="key-head"><h2 class="key-title">Genre groups</h2>' +
      '<button class="link-btn" type="button" data-act="toggle-key" aria-expanded="' +
      !S.keyHidden +
      '" aria-controls="key-body">' +
      (S.keyHidden ? 'Show' : 'Hide') +
      '</button><div class="key-tools"></div></div><div id="key-body"' +
      (S.keyHidden ? ' hidden' : '') +
      '>';
    h += groups
      .slice(0, KEY_ROWS)
      .map(function (g) {
        var on = S.focus.has(g[0]);
        return (
          '<button class="key-row" type="button" data-key-root="' +
          esc(g[0]) +
          '" aria-pressed="' +
          on +
          '" title="Show only ' +
          esc(rootLabel(g[0])) +
          '">' +
          mark(g[0], 12) +
          '<span class="key-name">' +
          esc(rootLabel(g[0])) +
          '</span><span class="key-n">' +
          g[1] +
          '</span></button>'
        );
      })
      .join('');
    if (groups.length > KEY_ROWS)
      h += '<div class="key-more">+' + (groups.length - KEY_ROWS) + ' more groups in view</div>';
    h +=
      '<div class="key-bubble"><span class="key-bubble-disc" aria-hidden="true">12</span>' +
      '<span>Traditions documented there; the ring shows their groups. Not how much music there is.</span></div>';
    h +=
      '<button class="link-btn" type="button" data-act="all-groups">All ' +
      S.roots.length +
      ' groups ' +
      ICON.chevron +
      '</button></div>';
    el.key.innerHTML = h;
    el.key.classList.toggle('key-collapsed', !!S.keyHidden);
  }

  // ── search ──

  function onQuery() {
    var val = el.search.value;
    var ql = val.trim().toLowerCase();
    // Focusing an empty search must not erase the active collection filter.
    if (S.thread && !ql) {
      el.results.hidden = true;
      return;
    }
    if (S.thread) exitThread();
    var all = !ql
      ? []
      : S.pts.filter(function (p) {
          return (
            p.name.toLowerCase().indexOf(ql) >= 0 ||
            p.id.indexOf(ql.replace(/\s+/g, '_')) >= 0 ||
            p.place.toLowerCase().indexOf(ql) >= 0
          );
        });
    var ids = new Set(
      all.map(function (p) {
        return p.id;
      })
    );
    var tokenHit = null;
    if (ql.length >= 3) {
      var toks = Object.keys(S.tokenIdx).filter(function (t) {
        return t.indexOf(ql) >= 0;
      });
      if (toks.length) {
        var n = 0;
        toks.forEach(function (t) {
          S.tokenIdx[t].forEach(function (id) {
            if (!S.byId[id]) return;
            if (!ids.has(id)) n++;
            ids.add(id);
          });
        });
        tokenHit = { tokens: toks.slice(0, 3).join(', ') + (toks.length > 3 ? '…' : ''), count: n };
      }
    }
    S.qmatch = ql ? ids : null;

    var h = '';
    if (all.length)
      h +=
        '<div class="results-head">' +
        plural(all.length, 'name, place or id match', 'name, place or id matches') +
        (all.length > 12 ? ' · first 12 below, all lit on the map' : '') +
        '</div>';
    h += all
      .slice(0, 12)
      .map(function (p) {
        return (
          '<button class="rowbtn" type="button" data-tid="' +
          esc(p.id) +
          '">' +
          mark(p.root) +
          '<span class="rowtext"><span class="rowname">' +
          esc(p.name) +
          '</span><span class="rowplace">' +
          esc(p.place) +
          '</span></span></button>'
        );
      })
      .join('');
    if (tokenHit) {
      h +=
        '<div class="results-sound"><div class="label">Sound-word match</div>' +
        '<div class="results-tokens">' +
        esc(tokenHit.tokens) +
        '</div><div class="results-why">' +
        (tokenHit.count
          ? '+' +
            plural(tokenHit.count, 'more tradition') +
            ' lit on the map because a sound word in their recipe contains “' +
            esc(ql) +
            '” — matched by descriptor, not by name.'
          : 'These sound words belong to the traditions already listed.') +
        '</div></div>';
    }
    if (ql && !all.length && !tokenHit)
      h =
        '<div class="route-end" role="status">No matching genres or places for “' +
        esc(val.trim()) +
        '”. Try a place, a catalog id, or a sound word such as “drone”.</div>';
    el.results.innerHTML = h;
    el.results.hidden = !ql;
    syncControls();
    draw();
    scheduleListSync();
  }

  // ── legend (Genres), collections ──

  function renderLegend() {
    var h =
      '<div class="panel-heading"><h2 class="label">Genre groups</h2>' +
      '<button class="panel-action" type="button" data-act="clear-roots">Clear</button>' +
      '<button class="panel-action icon-btn" type="button" data-act="close-panel" aria-label="Close genre groups">' +
      ICON.close +
      '</button></div>' +
      '<div class="panel-note">The catalog’s ' +
      S.roots.length +
      ' taxonomy groups. Pick groups to show only them; each has its own colour and marker shape.</div>';
    h += S.roots
      .map(function (r) {
        var on = S.focus.has(r);
        return (
          '<button class="rowbtn group-row" type="button" data-root="' +
          esc(r) +
          '" aria-pressed="' +
          on +
          '">' +
          mark(r, 14) +
          '<span class="rowtext">' +
          esc(rootLabel(r)) +
          '</span><span class="row-n">' +
          S.rootCount[r] +
          '</span><span class="row-check" aria-hidden="true">' +
          (on ? ICON.check : '') +
          '</span></button>'
        );
      })
      .join('');
    el.legendPanel.innerHTML = h;
    syncControls();
  }

  function renderThreads() {
    el.threadsPanel.innerHTML =
      '<div class="panel-heading"><h2 class="label">Collections</h2>' +
      '<button class="panel-action icon-btn" type="button" data-act="close-panel" aria-label="Close collections">' +
      ICON.close +
      '</button></div>' +
      '<div class="panel-note">Genres grouped by theme. Choosing one replaces genre groups and search.</div>' +
      S.threadDefs
        .map(function (t) {
          return (
            '<button class="rowbtn" type="button" aria-pressed="' +
            (!!S.thread && S.thread.id === t.id) +
            '" data-thid="' +
            esc(t.id) +
            '"><span class="rowtext"><span class="rowname">' +
            esc(t.title) +
            '</span></span><span class="row-n">' +
            plural(t.stops.length, 'genre') +
            '</span></button>'
          );
        })
        .join('');
  }

  function pickThread(id) {
    var t = S.threadDefs.filter(function (x) {
      return x.id === id;
    })[0];
    if (!t) return;
    S.focus.clear();
    S.qmatch = new Set(t.stops);
    S.thread = t;
    closeStack();
    el.search.value = '';
    el.results.hidden = true;
    select(null);
    renderLegend();
    renderThreads();
    renderThreadCard();
    fitPoints(
      t.stops
        .map(function (sid) {
          return S.byId[sid];
        })
        .filter(Boolean)
    );
    syncFit();
  }

  function renderThreadCard() {
    var t = S.thread;
    if (!t) {
      el.threadCard.hidden = true;
      syncSide();
      return;
    }
    var h =
      '<div class="panel-heading"><div class="thread-kicker">' +
      ICON.layers +
      'Collection</div><button class="panel-action icon-btn" type="button" data-act="exit-thread" title="Clear collection" aria-label="Clear collection">' +
      ICON.close +
      '</button></div>' +
      '<h2 class="thread-title">' +
      esc(t.title) +
      '</h2><div class="panel-note">' +
      plural(t.stops.length, 'genre') +
      ', grouped by theme; the order is not a route.</div><div class="thread-stops">';
    h += t.stops
      .map(function (id) {
        var p = S.byId[id];
        if (!p) return '';
        return (
          '<button class="rowbtn" type="button" data-tid="' +
          esc(id) +
          '"' +
          (S.sel && S.sel.id === id ? ' aria-current="true"' : '') +
          '>' +
          mark(p.root) +
          '<span class="rowtext"><span class="rowname">' +
          esc(p.name) +
          '</span><span class="rowplace">' +
          esc(p.place) +
          '</span></span></button>'
        );
      })
      .join('');
    h += '</div>';
    el.threadCard.innerHTML = h;
    el.threadCard.hidden = !!S.sel && overlay();
    syncSide();
  }

  function exitThread() {
    S.thread = null;
    S.qmatch = null;
    el.threadCard.hidden = true;
    renderThreads();
    if (S.sel) renderCard();
    syncControls();
    draw();
    scheduleListSync();
  }

  // ── wiring ──

  // Each constraint in force is one chip with its own remove button, and the
  // chips are rebuilt from state on every change, so none can go stale.
  function syncControls() {
    [
      ['territories', el.legendPanel, S.focus.size > 0],
      ['threads', el.threadsPanel, !!S.thread],
      ['routes', el.routesPanel, S.routesOn],
    ].forEach(function (entry) {
      var btn = $('t-' + entry[0]);
      btn.setAttribute('aria-expanded', String(!entry[1].hidden));
      btn.dataset.active = String(entry[2]);
    });
    $('t-territories-badge').textContent = S.focus.size ? ' · ' + S.focus.size : '';
    var chips = [];
    var chip = function (text, kind, title) {
      return (
        '<span class="filter-chip" title="' +
        esc(title || text) +
        '">' +
        esc(text) +
        '<button type="button" data-clear="' +
        kind +
        '" aria-label="Remove filter: ' +
        esc(title || text) +
        '">' +
        ICON.close +
        '</button></span>'
      );
    };
    if (S.focus.size)
      chips.push(
        chip(
          S.focus.size + ' genre group' + (S.focus.size === 1 ? '' : 's'),
          'focus',
          Array.from(S.focus).map(rootLabel).join(', ')
        )
      );
    if (S.thread) chips.push(chip(S.thread.title, 'thread', 'Collection: ' + S.thread.title));
    if (el.search.value.trim()) chips.push(chip('Search: ' + el.search.value.trim(), 'search'));
    $('filter-summary').innerHTML = chips.join('');
    $('active-filters').hidden = chips.length === 0;
    $('no-filters').hidden = chips.length > 0;
    syncRouteChip();
    syncFit();
    syncSide();
  }

  function syncRouteChip() {
    var r = S.routesOn && S.routeIndex !== null ? S.routes[S.routeIndex] : null;
    el.routeChip.hidden = !r;
    if (!r) {
      el.routeChip.innerHTML = '';
      return;
    }
    el.routeChip.innerHTML =
      '<span class="route-dot" aria-hidden="true"></span><span>Route: ' +
      esc(r.label) +
      '</span><button type="button" data-act="clear-route" aria-label="Clear route ' +
      esc(r.label) +
      '">' +
      ICON.close +
      '</button>';
  }

  // Docked, the side column holds the open tab, a chosen collection and the
  // In view list (or the location chooser in its place). As sheets over a
  // narrow map, each of those opens only on request.
  function syncSide() {
    var tabOpen = !el.legendPanel.hidden || !el.threadsPanel.hidden || !el.routesPanel.hidden;
    var narrow = overlay();
    var lowerOpen = narrow ? S.listOpen || !!S.stack : true;
    $('side-lower').hidden = !lowerOpen;
    var inview = $('t-inview');
    inview.setAttribute('aria-expanded', String(narrow && lowerOpen));
    inview.dataset.active = String(!!S.stack);
    document.body.classList.toggle(
      'side-sheet',
      narrow && (tabOpen || lowerOpen || !el.threadCard.hidden)
    );
  }

  // Layout preferences (codex-layout:*, never session state). Reset layout —
  // in Map information or the app's More menu — restores their defaults.
  function pref(key, initial, onReset) {
    if (window.UILayout) return window.UILayout.remember(key, initial, onReset);
    var value = initial;
    return {
      get: function () {
        return value;
      },
      set: function (next) {
        value = next;
      },
    };
  }
  function setCollapsed(collapsed) {
    document.body.classList.toggle('side-collapsed', collapsed);
    var b = $('t-collapse');
    b.setAttribute('aria-expanded', String(!collapsed));
    b.setAttribute('aria-label', collapsed ? 'Expand map panels' : 'Collapse map panels');
    if (S.prefs && S.prefs.collapsed.get() !== collapsed) S.prefs.collapsed.set(collapsed);
  }

  function openTab() {
    if (!el.legendPanel.hidden) return 'territories';
    if (!el.routesPanel.hidden) return 'routes';
    if (!el.threadsPanel.hidden) return 'threads';
    return null;
  }
  function hidePanels() {
    el.legendPanel.hidden = el.routesPanel.hidden = el.threadsPanel.hidden = true;
    syncControls();
  }

  function setPanel(name, focus) {
    var panels = { territories: el.legendPanel, threads: el.threadsPanel, routes: el.routesPanel };
    var previous = Object.keys(panels).find(function (key) {
      return !panels[key].hidden;
    });
    Object.keys(panels).forEach(function (key) {
      panels[key].hidden = key !== name;
    });
    if (name) {
      if (S.stack) S.stack.tab = null;
      setCollapsed(false);
      if (overlay()) {
        S.listOpen = false;
        closeStack();
      }
    }
    syncControls();
    if (focus && previous) $('t-' + previous).focus();
  }

  function clearSearch() {
    el.search.value = '';
    el.results.hidden = true;
    if (!S.thread) S.qmatch = null;
  }

  function clearFilters() {
    S.focus.clear();
    S.thread = null;
    S.qmatch = null;
    el.search.value = '';
    el.results.hidden = true;
    el.threadCard.hidden = true;
    closeStack();
    renderLegend();
    renderThreads();
    if (S.sel) renderCard();
    draw();
    syncList();
    syncControls();
  }

  function renderRoutes() {
    var h =
      '<div class="panel-heading"><h2 class="label">Routes</h2>' +
      '<button class="panel-action" type="button" data-act="hide-routes">Hide routes</button>' +
      '<button class="panel-action icon-btn" type="button" data-act="close-panel" aria-label="Close routes">' +
      ICON.close +
      '</button></div>' +
      '<div class="panel-note">Each route joins two catalogued endpoints, numbered in the catalog’s order. ' +
      'The curve is not a path. Choosing a route clears genre groups, a collection and search.</div>';
    S.routes.forEach(function (route, i) {
      var selected = S.routeIndex === i;
      h +=
        '<button class="rowbtn route-row" type="button" data-route="' +
        i +
        '" aria-current="' +
        selected +
        '" aria-expanded="' +
        selected +
        '"><span class="route-caret" aria-hidden="true">' +
        ICON.chevron +
        '</span><span class="rowtext"><span class="rowname">' +
        esc(route.label) +
        '</span></span></button>';
      if (!selected) return;
      h += '<div class="route-ends">';
      [route.a, route.b].forEach(function (end, n) {
        var num =
          '<span class="route-num" aria-label="Endpoint ' + (n + 1) + '">' + (n + 1) + '</span>';
        h += end.id
          ? '<button class="rowbtn" type="button" data-tid="' +
            esc(end.id) +
            '">' +
            num +
            '<span class="rowtext"><span class="rowname">' +
            esc(end.name) +
            '</span><span class="rowplace">' +
            esc(end.place) +
            '</span></span></button>'
          : '<div class="route-end">' +
            num +
            '<span class="rowtext"><span class="rowname">' +
            esc(end.name) +
            '</span><span class="rowplace">A place, not a catalogued genre</span></span></div>';
      });
      h += '</div>';
    });
    el.routesPanel.innerHTML = h;
  }

  function pickRoute(index) {
    var route = S.routes[index];
    if (!route) return;
    clearFilters();
    select(null);
    S.routesOn = true;
    S.routeIndex = index;
    renderRoutes();
    syncControls();
    fitPoints([route.a, route.b]);
    draw();
  }

  function clearRoute() {
    S.routeIndex = null;
    renderRoutes();
    syncControls();
    draw();
  }

  function toggleRoot(r) {
    if (S.thread) exitThread();
    if (S.focus.has(r)) S.focus.delete(r);
    else S.focus.add(r);
    renderLegend();
    draw();
    scheduleListSync();
    syncControls();
  }

  function requestAdd() {
    var s = S.sel;
    if (!s || !EMBEDDED) return;
    var a = S.adds[s.id];
    if (a && a.state === 'adding') return;
    S.adds[s.id] = { state: 'adding', times: a ? a.times || 0 : 0 };
    renderCard();
    var btn = el.card.querySelector('[data-act="add"]');
    if (btn) btn.focus();
    parent.postMessage({ type: 'add-genre', id: s.id }, location.origin);
  }

  function wireControls() {
    wireStack();

    $('zoom-in').addEventListener('click', function () {
      var r = el.host.getBoundingClientRect();
      zoomAt(r.left + S.w / 2, r.top + S.h / 2, 1.7);
    });
    $('zoom-out').addEventListener('click', function () {
      var r = el.host.getBoundingClientRect();
      zoomAt(r.left + S.w / 2, r.top + S.h / 2, 1 / 1.7);
    });
    $('zoom-reset').addEventListener('click', resetView);
    $('zoom-fit').addEventListener('click', function () {
      var t = fitTarget();
      if (t) fitPoints(t.pts);
    });
    $('t-info').addEventListener('click', function () {
      setInfo(el.provenance.hidden);
    });
    el.provenance.addEventListener('click', function (e) {
      if (e.target.closest('[data-act="close-info"]')) {
        setInfo(false);
        $('t-info').focus();
      }
      if (e.target.closest('[data-act="reset-layout"]')) {
        if (window.UILayout) window.UILayout.reset();
        else {
          setCollapsed(false);
          S.keyHidden = false;
          renderKey(inViewPts());
        }
      }
    });
    $('t-collapse').addEventListener('click', function () {
      setCollapsed(!document.body.classList.contains('side-collapsed'));
    });
    S.prefs = {
      collapsed: pref('map-side-collapsed', false, function () {
        setCollapsed(false);
      }),
      keyHidden: pref('map-key-hidden', false, function () {
        S.keyHidden = false;
        renderKey(inViewPts());
      }),
    };
    S.keyHidden = !!S.prefs.keyHidden.get();
    if (S.prefs.collapsed.get()) setCollapsed(true);
    $('t-inview').addEventListener('click', function () {
      if (S.stack) {
        closeStack();
        S.listOpen = false;
      } else {
        S.listOpen = !S.listOpen;
        if (S.listOpen) setPanel(null);
      }
      syncSide();
    });

    [
      ['territories', el.legendPanel],
      ['threads', el.threadsPanel],
      ['routes', el.routesPanel],
    ].forEach(function (entry) {
      $('t-' + entry[0]).addEventListener('click', function () {
        var open = entry[1].hidden;
        if (entry[0] === 'routes' && open) S.routesOn = true;
        setPanel(open ? entry[0] : null);
        draw();
      });
      entry[1].addEventListener('click', function (e) {
        if (e.target.closest('[data-act="close-panel"]')) setPanel(null, true);
      });
    });
    $('clear-filters').addEventListener('click', function () {
      clearFilters();
      el.search.focus();
    });
    $('filter-summary').addEventListener('click', function (e) {
      var b = e.target.closest('[data-clear]');
      if (!b) return;
      var kind = b.dataset.clear;
      if (kind === 'focus') {
        S.focus.clear();
        renderLegend();
      } else if (kind === 'thread') exitThread();
      else if (kind === 'search') clearSearch();
      draw();
      syncList();
      syncControls();
      el.search.focus();
    });
    el.routeChip.addEventListener('click', function (e) {
      if (e.target.closest('[data-act="clear-route"]')) {
        clearRoute();
        el.host.focus();
      }
    });
    el.key.addEventListener('click', function (e) {
      var k = e.target.closest('[data-key-root]');
      if (k) {
        toggleRoot(k.dataset.keyRoot);
        var again = el.key.querySelector('[data-key-root="' + k.dataset.keyRoot + '"]');
        if (again) again.focus();
        return;
      }
      if (e.target.closest('[data-act="toggle-key"]')) {
        S.keyHidden = !S.keyHidden;
        S.prefs.keyHidden.set(S.keyHidden);
        renderKey(inViewPts());
        el.key.querySelector('[data-act="toggle-key"]').focus();
        return;
      }
      if (e.target.closest('[data-act="all-groups"]')) {
        setPanel('territories');
        var first = el.legendPanel.querySelector('[data-root]');
        if (first) first.focus();
      }
    });
    el.routesPanel.addEventListener('click', function (e) {
      if (e.target.closest('[data-act="hide-routes"]')) {
        S.routesOn = false;
        S.routeIndex = null;
        el.tip.hidden = true;
        renderRoutes();
        setPanel(null, true);
        draw();
        return;
      }
      var row = e.target.closest('[data-route]');
      if (!row) return;
      pickRoute(Number(row.dataset.route));
      // Rendering the selected endpoints replaces the row; preserve keyboard focus.
      el.routesPanel.querySelector('[data-route="' + row.dataset.route + '"]').focus();
    });

    el.legendPanel.addEventListener('click', function (e) {
      if (e.target.closest('[data-act="clear-roots"]')) {
        S.focus.clear();
        renderLegend();
        el.legendPanel.querySelector('[data-act="clear-roots"]').focus();
        draw();
        scheduleListSync();
        return;
      }
      var b = e.target.closest('[data-root]');
      if (!b) return;
      var r = b.dataset.root;
      toggleRoot(r);
      el.legendPanel.querySelector('[data-root="' + r + '"]').focus();
    });

    el.threadsPanel.addEventListener('click', function (e) {
      var b = e.target.closest('[data-thid]');
      if (!b) return;
      setPanel(null);
      pickThread(b.dataset.thid);
      el.threadCard.querySelector('[data-act="exit-thread"]').focus();
    });

    // One delegated handler for every "open this tradition" button on the page.
    [el.list, el.results, el.card, el.threadCard, el.routesPanel].forEach(function (root) {
      root.addEventListener('click', function (e) {
        if (e.target.closest('[data-act="close-card"]')) {
          closeCard();
          return;
        }
        if (e.target.closest('[data-act="exit-thread"]')) {
          exitThread();
          $('t-threads').focus();
          return;
        }
        if (e.target.closest('[data-act="back-thread"]')) {
          select(null);
          renderThreadCard();
          var first = el.threadCard.querySelector('[data-tid]');
          if (first) first.focus();
          return;
        }
        if (e.target.closest('[data-act="copy"]')) {
          copyRecipe();
          return;
        }
        if (e.target.closest('[data-act="add"]')) {
          requestAdd();
          return;
        }
        if (e.target.closest('[data-act="genre-page"]')) {
          if (S.sel && EMBEDDED)
            parent.postMessage({ type: 'genre-web', id: S.sel.id }, location.origin);
          return;
        }
        if (e.target.closest('[data-act="toggle-recipe"]')) {
          S.recipeOpen = !S.recipeOpen;
          renderCard();
          el.card.querySelector('[data-act="toggle-recipe"]').focus();
          return;
        }
        if (e.target.closest('[data-act="retry-detail"]')) {
          if (!S.sel) return;
          S.sel.fetchError = false;
          S.sel.fetching = true;
          renderCard();
          fetchDetail(S.sel.id);
          return;
        }
        var th = e.target.closest('[data-open-thread]');
        if (th) {
          pickThread(th.dataset.openThread);
          var exit = el.threadCard.querySelector('[data-act="exit-thread"]');
          if (exit) exit.focus();
          return;
        }
        var ro = e.target.closest('[data-open-route]');
        if (ro) {
          var ri = Number(ro.dataset.openRoute);
          pickRoute(ri);
          setPanel('routes');
          var rb = el.routesPanel.querySelector('[data-route="' + ri + '"]');
          if (rb) rb.focus();
          return;
        }
        var exp = e.target.closest('[data-expand]');
        if (exp) {
          var name = exp.dataset.expand;
          if (S.expanded.has(name)) S.expanded.delete(name);
          else S.expanded.add(name);
          syncList();
          var back = el.list.querySelector('[data-expand="' + name.replace(/"/g, '\\"') + '"]');
          if (back) back.focus();
          return;
        }
        var row = e.target.closest('[data-tid]');
        if (!row) return;
        var p = S.byId[row.dataset.tid];
        if (!p) return;
        if (!S.thread) S.qmatch = null;
        el.search.value = '';
        el.results.hidden = true;
        syncControls();
        S.opener = root === el.card || root === el.results ? null : row;
        select(p);
        if (root === el.routesPanel && overlay()) setPanel(null);
        if (root === el.list && overlay()) {
          S.listOpen = false;
          syncSide();
        }
        flyTo(p);
        if (root === el.card || root === el.results) {
          var title = el.card.querySelector('h2');
          if (title) {
            title.tabIndex = -1;
            title.focus();
          }
        }
      });
    });

    el.search.addEventListener('input', onQuery);
    el.search.addEventListener('focus', onQuery);
    el.search.addEventListener('keydown', function (e) {
      if (e.key !== 'ArrowDown' || el.results.hidden) return;
      var first = el.results.querySelector('[data-tid]');
      if (first) {
        e.preventDefault();
        first.focus();
      }
    });
    el.results.addEventListener('keydown', function (e) {
      if (e.key !== 'ArrowDown' && e.key !== 'ArrowUp') return;
      var rows = Array.prototype.slice.call(el.results.querySelectorAll('[data-tid]'));
      var i = rows.indexOf(document.activeElement);
      if (i < 0) return;
      e.preventDefault();
      if (e.key === 'ArrowUp' && i === 0) el.search.focus();
      else
        rows[Math.max(0, Math.min(rows.length - 1, i + (e.key === 'ArrowDown' ? 1 : -1)))].focus();
    });

    document.addEventListener('pointerdown', function (e) {
      // Sheets over a narrow map close on an outside tap. Dismiss before a
      // canvas tap opens a route, and before a menu row is replaced: testing
      // click.target afterwards mistakes a replaced row for an outside click.
      if (overlay() && !e.target.closest('#side')) setPanel(null);
      if (!el.provenance.hidden && !e.target.closest('#provenance') && !e.target.closest('#t-info'))
        setInfo(false);
    });

    document.addEventListener('click', function (e) {
      if (!el.results.hidden && !e.target.closest('.searchwrap')) el.results.hidden = true;
    });

    document.addEventListener('keydown', function (e) {
      if (e.key !== 'Escape') return;
      if (!el.provenance.hidden) {
        setInfo(false);
        $('t-info').focus();
        return;
      }
      if (S.stack) {
        closeStack(true);
        return;
      }
      if (!el.results.hidden) {
        el.results.hidden = true;
        el.search.focus();
        return;
      }
      var tabOpen = !el.legendPanel.hidden || !el.threadsPanel.hidden || !el.routesPanel.hidden;
      if (overlay() && tabOpen) {
        setPanel(null, true);
        return;
      }
      if (overlay() && S.listOpen) {
        S.listOpen = false;
        syncSide();
        $('t-inview').focus();
        return;
      }
      if (S.sel) {
        closeCard();
      } else if (S.thread) {
        exitThread();
        $('t-threads').focus();
      }
    });

    // The app answers an Add with how much of the ensemble arrived.
    window.addEventListener('message', function (e) {
      if (e.origin !== location.origin || e.source !== parent || !e.data) return;
      if (e.data.type !== 'genre-added' || typeof e.data.id !== 'string') return;
      var prev = S.adds[e.data.id] || {};
      S.adds[e.data.id] = e.data.ok
        ? {
            state: 'done',
            added: e.data.added,
            expected: e.data.expected,
            times: (prev.times || 0) + 1,
          }
        : { state: 'failed', times: prev.times || 0 };
      var name = S.byId[e.data.id] ? S.byId[e.data.id].name : e.data.id;
      announce(
        e.data.ok
          ? 'Added ' +
              e.data.added +
              (e.data.expected ? ' of ' + e.data.expected : '') +
              ' instruments from ' +
              name +
              ' to Your recipe.'
          : 'Nothing was added from ' + name + '.'
      );
      if (S.sel && S.sel.id === e.data.id) {
        var focused = document.activeElement && document.activeElement.dataset.act === 'add';
        renderCard();
        if (focused) el.card.querySelector('[data-act="add"]').focus();
      }
    });

    if (window.matchMedia) {
      var mq = window.matchMedia('(max-width: 899px)');
      var onBreak = function () {
        if (!overlay() && el.legendPanel.hidden && el.routesPanel.hidden && el.threadsPanel.hidden)
          setPanel('territories');
        if (S.stack) renderStack();
        renderThreadCard();
        syncSide();
      };
      if (mq.addEventListener) mq.addEventListener('change', onBreak);
    }
  }

  function copyRecipe() {
    var s = S.sel;
    if (!s) return;
    var text = s.recipe || s.name + ' — ' + s.place;
    var done = function (label) {
      S.copyLabel = label;
      renderCard();
      var b = el.card.querySelector('[data-act="copy"]');
      if (b) b.focus();
      setTimeout(function () {
        S.copyLabel = null;
        if (S.sel) renderCard();
      }, 1600);
    };
    if (!navigator.clipboard) {
      done('Copy failed');
      return;
    }
    navigator.clipboard.writeText(text).then(
      function () {
        done('Copied');
      },
      function () {
        done('Copy failed');
      }
    );
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
  else boot();
})();
