// atlas.js — the Traditions Atlas: 2503 traditions on an Equal Earth map,
// coloured by the catalog's own taxonomy roots rather than by geography.
//
// Loaded by atlas.html as a plain script (no build step — unlike codex.html,
// which is assembled by scripts/build_html.js because it inlines the catalog).
//
// TWO THINGS HERE ARE NOT IN THE ORIGINAL DESIGN, and they exist because the
// design could not be clicked:
//
//   1. Display coordinates come from data/atlas-geo.json, generated by
//      scripts/build_atlas_geo.js, which spreads co-located pins over a small
//      land-aware disc. data/geo.json puts 2503 traditions on 835 coordinates,
//      so a stack projected to one screen point at every zoom.
//   2. openStack() — the cluster popover. A bubble that cannot be zoomed apart
//      lists its members instead of zooming into a dead end. This is the floor
//      that makes every pin reachable no matter how deep the stack: the spread
//      handles 94.6% of pins, the popover handles London's 103.
//
// See the header of scripts/build_atlas_geo.js for the measurements.

'use strict';

(function () {
  // ── configuration ──

  // Colours keyed to the catalog's own taxonomy roots (references/04_tree.js).
  // Sonic territories, not geography. 'unplaced' = no extras.parent yet.
  var ROOT_COLORS = {
    droneModal: '#6d4fc4',
    functionalSong: '#4a7dbb',
    improvOnFrame: '#c08a1f',
    distortedRock: '#cf4f45',
    mcRhythm: '#e07b39',
    groovePercussion: '#3f9084',
    artMusic: '#5560b5',
    balladPoetry: '#7d9440',
    ritualDevotional: '#b0568c',
    bassSystem: '#2f855a',
    electronicDance: '#3d8fd1',
    experimentalElec: '#2b8a99',
    lullaby: '#c78aa8',
    wedding: '#d9a021',
    funeralLament: '#6e7b8b',
    seaShanty: '#33698c',
    fieldWork: '#71862f',
    domesticRhythm: '#937b66',
    huntingSong: '#55705a',
    nurseryRhyme: '#d98a6a',
    drinkingSong: '#a9713a',
    carnivalProcessional: '#cc5f9e',
    praiseSong: '#8a6d3b',
    protestSong: '#b3402e',
    spokenWord: '#5f6368',
    unplaced: '#9aa0a6',
  };

  var CELL = 58; // cluster bin, px
  var CLUSTER_MIN = 4; // a cell with this many pins draws as a bubble
  // Raised from the prototype's 60. With the spread in data/atlas-geo.json,
  // x150 takes individually-clickable pins from 62% to 95%; past that the
  // basemap outline is too coarse to be worth the extra depth, and the popover
  // covers what is left.
  var MAX_ZOOM_FACTOR = 150;
  var MIN_ZOOM_FACTOR = 0.8;
  var PICK_SLOP = 3; // px added to a hit radius
  var STACK_GROUP_THRESHOLD = 12; // popover groups by branch above this many

  // A published Artifact runs under a CSP that blocks fetch, so the standalone
  // build (scripts/build_atlas_standalone.js) ships every sidecar inlined on
  // window.__ATLAS_DATA__ and this file reads from there instead. Same code
  // either way — the artifact is not a separate implementation that can drift.
  var INLINE =
    typeof window !== 'undefined' && window.__ATLAS_DATA__ ? window.__ATLAS_DATA__ : null;
  var CODEX_URL = (INLINE && INLINE.codexUrl) || 'codex.html';

  // ── state ──

  var S = {
    pts: [],
    byId: {},
    nodes: {},
    sigs: {},
    tokenIdx: {},
    roots: [],
    threadDefs: [],
    routes: [],
    land: null,
    meta: { verified: [] },
    cache: {},
    view: { cx: 0.35, cy: 0.25, scale: 0 },
    baseScale: 0,
    focus: new Set(),
    qmatch: null,
    hit: [],
    clusters: [],
    sel: null,
    kin: [],
    thread: null,
    stack: null, // { pts, anchorX, anchorY, filter }
    expanded: new Set(),
    heat: false,
    routesOn: false,
    w: 0,
    h: 0,
    dpr: 1,
  };

  var el = {};
  function $(id) {
    return document.getElementById(id);
  }

  // ── small helpers ──

  // Human-facing sorts name their locale: bare localeCompare() collates by the
  // runtime's locale and is banned repo-wide (see eslint.config.js).
  function byName(a, b) {
    return a.name.localeCompare(b.name, 'en');
  }
  function esc(s) {
    return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }
  function rootColor(r) {
    return ROOT_COLORS[r] || ROOT_COLORS.unplaced;
  }
  function rootLabel(r) {
    if (r === 'unplaced') return 'Awaiting tree placement';
    return S.nodes[r] ? S.nodes[r].n : r;
  }
  function branchOf(node) {
    var names = [];
    var cur = node;
    while (cur && S.nodes[cur]) {
      names.unshift(S.nodes[cur].n);
      cur = S.nodes[cur].p;
    }
    return names.join(' › ');
  }

  // Equal Earth projection.
  function proj(lat, lng) {
    var A1 = 1.340264,
      A2 = -0.081106,
      A3 = 0.000893,
      A4 = 0.003796,
      M = Math.sqrt(3) / 2;
    var la = (lat * Math.PI) / 180,
      lo = (lng * Math.PI) / 180;
    var t = Math.asin(M * Math.sin(la)),
      t2 = t * t,
      t6 = t2 * t2 * t2;
    return [
      (lo * Math.cos(t)) / (M * (A1 + 3 * A2 * t2 + t6 * (7 * A3 + 9 * A4 * t2))),
      t * (A1 + A2 * t2 + t6 * (A3 + A4 * t2)),
    ];
  }

  function toScreen(x, y) {
    var v = S.view;
    return [(x - v.cx) * v.scale + S.w / 2, S.h / 2 - (y - v.cy) * v.scale];
  }
  function fromEvent(e) {
    var r = el.host.getBoundingClientRect();
    return [e.clientX - r.left, e.clientY - r.top];
  }

  // ── boot ──

  function boot() {
    el.host = $('canvas-host');
    el.list = $('list');
    el.search = $('search');
    el.results = $('results');
    el.count = $('count');
    el.card = $('card');
    el.threadCard = $('thread-card');
    el.stack = $('stack');
    el.tip = $('tip');
    el.provenance = $('provenance');
    el.legendPanel = $('legend-panel');
    el.threadsPanel = $('threads-panel');

    var get = function (u) {
      return fetch(u).then(function (r) {
        if (!r.ok) throw new Error(u + ' ' + r.status);
        return r.json();
      });
    };

    var sources = INLINE
      ? Promise.resolve([
          INLINE.index,
          INLINE.geo,
          INLINE.sigs,
          INLINE.world,
          INLINE.treeMap,
          INLINE.nodes,
          INLINE.routes,
          INLINE.threads,
          INLINE.meta,
        ])
      : Promise.all([
          get('api/traditions/index.json'),
          get('data/atlas-geo.json'),
          get('references/_tradition_signatures.json'),
          get('data/countries.geo.json'),
          get('data/tree-map.json'),
          get('data/tree-nodes.json'),
          get('data/routes.json'),
          get('data/threads.json'),
          get('data/geo-meta.json'),
        ]);

    sources
      .then(function (r) {
        ingest(r[0], r[1].coords, r[2], r[3], r[4], r[5], r[6], r[7], r[8]);
        setupCanvas();
        wireControls();
        $('loading').textContent = S.pts.length + ' traditions loaded.';
        renderProvenance();
        syncList();
        renderLegend();
        renderThreads();
        var deep = new URLSearchParams(location.search).get('trad');
        if (deep && S.byId[deep]) {
          select(S.byId[deep]);
          flyTo(S.byId[deep]);
        }
      })
      .catch(function (err) {
        el.count.textContent = 'load error';
        $('loading').textContent = 'The catalog did not load: ' + err.message;
        el.list.innerHTML =
          '<p style="padding:12px 10px;color:var(--muted-2);font-size:13px">' +
          'The catalog did not load. Every recipe is still available at ' +
          '<a href="api/all.json">api/all.json</a>.</p>';
      });
  }

  function ingest(idx, geo, sigs, world, treeMap, nodes, routes, threads, meta) {
    S.sigs = sigs;
    S.nodes = nodes;
    S.meta = meta;
    S.threadDefs = threads.threads;

    Object.keys(sigs).forEach(function (id) {
      sigs[id].forEach(function (t) {
        var k = t.toLowerCase();
        (S.tokenIdx[k] = S.tokenIdx[k] || []).push(id);
      });
    });

    S.roots = Object.keys(nodes).filter(function (k) {
      return nodes[k].p === null;
    });
    S.roots.push('unplaced');

    S.pts = idx.items
      .filter(function (t) {
        return geo[t.id];
      })
      .map(function (t) {
        var g = geo[t.id];
        var p = proj(g[0], g[1]);
        var node = treeMap[t.id] || null;
        var root = node ? node.split('.')[0] : 'unplaced';
        return {
          id: t.id,
          name: t.name.replace(/&amp;/g, '&'),
          node: node,
          root: root,
          lat: g[0],
          lng: g[1],
          place: g[2],
          // Sidebar bucket, from the table in scripts/_atlas_regions.js. The
          // prototype derived this from coordinates and put Algiers in Europe.
          region: g[3],
          x: p[0],
          y: p[1],
          color: rootColor(root),
        };
      });
    S.pts.forEach(function (p) {
      S.byId[p.id] = p;
    });

    S.land = new Path2D();
    var addRing = function (ring) {
      ring.forEach(function (c, i) {
        var p = proj(c[1], c[0]);
        if (i === 0) S.land.moveTo(p[0], p[1]);
        else S.land.lineTo(p[0], p[1]);
      });
      S.land.closePath();
    };
    world.features.forEach(function (f) {
      if (!f.geometry) return;
      if (f.geometry.type === 'Polygon') f.geometry.coordinates.forEach(addRing);
      else if (f.geometry.type === 'MultiPolygon')
        f.geometry.coordinates.forEach(function (poly) {
          poly.forEach(addRing);
        });
    });

    S.routes = routes.routes
      .map(function (r) {
        var end = function (e) {
          if (typeof e === 'string') return S.byId[e];
          var pr = proj(e[0], e[1]);
          return { x: pr[0], y: pr[1] };
        };
        var a = end(r.a),
          b = end(r.b);
        return a && b ? { ax: a.x, ay: a.y, bx: b.x, by: b.y, label: r.label } : null;
      })
      .filter(Boolean);
  }

  function renderProvenance() {
    // Two counts, never added together. A model re-derived every coordinate
    // blind and a person has checked none of them, and those are different
    // claims — collapsing them into one "verified" number is the overclaim
    // this line exists to avoid. See the note in data/geo-meta.json.
    var reviewed = (S.meta.reviewed || []).length;
    var verified = (S.meta.verified || []).length;
    el.provenance.textContent =
      'Bubbles count documented scenes, not musical abundance · ' +
      S.pts.length.toLocaleString('en') +
      ' pins drafted · ' +
      reviewed.toLocaleString('en') +
      ' model-reviewed · ' +
      verified.toLocaleString('en') +
      ' human-verified — corrections welcome';
  }

  // ── canvas ──

  function setupCanvas() {
    var cv = document.createElement('canvas');
    cv.style.cssText = 'position:absolute;inset:0;width:100%;height:100%;display:block;';
    cv.setAttribute('aria-hidden', 'true');
    el.host.appendChild(cv);
    S.cv = cv;

    var resize = function () {
      var r = el.host.getBoundingClientRect();
      var dpr = window.devicePixelRatio || 1;
      S.w = r.width;
      S.h = r.height;
      cv.width = r.width * dpr;
      cv.height = r.height * dpr;
      S.dpr = dpr;
      if (!S.view.scale) {
        S.baseScale = Math.min(S.w / 5.6, S.h / 2.75);
        S.view.scale = S.baseScale;
      }
      draw();
      positionStack();
    };
    new ResizeObserver(resize).observe(el.host);
    resize();

    var drag = null,
      pinch = null,
      moved = false;
    el.host.addEventListener('pointerdown', function (e) {
      el.host.setPointerCapture(e.pointerId);
      if (pinch) return;
      drag = { x: e.clientX, y: e.clientY, cx: S.view.cx, cy: S.view.cy, id: e.pointerId };
      moved = false;
      el.host.style.cursor = 'grabbing';
    });
    el.host.addEventListener('pointermove', function (e) {
      if (drag && e.pointerId === drag.id) {
        var dx = e.clientX - drag.x,
          dy = e.clientY - drag.y;
        if (Math.abs(dx) + Math.abs(dy) > 3) moved = true;
        S.view.cx = drag.cx - dx / S.view.scale;
        S.view.cy = drag.cy + dy / S.view.scale;
        if (moved) closeStack();
        draw();
        scheduleListSync();
      } else {
        hover(e);
      }
    });
    el.host.addEventListener('pointerup', function (e) {
      if (drag && e.pointerId === drag.id) {
        el.host.style.cursor = 'grab';
        if (!moved) onMapClick(e);
        drag = null;
      }
    });
    el.host.addEventListener('pointercancel', function () {
      drag = null;
      el.host.style.cursor = 'grab';
    });
    el.host.addEventListener(
      'wheel',
      function (e) {
        e.preventDefault();
        closeStack();
        zoomAt(e.clientX, e.clientY, Math.exp(-e.deltaY * 0.0015));
      },
      { passive: false }
    );
    el.host.addEventListener(
      'touchmove',
      function (e) {
        if (e.touches.length === 2) {
          e.preventDefault();
          var a = e.touches[0],
            b = e.touches[1];
          var d = Math.hypot(a.clientX - b.clientX, a.clientY - b.clientY);
          if (pinch) zoomAt((a.clientX + b.clientX) / 2, (a.clientY + b.clientY) / 2, d / pinch);
          pinch = d;
          drag = null;
        }
      },
      { passive: false }
    );
    el.host.addEventListener(
      'touchend',
      function (e) {
        if (e.touches.length < 2) pinch = null;
      },
      { passive: true }
    );
  }

  function maxScale() {
    return S.baseScale * MAX_ZOOM_FACTOR;
  }

  function zoomAt(clientX, clientY, k) {
    var v = S.view;
    var r = el.host.getBoundingClientRect();
    var sx = clientX - r.left,
      sy = clientY - r.top;
    var px = v.cx + (sx - S.w / 2) / v.scale,
      py = v.cy - (sy - S.h / 2) / v.scale;
    v.scale = Math.max(S.baseScale * MIN_ZOOM_FACTOR, Math.min(maxScale(), v.scale * k));
    v.cx = px - (sx - S.w / 2) / v.scale;
    v.cy = py + (sy - S.h / 2) / v.scale;
    draw();
    scheduleListSync();
  }

  function flyTo(pt, targetScale) {
    var v = S.view;
    var from = { cx: v.cx, cy: v.cy, s: v.scale };
    var to = {
      cx: pt.x,
      cy: pt.y,
      s: targetScale || Math.max(v.scale, S.baseScale * 10),
    };
    var t0 = performance.now(),
      D = 550;
    var step = function () {
      var t = Math.min(1, (performance.now() - t0) / D);
      var e = 1 - Math.pow(1 - t, 3);
      v.cx = from.cx + (to.cx - from.cx) * e;
      v.cy = from.cy + (to.cy - from.cy) * e;
      v.scale = from.s + (to.s - from.s) * e;
      draw();
      if (t < 1) requestAnimationFrame(step);
      else scheduleListSync();
    };
    step();
  }

  // ── clustering ──

  function visiblePts() {
    var hasFocus = S.focus.size > 0,
      hasQ = !!S.qmatch;
    if (!hasFocus && !hasQ) return S.pts;
    return S.pts.filter(function (p) {
      return (!hasFocus || S.focus.has(p.root)) && (!hasQ || S.qmatch.has(p.id));
    });
  }

  function bubbleRadius(n) {
    return Math.max(11, Math.min(26, 7 + Math.sqrt(n) * 2.1));
  }

  function buildClusters() {
    var map = new Map();
    var vis = visiblePts();
    for (var i = 0; i < vis.length; i++) {
      var p = vis[i];
      var s = toScreen(p.x, p.y);
      if (s[0] < -40 || s[1] < -40 || s[0] > S.w + 40 || s[1] > S.h + 40) continue;
      var key = Math.floor(s[0] / CELL) + ':' + Math.floor(s[1] / CELL);
      var c = map.get(key);
      if (!c) {
        c = { sx: 0, sy: 0, pts: [] };
        map.set(key, c);
      }
      c.sx += s[0];
      c.sy += s[1];
      c.pts.push(p);
    }
    var cls = [];
    map.forEach(function (c) {
      cls.push({ sx: c.sx / c.pts.length, sy: c.sy / c.pts.length, pts: c.pts });
    });
    var merged = true;
    while (merged) {
      merged = false;
      outer: for (var a = 0; a < cls.length; a++) {
        if (cls[a].pts.length < CLUSTER_MIN) continue;
        for (var b = a + 1; b < cls.length; b++) {
          if (cls[b].pts.length < CLUSTER_MIN) continue;
          var A = cls[a],
            B = cls[b];
          if (
            Math.hypot(A.sx - B.sx, A.sy - B.sy) <
            (bubbleRadius(A.pts.length) + bubbleRadius(B.pts.length)) * 0.62
          ) {
            var n = A.pts.length + B.pts.length;
            A.sx = (A.sx * A.pts.length + B.sx * B.pts.length) / n;
            A.sy = (A.sy * A.pts.length + B.sy * B.pts.length) / n;
            A.pts = A.pts.concat(B.pts);
            cls.splice(b, 1);
            merged = true;
            break outer;
          }
        }
      }
    }
    return cls;
  }

  // Would zooming in actually break this bubble apart? Project its members at
  // the scale the click would land on; if they still share one bin, zooming is
  // theatre and the popover is the honest response. Cheap: bails at the second
  // distinct cell.
  function canSplit(cluster) {
    var v = S.view;
    var target = Math.min(maxScale(), v.scale * 2.6);
    if (target <= v.scale * 1.001) return false; // already at max zoom
    var cx = v.cx + (cluster.sx - S.w / 2) / v.scale;
    var cy = v.cy - (cluster.sy - S.h / 2) / v.scale;
    var seen = null;
    for (var i = 0; i < cluster.pts.length; i++) {
      var p = cluster.pts[i];
      var sx = (p.x - cx) * target + S.w / 2;
      var sy = S.h / 2 - (p.y - cy) * target;
      var key = Math.floor(sx / CELL) + ':' + Math.floor(sy / CELL);
      if (seen === null) seen = key;
      else if (key !== seen) return true;
    }
    return false;
  }

  // ── drawing ──

  function draw() {
    if (!S.cv || !S.land) return;
    var ctx = S.cv.getContext('2d');
    var v = S.view;
    ctx.setTransform(S.dpr, 0, 0, S.dpr, 0, 0);
    ctx.clearRect(0, 0, S.w, S.h);
    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, S.w, S.h);

    ctx.save();
    ctx.translate(S.w / 2, S.h / 2);
    ctx.scale(v.scale, -v.scale);
    ctx.translate(-v.cx, -v.cy);
    // land only — no national borders; traditions don't respect them
    ctx.fillStyle = '#f1f3f4';
    ctx.fill(S.land);
    ctx.strokeStyle = '#f1f3f4';
    ctx.lineWidth = 1.2 / v.scale;
    ctx.stroke(S.land);
    ctx.restore();

    if (S.routesOn) drawRoutes(ctx);

    var cls = buildClusters();
    S.clusters = cls;
    if (S.heat) drawHeat(ctx, cls);

    S.hit = [];
    drawDimmed(ctx);

    var stackIds = S.stack
      ? new Set(
          S.stack.pts.map(function (p) {
            return p.id;
          })
        )
      : null;

    for (var i = 0; i < cls.length; i++) {
      var c = cls[i];
      if (c.pts.length >= CLUSTER_MIN) {
        drawBubble(ctx, c, stackIds);
      } else {
        drawDots(ctx, c, stackIds);
      }
    }

    if (S.routesOn) {
      for (var r = 0; r < S.routes.length; r++) {
        var rt = S.routes[r];
        if (rt._mx !== undefined) S.hit.push({ sx: rt._mx, sy: rt._my, r: 12, route: rt.label });
      }
    }

    drawThread(ctx);
    drawSelection(ctx);
  }

  function drawRoutes(ctx) {
    ctx.save();
    ctx.setLineDash([5, 4]);
    ctx.strokeStyle = 'rgba(200,80,74,0.55)';
    ctx.lineWidth = 1.3;
    for (var i = 0; i < S.routes.length; i++) {
      var r = S.routes[i];
      var a = toScreen(r.ax, r.ay),
        b = toScreen(r.bx, r.by);
      if (Math.max(a[0], b[0]) < -60 || Math.min(a[0], b[0]) > S.w + 60) continue;
      var mx = (a[0] + b[0]) / 2;
      var my = (a[1] + b[1]) / 2 - Math.min(110, Math.hypot(b[0] - a[0], b[1] - a[1]) * 0.22) - 10;
      ctx.beginPath();
      ctx.moveTo(a[0], a[1]);
      ctx.quadraticCurveTo(mx, my, b[0], b[1]);
      ctx.stroke();
      r._mx = (a[0] + 2 * mx + b[0]) / 4;
      r._my = (a[1] + 2 * my + b[1]) / 4;
    }
    ctx.restore();
  }

  function drawHeat(ctx, cls) {
    ctx.save();
    ctx.globalCompositeOperation = 'multiply';
    for (var i = 0; i < cls.length; i++) {
      var c = cls[i];
      var r = 20 + Math.sqrt(c.pts.length) * 9;
      var g = ctx.createRadialGradient(c.sx, c.sy, 0, c.sx, c.sy, r);
      g.addColorStop(0, 'rgba(200,80,74,0.14)');
      g.addColorStop(1, 'rgba(200,80,74,0)');
      ctx.fillStyle = g;
      ctx.beginPath();
      ctx.arc(c.sx, c.sy, r, 0, 7);
      ctx.fill();
    }
    ctx.restore();
  }

  function drawDimmed(ctx) {
    if (S.focus.size === 0 && !S.qmatch) return;
    var lit = new Set(
      visiblePts().map(function (p) {
        return p.id;
      })
    );
    ctx.fillStyle = 'rgba(189,193,198,0.7)';
    for (var i = 0; i < S.pts.length; i++) {
      var p = S.pts[i];
      if (lit.has(p.id)) continue;
      var s = toScreen(p.x, p.y);
      if (s[0] < -10 || s[1] < -10 || s[0] > S.w + 10 || s[1] > S.h + 10) continue;
      ctx.beginPath();
      ctx.arc(s[0], s[1], 2, 0, 7);
      ctx.fill();
      // Dimmed pins are hit-testable but sort last: a lit pin under the cursor
      // always wins (see pickAll).
      S.hit.push({ sx: s[0], sy: s[1], r: 6, pt: p, dim: true });
    }
  }

  function drawBubble(ctx, c, stackIds) {
    var r = bubbleRadius(c.pts.length);
    var counts = {};
    for (var i = 0; i < c.pts.length; i++) {
      counts[c.pts[i].root] = (counts[c.pts[i].root] || 0) + 1;
    }
    var top = Object.keys(counts).sort(function (a, b) {
      return counts[b] - counts[a];
    })[0];
    var open = stackIds && c.pts.length && stackIds.has(c.pts[0].id);
    ctx.beginPath();
    ctx.arc(c.sx, c.sy, r, 0, 7);
    ctx.fillStyle = rootColor(top) + 'cc';
    ctx.fill();
    ctx.strokeStyle = open ? '#c8504a' : '#ffffff';
    ctx.lineWidth = open ? 2.5 : 1.5;
    ctx.stroke();
    ctx.fillStyle = '#ffffff';
    ctx.font = '600 ' + (c.pts.length > 999 ? 10 : 11) + 'px IBM Plex Sans, sans-serif';
    ctx.textAlign = 'center';
    ctx.textBaseline = 'middle';
    ctx.fillText(String(c.pts.length), c.sx, c.sy + 0.5);
    S.hit.push({ sx: c.sx, sy: c.sy, r: r, cluster: c });
  }

  function drawDots(ctx, c, stackIds) {
    var labelZoom = S.view.scale > S.baseScale * 12;
    for (var i = 0; i < c.pts.length; i++) {
      var p = c.pts[i];
      var s = toScreen(p.x, p.y);
      var r = 3.5;
      if (stackIds && stackIds.has(p.id)) {
        ctx.beginPath();
        ctx.arc(s[0], s[1], r + 3.5, 0, 7);
        ctx.strokeStyle = '#c8504a';
        ctx.lineWidth = 1.6;
        ctx.stroke();
      }
      ctx.beginPath();
      ctx.arc(s[0], s[1], r, 0, 7);
      ctx.fillStyle = p.color;
      ctx.fill();
      ctx.strokeStyle = '#ffffff';
      ctx.lineWidth = 1;
      ctx.stroke();
      if (labelZoom) {
        ctx.font = '11px IBM Plex Sans, sans-serif';
        ctx.textAlign = 'left';
        ctx.textBaseline = 'middle';
        ctx.lineWidth = 3;
        ctx.strokeStyle = 'rgba(255,255,255,0.85)';
        ctx.strokeText(p.name, s[0] + r + 5, s[1]);
        ctx.fillStyle = '#202124';
        ctx.fillText(p.name, s[0] + r + 5, s[1]);
      }
      S.hit.push({ sx: s[0], sy: s[1], r: r + 4, pt: p });
    }
  }

  function drawThread(ctx) {
    var th = S.thread;
    if (!th) return;
    var stops = th.stops
      .map(function (id) {
        return S.byId[id];
      })
      .filter(Boolean);
    ctx.save();
    ctx.strokeStyle = '#c8504a';
    ctx.lineWidth = 1.8;
    for (var i = 0; i + 1 < stops.length; i++) {
      var a = toScreen(stops[i].x, stops[i].y),
        b = toScreen(stops[i + 1].x, stops[i + 1].y);
      var mx = (a[0] + b[0]) / 2;
      var my = (a[1] + b[1]) / 2 - Math.min(110, Math.hypot(b[0] - a[0], b[1] - a[1]) * 0.22) - 10;
      ctx.beginPath();
      ctx.moveTo(a[0], a[1]);
      ctx.quadraticCurveTo(mx, my, b[0], b[1]);
      ctx.stroke();
    }
    stops.forEach(function (p, i) {
      var s = toScreen(p.x, p.y);
      ctx.beginPath();
      ctx.arc(s[0], s[1], 9, 0, 7);
      ctx.fillStyle = '#c8504a';
      ctx.fill();
      ctx.strokeStyle = '#ffffff';
      ctx.lineWidth = 1.5;
      ctx.stroke();
      ctx.fillStyle = '#ffffff';
      ctx.font = '600 10px IBM Plex Sans, sans-serif';
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.fillText(String(i + 1), s[0], s[1] + 0.5);
      S.hit.push({ sx: s[0], sy: s[1], r: 11, pt: p });
    });
    ctx.restore();
  }

  function drawSelection(ctx) {
    if (!S.sel) return;
    var p = S.byId[S.sel.id];
    if (!p) return;
    var s = toScreen(p.x, p.y);
    for (var i = 0; i < S.kin.length; i++) {
      var kp = S.byId[S.kin[i].id];
      if (!kp) continue;
      var k = toScreen(kp.x, kp.y);
      var mx = (s[0] + k[0]) / 2;
      var my = (s[1] + k[1]) / 2 - Math.min(120, Math.hypot(k[0] - s[0], k[1] - s[1]) * 0.25) - 12;
      ctx.beginPath();
      ctx.moveTo(s[0], s[1]);
      ctx.quadraticCurveTo(mx, my, k[0], k[1]);
      ctx.strokeStyle = kp.color + '99';
      ctx.lineWidth = 1.4;
      ctx.stroke();
      ctx.beginPath();
      ctx.arc(k[0], k[1], 4.5, 0, 7);
      ctx.fillStyle = kp.color;
      ctx.fill();
      ctx.strokeStyle = '#ffffff';
      ctx.lineWidth = 1;
      ctx.stroke();
    }
    ctx.beginPath();
    ctx.arc(s[0], s[1], 7.5, 0, 7);
    ctx.strokeStyle = '#c8504a';
    ctx.lineWidth = 2.5;
    ctx.stroke();
    ctx.beginPath();
    ctx.arc(s[0], s[1], 4, 0, 7);
    ctx.fillStyle = p.color;
    ctx.fill();
  }

  // ── hit testing ──

  // Returns EVERY hit under the cursor, nearest first. The prototype returned
  // only the nearest, so of two dots at the same pixel the second was
  // unreachable — 311 pins were shadowed that way. Callers decide what a tie
  // means; onMapClick turns it into a popover.
  function pickAll(e) {
    var m = fromEvent(e);
    var hits = [];
    for (var i = 0; i < S.hit.length; i++) {
      var h = S.hit[i];
      var d = Math.hypot(h.sx - m[0], h.sy - m[1]);
      if (d < h.r + PICK_SLOP) hits.push({ h: h, d: d });
    }
    hits.sort(function (a, b) {
      // lit before dimmed, then by distance
      var ad = a.h.dim ? 1 : 0,
        bd = b.h.dim ? 1 : 0;
      if (ad !== bd) return ad - bd;
      return a.d - b.d;
    });
    return hits;
  }

  function hover(e) {
    var hits = pickAll(e);
    var top = hits.length ? hits[0].h : null;
    el.host.style.cursor = top ? 'pointer' : 'grab';
    if (top && (top.pt || top.route)) {
      var m = fromEvent(e);
      var coincident = hits.filter(function (x) {
        return x.h.pt;
      }).length;
      var text = top.pt ? top.pt.name : top.route;
      if (top.pt && coincident > 1) text += '  +' + (coincident - 1) + ' here';
      el.tip.textContent = text;
      el.tip.style.left = m[0] + 'px';
      el.tip.style.top = m[1] + 'px';
      el.tip.hidden = false;
    } else if (top && top.cluster) {
      var m2 = fromEvent(e);
      el.tip.textContent =
        top.cluster.pts.length + ' traditions' + (canSplit(top.cluster) ? '' : ' — click to list');
      el.tip.style.left = m2[0] + 'px';
      el.tip.style.top = m2[1] + 'px';
      el.tip.hidden = false;
    } else {
      el.tip.hidden = true;
    }
  }

  function onMapClick(e) {
    var hits = pickAll(e);
    if (!hits.length) {
      closeStack();
      if (S.sel) select(null);
      return;
    }
    var top = hits[0].h;

    if (top.cluster) {
      if (canSplit(top.cluster)) {
        closeStack();
        var v = S.view;
        var px = v.cx + (top.sx - S.w / 2) / v.scale;
        var py = v.cy - (top.sy - S.h / 2) / v.scale;
        flyTo({ x: px, y: py }, Math.min(maxScale(), v.scale * 2.6));
      } else {
        openStack(top.cluster.pts, top.sx, top.sy);
      }
      return;
    }

    if (top.route) return;

    // Dots sharing a pixel: list them rather than silently picking one.
    var pts = [];
    var seen = {};
    for (var i = 0; i < hits.length; i++) {
      var h = hits[i].h;
      if (h.pt && !seen[h.pt.id]) {
        seen[h.pt.id] = 1;
        pts.push(h.pt);
      }
    }
    if (pts.length > 1) {
      openStack(pts, top.sx, top.sy);
      return;
    }
    closeStack();
    select(top.pt);
  }

  // ── the cluster popover ──
  //
  // Opened when a bubble cannot be zoomed apart, or when dots share a pixel.
  // Every member is listed and focusable, so no pin is ever unreachable and the
  // map gets a keyboard route into stacked data that the canvas cannot give.

  function openStack(pts, anchorX, anchorY) {
    S.stack = { pts: pts.slice(), anchorX: anchorX, anchorY: anchorY, filter: '' };
    renderStack();
    positionStack();
    el.stack.hidden = false;
    draw();
    var first =
      el.stack.querySelector('#stack-filter') || el.stack.querySelector('button[data-tid]');
    if (first) first.focus();
  }

  function closeStack() {
    if (!S.stack) return;
    S.stack = null;
    el.stack.hidden = true;
    el.stack.innerHTML = '';
    draw();
  }

  function stackPlaceLabel(pts) {
    var counts = {};
    for (var i = 0; i < pts.length; i++) counts[pts[i].place] = (counts[pts[i].place] || 0) + 1;
    var keys = Object.keys(counts);
    keys.sort(function (a, b) {
      return counts[b] - counts[a];
    });
    if (keys.length === 1) return keys[0];
    return keys[0] + ' and ' + (keys.length - 1) + ' nearby';
  }

  function renderStack() {
    var st = S.stack;
    if (!st) return;
    var q = st.filter.trim().toLowerCase();
    var shown = q
      ? st.pts.filter(function (p) {
          return (
            p.name.toLowerCase().indexOf(q) >= 0 ||
            p.place.toLowerCase().indexOf(q) >= 0 ||
            rootLabel(p.root).toLowerCase().indexOf(q) >= 0
          );
        })
      : st.pts;

    var head =
      '<header>' +
      '<button class="closebtn" data-act="close" title="Close" aria-label="Close">&#215;</button>' +
      '<div class="stack-count" id="stack-title">' +
      st.pts.length +
      ' traditions</div>' +
      '<div class="stack-place">' +
      esc(stackPlaceLabel(st.pts)) +
      '</div>';
    if (st.pts.length > STACK_GROUP_THRESHOLD) {
      head +=
        '<label class="sr-only" for="stack-filter">Filter these traditions</label>' +
        '<input id="stack-filter" type="text" autocomplete="off" placeholder="Filter these ' +
        st.pts.length +
        '" value="' +
        esc(st.filter) +
        '" />';
    }
    head += '</header>';

    var body = '';
    if (!shown.length) {
      body = '<div class="empty">Nothing matches &ldquo;' + esc(st.filter) + '&rdquo;.</div>';
    } else if (st.pts.length > STACK_GROUP_THRESHOLD) {
      // A flat list of 103 is a wall. Grouping by taxonomy root turns London
      // into 11 legible headings and reuses the colours already on the map.
      var groups = {};
      shown.forEach(function (p) {
        (groups[p.root] = groups[p.root] || []).push(p);
      });
      var roots = Object.keys(groups).sort(function (a, b) {
        return groups[b].length - groups[a].length;
      });
      roots.forEach(function (r) {
        body +=
          '<div class="group-head"><span class="group-name" style="color:' +
          rootColor(r) +
          '">' +
          esc(rootLabel(r)) +
          '</span><span class="group-n">' +
          groups[r].length +
          '</span></div>';
        body += groups[r].sort(byName).map(stackRow).join('');
      });
    } else {
      body = shown.slice().sort(byName).map(stackRow).join('');
    }

    el.stack.innerHTML = head + '<div id="stack-list">' + body + '</div>';
  }

  function stackRow(p) {
    return (
      '<button class="rowbtn" data-tid="' +
      esc(p.id) +
      '"><span class="dot" style="background:' +
      p.color +
      '"></span><span class="rowtext"><span class="rowname">' +
      esc(p.name) +
      '</span><span class="rowplace">' +
      esc(p.place) +
      '</span></span></button>'
    );
  }

  function positionStack() {
    var st = S.stack;
    if (!st) return;
    var pad = 10;
    el.stack.hidden = false;
    var box = el.stack.getBoundingClientRect();
    var w = box.width || 320;
    var h = box.height || 320;
    var left = st.anchorX + 18;
    if (left + w > S.w - pad) left = st.anchorX - w - 18;
    if (left < pad) left = pad;
    var top = st.anchorY - h / 2;
    if (top + h > S.h - pad) top = S.h - h - pad;
    if (top < pad) top = pad;
    el.stack.style.left = Math.round(left) + 'px';
    el.stack.style.top = Math.round(top) + 'px';
  }

  function wireStack() {
    el.stack.addEventListener('click', function (e) {
      var close = e.target.closest('[data-act="close"]');
      if (close) {
        closeStack();
        return;
      }
      var row = e.target.closest('button[data-tid]');
      if (!row) return;
      var p = S.byId[row.dataset.tid];
      if (!p) return;
      closeStack();
      select(p);
      flyTo(p);
    });
    el.stack.addEventListener('input', function (e) {
      if (e.target.id !== 'stack-filter') return;
      S.stack.filter = e.target.value;
      var pos = e.target.selectionStart;
      renderStack();
      var again = el.stack.querySelector('#stack-filter');
      if (again) {
        again.focus();
        again.setSelectionRange(pos, pos);
      }
    });
    // Roving focus so a 103-item list is walkable without a mouse.
    el.stack.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') {
        e.stopPropagation();
        closeStack();
        el.host.focus();
        return;
      }
      if (e.key !== 'ArrowDown' && e.key !== 'ArrowUp') return;
      var rows = Array.prototype.slice.call(el.stack.querySelectorAll('button[data-tid]'));
      if (!rows.length) return;
      e.preventDefault();
      var i = rows.indexOf(document.activeElement);
      var next = e.key === 'ArrowDown' ? i + 1 : i - 1;
      if (i < 0) next = e.key === 'ArrowDown' ? 0 : rows.length - 1;
      if (next < 0) next = rows.length - 1;
      if (next >= rows.length) next = 0;
      rows[next].focus();
    });
  }

  // ── selection ──

  function kinFor(p) {
    var sig = S.sigs[p.id];
    var ranked;
    if (sig) {
      var setOf = new Set(sig);
      ranked = Object.keys(S.sigs)
        .filter(function (id) {
          return id !== p.id;
        })
        .map(function (id) {
          var other = S.sigs[id];
          var inter = 0;
          for (var i = 0; i < other.length; i++) if (setOf.has(other[i])) inter++;
          return [id, inter / (setOf.size + other.length - inter)];
        })
        .filter(function (x) {
          return x[1] > 0.08;
        })
        .sort(function (a, b) {
          return b[1] - a[1];
        })
        .slice(0, 6)
        .map(function (x) {
          return x[0];
        });
    } else {
      var near = function (list) {
        return list
          .filter(function (q) {
            return q.id !== p.id;
          })
          .sort(function (a, b) {
            return Math.hypot(a.x - p.x, a.y - p.y) - Math.hypot(b.x - p.x, b.y - p.y);
          });
      };
      var sameNode = p.node
        ? near(
            S.pts.filter(function (q) {
              return q.node === p.node;
            })
          )
        : [];
      var sameRoot = near(
        S.pts.filter(function (q) {
          return q.root === p.root && (!p.node || q.node !== p.node);
        })
      );
      ranked = sameNode
        .concat(sameRoot)
        .slice(0, 6)
        .map(function (q) {
          return q.id;
        });
    }
    return ranked
      .map(function (id) {
        return S.byId[id];
      })
      .filter(Boolean);
  }

  function select(p) {
    if (!p) {
      S.sel = null;
      S.kin = [];
      el.card.hidden = true;
      el.card.innerHTML = '';
      draw();
      syncList();
      return;
    }
    S.kin = kinFor(p);
    S.sel = {
      id: p.id,
      name: p.name,
      place: p.place,
      color: p.color,
      branch: p.node ? branchOf(p.node) : 'Awaiting tree placement',
      kinBasis: S.sigs[p.id] ? 'shared sound-words' : 'same branch, nearest',
      lineage: '',
      recipe: '',
      fetching: !S.cache[p.id],
      fetchError: false,
    };
    if (S.cache[p.id]) {
      S.sel.lineage = S.cache[p.id].lineage;
      S.sel.recipe = S.cache[p.id].recipe;
      S.sel.fetchError = !!S.cache[p.id].fetchError;
      S.sel.fetching = false;
    }
    renderCard();
    draw();
    syncList();
    if (!S.cache[p.id]) fetchDetail(p.id);
  }

  function fetchDetail(id) {
    if (INLINE) {
      var d = INLINE.detail[id] || ['', ''];
      S.cache[id] = { lineage: d[0], recipe: d[1] };
      if (S.sel && S.sel.id === id) {
        S.sel.lineage = d[0];
        S.sel.recipe = d[1];
        S.sel.fetching = false;
        renderCard();
      }
      return;
    }
    // Relative, so a local checkout and a fork both read their own catalog.
    fetch('api/traditions/' + encodeURIComponent(id) + '.json')
      .then(function (r) {
        if (!r.ok) throw new Error(String(r.status));
        return r.json();
      })
      .then(function (d) {
        S.cache[id] = { lineage: d.lineage || '', recipe: d.recipe || '' };
      })
      .catch(function () {
        // Not cached: a transient failure should not poison the session, so the
        // next click on this pin tries again.
        if (S.sel && S.sel.id === id) {
          S.sel.fetchError = true;
          S.sel.fetching = false;
          renderCard();
        }
        throw null;
      })
      .then(function () {
        if (S.sel && S.sel.id === id && S.cache[id]) {
          S.sel.lineage = S.cache[id].lineage;
          S.sel.recipe = S.cache[id].recipe;
          S.sel.fetching = false;
          renderCard();
        }
      })
      .catch(function () {
        /* already surfaced above */
      });
  }

  function renderCard() {
    var s = S.sel;
    if (!s) return;
    var h = '';
    h +=
      '<button class="closebtn" data-act="close-card" title="Close" aria-label="Close">&#215;</button>';
    h +=
      '<div style="display:flex;align-items:flex-start;gap:6px;margin-bottom:4px;padding-right:20px">' +
      '<span class="dot" style="background:' +
      s.color +
      ';margin-top:4px"></span>' +
      '<span style="font-size:11px;font-weight:600;color:' +
      s.color +
      ';line-height:1.4">' +
      esc(s.branch) +
      '</span></div>';
    h += '<h2 style="margin-bottom:2px;padding-right:20px">' + esc(s.name) + '</h2>';
    h +=
      '<div style="display:flex;align-items:baseline;justify-content:space-between;gap:8px;margin-bottom:10px">' +
      '<span style="font-size:13px;color:var(--muted)">' +
      esc(s.place) +
      '</span>' +
      '<a href="https://www.youtube.com/results?search_query=' +
      encodeURIComponent(s.name + ' music') +
      '" target="_blank" rel="noopener" style="font-size:12px;white-space:nowrap">Listen &#8599;</a></div>';
    if (s.lineage) {
      h +=
        '<p style="font-size:13px;color:var(--muted);line-height:1.5;margin-bottom:12px;text-wrap:pretty">' +
        esc(s.lineage) +
        '</p>';
    }
    if (s.recipe) {
      h += '<div class="label" style="margin-bottom:4px">Recipe</div>';
      h += '<div class="recipe" style="margin-bottom:12px">' + esc(s.recipe) + '</div>';
    }
    if (s.fetching) {
      h +=
        '<div style="display:flex;align-items:center;gap:8px;color:var(--muted-2);font-size:12px;margin-bottom:12px">' +
        '<span style="width:12px;height:12px;border:2px solid var(--border);border-top-color:var(--color-blue);' +
        'border-radius:50%;animation:atlas-spin 0.8s linear infinite"></span>Fetching the recipe…</div>';
    }
    if (s.fetchError) {
      h +=
        '<div style="font-size:12px;color:var(--muted-2);font-style:italic;margin-bottom:12px">' +
        'Could not reach the catalog for the recipe — the buttons below still work.</div>';
    }
    if (S.kin.length) {
      h +=
        '<div class="label" style="margin-bottom:6px">Kin <span style="font-weight:400;text-transform:none;' +
        'letter-spacing:0">· ' +
        esc(s.kinBasis) +
        '</span></div><div style="display:flex;flex-wrap:wrap;gap:4px;margin-bottom:14px">';
      h += S.kin
        .map(function (k) {
          return (
            '<button class="chip" data-tid="' +
            esc(k.id) +
            '"><span class="dot" style="width:7px;height:7px;background:' +
            k.color +
            '"></span>' +
            esc(k.name) +
            '</button>'
          );
        })
        .join('');
      h += '</div>';
    }
    h +=
      '<div style="display:flex;gap:8px"><a class="btn-primary" href="' +
      CODEX_URL +
      '?trad=' +
      encodeURIComponent(s.id) +
      '">Open in Codex &#8599;</a>' +
      '<button class="btn-secondary" data-act="copy">' +
      esc(S.copyLabel || 'Copy recipe') +
      '</button></div>';
    if (S.thread) {
      h +=
        '<button data-act="back-thread" style="width:100%;margin-top:8px;padding:7px 12px;font-size:12px;' +
        'color:var(--muted);background:var(--surface-sunken);border:none;border-radius:6px">' +
        '&#8592; Back to thread</button>';
    }
    el.card.innerHTML = h;
    el.card.hidden = false;
    el.threadCard.hidden = true;
  }

  // ── sidebar ──

  var listTimer = null;
  function scheduleListSync() {
    clearTimeout(listTimer);
    listTimer = setTimeout(syncList, 180);
  }

  function syncList() {
    if (!S.pts.length) return;
    var vis = [];
    var all = visiblePts();
    for (var i = 0; i < all.length; i++) {
      var s = toScreen(all[i].x, all[i].y);
      if (s[0] >= 0 && s[1] >= 0 && s[0] <= S.w && s[1] <= S.h) vis.push(all[i]);
    }
    var groups = {};
    vis.forEach(function (p) {
      var r = p.region;
      (groups[r] = groups[r] || []).push(p);
    });
    var names = Object.keys(groups).sort(function (a, b) {
      return groups[b].length - groups[a].length;
    });

    var CAP = 14;
    var html = '<div class="eyebrow">In view</div>';
    if (!vis.length) {
      html +=
        '<p style="color:var(--muted-2);font-size:13px;font-style:italic;padding:12px 10px">' +
        'Nothing in view — zoom out or clear filters.</p>';
    }
    names.forEach(function (name) {
      var rows = groups[name].slice().sort(byName);
      var open = S.expanded.has(name);
      var take = open ? rows : rows.slice(0, CAP);
      html += '<div style="margin-bottom:6px">';
      html +=
        '<div style="display:flex;align-items:baseline;justify-content:space-between;gap:8px;padding:6px 10px 2px">' +
        '<span style="font-family:var(--font-display);font-size:15px;font-weight:600">' +
        esc(name) +
        '</span><span style="font-family:var(--font-mono);font-size:12px;color:var(--muted-2)">' +
        rows.length +
        '</span></div>';
      html += take
        .map(function (p) {
          return (
            '<button class="rowbtn" data-tid="' +
            esc(p.id) +
            '"' +
            (S.sel && S.sel.id === p.id ? ' aria-current="true"' : '') +
            '><span class="dot" style="background:' +
            p.color +
            '"></span><span class="rowtext"><span class="rowname">' +
            esc(p.name) +
            '</span><span class="rowplace">' +
            esc(p.place) +
            '</span></span></button>'
          );
        })
        .join('');
      if (rows.length > CAP) {
        // The prototype said "zoom in", which for a stacked coordinate was
        // advice the map could not honour. Expanding in place always can.
        html +=
          '<button data-expand="' +
          esc(name) +
          '" style="font-size:12px;color:var(--color-blue);padding:4px 10px 6px;background:none;border:none">' +
          (open ? 'show fewer' : '+ ' + (rows.length - CAP) + ' more in view') +
          '</button>';
      }
      html += '</div>';
    });
    el.list.innerHTML = html;

    var shown =
      vis.length === S.pts.length
        ? S.pts.length.toLocaleString('en')
        : vis.length.toLocaleString('en') + ' in view';
    el.count.textContent = shown + ' on map';
  }

  // ── search ──

  function onQuery() {
    var val = el.search.value;
    var ql = val.trim().toLowerCase();
    var all = !ql
      ? []
      : S.pts.filter(function (p) {
          return (
            p.name.toLowerCase().indexOf(ql) >= 0 ||
            p.id.indexOf(ql.replace(/\s+/g, '_')) >= 0 ||
            p.place.toLowerCase().indexOf(ql) >= 0
          );
        });
    var ids = new Set(
      all.map(function (p) {
        return p.id;
      })
    );
    var tokenHit = null;
    if (ql.length >= 3) {
      var toks = Object.keys(S.tokenIdx).filter(function (t) {
        return t.indexOf(ql) >= 0;
      });
      if (toks.length) {
        var n = 0;
        toks.forEach(function (t) {
          S.tokenIdx[t].forEach(function (id) {
            if (!ids.has(id)) n++;
            ids.add(id);
          });
        });
        tokenHit = { tokens: toks.slice(0, 3).join(', ') + (toks.length > 3 ? '…' : ''), count: n };
      }
    }
    S.qmatch = ql ? ids : null;

    var h = '';
    if (tokenHit) {
      h +=
        '<div style="padding:8px 10px;border-bottom:1px solid var(--border);margin-bottom:4px">' +
        '<div class="label" style="color:var(--accent)">Sound-word match</div>' +
        '<div style="font-family:var(--font-mono);font-size:12px;color:var(--muted);margin-top:2px">' +
        esc(tokenHit.tokens) +
        '</div><div style="font-size:12px;color:var(--muted-2);margin-top:2px">+' +
        tokenHit.count +
        ' traditions lit on the map by descriptor</div></div>';
    }
    h += all
      .slice(0, 12)
      .map(function (p) {
        return (
          '<button class="rowbtn" data-tid="' +
          esc(p.id) +
          '"><span class="dot" style="background:' +
          p.color +
          '"></span><span class="rowtext"><span class="rowname">' +
          esc(p.name) +
          '</span><span class="rowplace">' +
          esc(p.place) +
          '</span></span></button>'
        );
      })
      .join('');
    el.results.innerHTML = h;
    el.results.hidden = !ql || (!all.length && !tokenHit);
    el.results.style.cssText =
      'position:absolute;top:calc(100% + 6px);right:0;width:320px;max-height:380px;overflow-y:auto;z-index:60';
    draw();
    scheduleListSync();
  }

  // ── legend, threads ──

  function renderLegend() {
    var counts = {};
    S.pts.forEach(function (p) {
      counts[p.root] = (counts[p.root] || 0) + 1;
    });
    var h =
      '<div style="display:flex;align-items:center;justify-content:space-between;gap:8px;padding:4px 8px 6px">' +
      '<span class="label">Highlight territories</span>' +
      '<button data-act="clear-roots" style="border:none;background:none;font-size:11px;color:var(--color-blue);padding:2px 4px">clear</button></div>';
    h += S.roots
      .filter(function (r) {
        return counts[r];
      })
      .map(function (r) {
        var on = S.focus.has(r);
        return (
          '<button class="rowbtn" style="min-height:30px;font-size:12px;font-weight:' +
          (on ? 600 : 400) +
          ';background:' +
          (on ? 'var(--color-blue-soft)' : 'transparent') +
          '" data-root="' +
          esc(r) +
          '" aria-pressed="' +
          on +
          '"><span class="dot" style="background:' +
          rootColor(r) +
          '"></span><span style="flex:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">' +
          esc(rootLabel(r)) +
          '</span><span style="font-family:var(--font-mono);font-size:10px;color:var(--muted-2)">' +
          counts[r] +
          '</span></button>'
        );
      })
      .join('');
    el.legendPanel.innerHTML = h;
    var badge = $('t-territories-badge');
    badge.textContent = S.focus.size ? ' · ' + S.focus.size + ' highlighted' : '';
  }

  function renderThreads() {
    el.threadsPanel.innerHTML =
      '<div class="label" style="padding:4px 8px 6px">Guided threads</div>' +
      S.threadDefs
        .map(function (t) {
          return (
            '<button class="rowbtn" style="min-height:32px;font-size:13px" data-thid="' +
            esc(t.id) +
            '"><span style="flex:1;min-width:0">' +
            esc(t.title) +
            '</span><span style="font-family:var(--font-mono);font-size:10px;color:var(--muted-2)">' +
            t.stops.length +
            ' stops</span></button>'
          );
        })
        .join('');
  }

  function pickThread(id) {
    var t = S.threadDefs.filter(function (x) {
      return x.id === id;
    })[0];
    if (!t) return;
    S.focus.clear();
    S.qmatch = new Set(t.stops);
    S.thread = t;
    closeStack();
    el.search.value = '';
    el.results.hidden = true;
    select(null);
    renderThreadCard();
    var stops = t.stops
      .map(function (sid) {
        return S.byId[sid];
      })
      .filter(Boolean);
    var xs = stops.map(function (p) {
        return p.x;
      }),
      ys = stops.map(function (p) {
        return p.y;
      });
    var cx = (Math.min.apply(null, xs) + Math.max.apply(null, xs)) / 2;
    var cy = (Math.min.apply(null, ys) + Math.max.apply(null, ys)) / 2;
    var dx = Math.max.apply(null, xs) - Math.min.apply(null, xs) + 0.35;
    var dy = Math.max.apply(null, ys) - Math.min.apply(null, ys) + 0.35;
    var sc = Math.max(S.baseScale, Math.min(S.baseScale * 20, Math.min(S.w / dx, S.h / dy) * 0.75));
    flyTo({ x: cx, y: cy }, sc);
  }

  function renderThreadCard() {
    var t = S.thread;
    if (!t) {
      el.threadCard.hidden = true;
      return;
    }
    var h =
      '<button class="closebtn" data-act="exit-thread" title="Exit thread" aria-label="Exit thread">&#215;</button>' +
      '<div class="label" style="color:var(--accent);margin-bottom:4px">Thread</div>' +
      '<h2 style="margin-bottom:6px;padding-right:20px">' +
      esc(t.title) +
      '</h2><p style="font-size:13px;color:var(--muted);line-height:1.5;margin-bottom:12px;text-wrap:pretty">' +
      esc(t.blurb) +
      '</p><div style="display:flex;flex-direction:column;gap:2px">';
    h += t.stops
      .map(function (id, i) {
        var p = S.byId[id];
        if (!p) return '';
        return (
          '<button class="rowbtn" data-tid="' +
          esc(id) +
          '"><span style="width:20px;height:20px;border-radius:50%;background:var(--accent);color:#fff;font-size:11px;' +
          'font-weight:600;display:inline-flex;align-items:center;justify-content:center;flex-shrink:0">' +
          (i + 1) +
          '</span><span class="rowtext"><span class="rowname">' +
          esc(p.name) +
          '</span><span class="rowplace">' +
          esc(p.place) +
          '</span></span><span class="dot" style="background:' +
          p.color +
          '"></span></button>'
        );
      })
      .join('');
    h += '</div>';
    el.threadCard.innerHTML = h;
    el.threadCard.hidden = !!S.sel;
  }

  function exitThread() {
    S.thread = null;
    S.qmatch = null;
    el.threadCard.hidden = true;
    draw();
    scheduleListSync();
  }

  // ── wiring ──

  function toggle(btn, on) {
    btn.setAttribute('aria-pressed', on ? 'true' : 'false');
  }

  function wireControls() {
    wireStack();

    $('zoom-in').addEventListener('click', function () {
      var r = el.host.getBoundingClientRect();
      zoomAt(r.left + S.w / 2, r.top + S.h / 2, 1.7);
    });
    $('zoom-out').addEventListener('click', function () {
      var r = el.host.getBoundingClientRect();
      zoomAt(r.left + S.w / 2, r.top + S.h / 2, 1 / 1.7);
    });
    $('zoom-reset').addEventListener('click', function () {
      closeStack();
      flyTo({ x: 0.35, y: 0.25 }, S.baseScale);
    });

    var tTerr = $('t-territories'),
      tRoutes = $('t-routes'),
      tThreads = $('t-threads'),
      tHeat = $('t-density');
    tTerr.addEventListener('click', function () {
      var open = el.legendPanel.hidden;
      el.legendPanel.hidden = !open;
      el.threadsPanel.hidden = true;
      toggle(tThreads, !!S.thread);
      tThreads.setAttribute('aria-expanded', 'false');
      toggle(tTerr, open);
      tTerr.setAttribute('aria-expanded', open ? 'true' : 'false');
    });
    tThreads.addEventListener('click', function () {
      var open = el.threadsPanel.hidden;
      el.threadsPanel.hidden = !open;
      el.legendPanel.hidden = true;
      toggle(tTerr, S.focus.size > 0);
      tTerr.setAttribute('aria-expanded', 'false');
      toggle(tThreads, open || !!S.thread);
      tThreads.setAttribute('aria-expanded', open ? 'true' : 'false');
    });
    tRoutes.addEventListener('click', function () {
      S.routesOn = !S.routesOn;
      toggle(tRoutes, S.routesOn);
      draw();
    });
    tHeat.addEventListener('click', function () {
      S.heat = !S.heat;
      toggle(tHeat, S.heat);
      draw();
    });

    el.legendPanel.addEventListener('click', function (e) {
      if (e.target.closest('[data-act="clear-roots"]')) {
        S.focus.clear();
        renderLegend();
        draw();
        scheduleListSync();
        return;
      }
      var b = e.target.closest('[data-root]');
      if (!b) return;
      var r = b.dataset.root;
      if (S.focus.has(r)) S.focus.delete(r);
      else S.focus.add(r);
      renderLegend();
      draw();
      scheduleListSync();
    });

    el.threadsPanel.addEventListener('click', function (e) {
      var b = e.target.closest('[data-thid]');
      if (!b) return;
      el.threadsPanel.hidden = true;
      pickThread(b.dataset.thid);
    });

    // One delegated handler for every "open this tradition" button on the page.
    [el.list, el.results, el.card, el.threadCard].forEach(function (root) {
      root.addEventListener('click', function (e) {
        if (e.target.closest('[data-act="close-card"]')) {
          select(null);
          renderThreadCard();
          return;
        }
        if (e.target.closest('[data-act="exit-thread"]')) {
          exitThread();
          return;
        }
        if (e.target.closest('[data-act="back-thread"]')) {
          select(null);
          renderThreadCard();
          return;
        }
        if (e.target.closest('[data-act="copy"]')) {
          copyRecipe();
          return;
        }
        var exp = e.target.closest('[data-expand]');
        if (exp) {
          var name = exp.dataset.expand;
          if (S.expanded.has(name)) S.expanded.delete(name);
          else S.expanded.add(name);
          syncList();
          return;
        }
        var row = e.target.closest('[data-tid]');
        if (!row) return;
        var p = S.byId[row.dataset.tid];
        if (!p) return;
        if (!S.thread) S.qmatch = null;
        el.search.value = '';
        el.results.hidden = true;
        select(p);
        flyTo(p);
      });
    });

    el.search.addEventListener('input', onQuery);
    el.search.addEventListener('focus', onQuery);

    document.addEventListener('click', function (e) {
      if (!el.results.hidden && !e.target.closest('.searchwrap')) el.results.hidden = true;
      if (S.stack && !e.target.closest('#stack') && !e.target.closest('#canvas-host')) closeStack();
    });

    document.addEventListener('keydown', function (e) {
      if (e.key !== 'Escape') return;
      if (S.stack) {
        closeStack();
        return;
      }
      if (!el.results.hidden) {
        el.results.hidden = true;
        return;
      }
      if (S.sel) {
        select(null);
        renderThreadCard();
      }
    });
  }

  function copyRecipe() {
    var s = S.sel;
    if (!s) return;
    var text = s.recipe || s.name + ' — ' + s.place;
    var done = function (label) {
      S.copyLabel = label;
      renderCard();
      setTimeout(function () {
        S.copyLabel = 'Copy recipe';
        if (S.sel) renderCard();
      }, 1600);
    };
    if (!navigator.clipboard) {
      done('Copy failed');
      return;
    }
    navigator.clipboard.writeText(text).then(
      function () {
        done('Copied ✓');
      },
      function () {
        done('Copy failed');
      }
    );
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', boot);
  else boot();
})();
