import json,hashlib,urllib.parse,subprocess,datetime,pathlib
p=pathlib.Path('docs/everynoise-work/001/packets')
checked='2026-09-30'
model='Axes, representative instrument construction, technique variants, exact room, tuning, microphone/preamp/console/compressor/EQ/medium and effects are authored recording defaults, not measured facts or documented artist gear. Software sample manipulation is represented by catalog sampler/granular chairs, not an assertion of particular hardware. Instrumentation and historical claims are limited to the cited sources. No exclusive origin is inferred from a practice anchor.'
axes_names=['harm','pitch','ornament','meter','density','transmission','improv','soundTech','intensity','voice','timbre','percussion','cyclicity']
env=dict(room='studio_auteur_home_pro',tuning='twelve_tet',chain_mic='condenser_ldc',chain_pre='ultra_clean',chain_console='console_in_the_box',chain_comp='comp_none',chain_eq='eq_mastering_clean_digital',chain_medium='digital_high',chain_status='authored_recording_model',pin_parts=True)
def source(url,title,claims,inspection='page_opened_and_read',date=None):
 return dict(url=url,title=title,checked_date=checked,publication_date=date,inspection=inspection,supported_claims=claims)
def photo(id,name,file,credit,lic,raw,licurl,dim,subject,inspection='file_page_opened_and_read',original=None,thumb=None,date=None):
 fn=file.replace(' ','_'); h=hashlib.md5(fn.encode()).hexdigest(); path=h[0]+'/'+h[:2]+'/'+urllib.parse.quote(fn)
 full=original or 'https://upload.wikimedia.org/wikipedia/commons/'+path
 small=thumb or 'https://upload.wikimedia.org/wikipedia/commons/thumb/'+path+'/800px-'+urllib.parse.quote(fn)
 return dict(manifest=dict(kind='tradition',id=id,name=name,source='Wikimedia Commons',source_page='https://commons.wikimedia.org/wiki/File:'+urllib.parse.quote(fn),image_url=full,thumb_url=small,license=lic,license_raw=raw,license_url=licurl,credit=credit,match_confidence='high',matched_label=subject),verification=dict(checked_date=checked,rights_metadata=inspection,photograph_date=date,image_subject=subject,metadata_dimensions=dim,metadata_mime_type='image/jpeg',image_urls_provenance='original_and_thumbnail_links_observed' if original and thumb else 'original_link_observed_thumbnail_standard_candidate' if original else 'standard_Commons_filename_hash_candidates_not_live_verified',visual_checked=False,bytes_checked=False,decoded_dimensions=None,final_full_url=None,final_thumb_url=None,http_status=None,checked=False))
def entry(n,label,id,name,family,lineage,inst,parts,fx,parent,a,desc,examples,refs,geo,rationale,distinction,sources,ph):
 t=dict(env,id=id,name=name,family=family,lineage=lineage,instruments=inst,parts=parts,chain_fx=fx)
 url='https://everynoise.com/engenremap-'+label.replace(' ','')+'.html'
 return dict(source_label=label,source_url=url,suggested_id=id,allocation_ordinal=n,id=id,proposed_outcome='add',tradition=t,extras=dict(parent=parent,axes=dict(zip(axes_names,a)),description=desc,exemplars=examples,status='researched',crossRefs=refs),geo=geo,signature_tokens=[],sources=[source(url,'Every Noise at Once — '+label,[],'blocked_tool_not_accessible')]+sources,neighbor_distinction=distinction,geo_rationale=rationale,photo=ph,model_policy=model,membership=dict(original_url_attempted=url,original_inspection='blocked_tool_not_accessible',member_examples_verified=False),equivalent_mapping=None,production_validation=dict(status='pending_coordinator_source_overlay',checked=False),blockers=['Exact Every Noise page artist membership could not be inspected; exemplar membership and label boundary remain unverified.','Actual original/thumbnail image bytes, final HTTP URLs, response MIME types, decoded dimensions and visual subject inspection remain unverified.'])
sampler=dict(sampler_archetypes='akai_s1000',sampler_classic_context='sampler_classic_industrial',sampler_bit_depth='sampler_twentyfour_bit',sampler_workflow='sampler_loop_layered')
voice=dict(voice_register='voice_register_source_unspecified',voice_quality='voice_quality_source_unspecified',voice_vibrato='voice_vibrato_local_unspecified',voice_articulation='voice_articulation_source_unspecified',voice_microtone='voice_microtone_local_unspecified',voice_mechanism_compound='voice_mechanism_compound_source_unspecified',voice_estill_quality='voice_estill_quality_source_unspecified',voice_speech_song='voice_speech_song_local_unspecified',voice_ornament_system='voice_ornament_system_source_unspecified',voice_tradition='voice_tradition_source_unspecified',voice_ensemble_config='voice_ensemble_solo_accompanied',voice_multitrack_stack='voice_multitrack_single_lead',voice_processing_chain='voice_processing_hall_reverb_long')
entries=[]
entries.append(entry(6,'deep ambient','deep_ambient','Deep ambient','electronic',
 'A listening and texture label for slowly unfolding, immersive ambient fields. Steve Roach explicitly describes Nostalgia for the Future as deep ambient, while Low Volume Music with Dirk Serries foregrounds overlapping loops. This proposal models the latter layered electronic continuum; the boundary with space ambient is porous and requires Every Noise membership verification.',
 ['analog_synth','sampler_classic'],dict(sampler,electronic_technique='electronic_pad_drone',oscillator='triangle_osc',filter_topology='svf',envelope='pad_env',modulation='lfo_filter'),['fx_true_stereo_reverb','hall_reverb'],'experimentalElec.ambient',[-2,-1,-2,-2,0,0,0,2,-2,-2,-2,-2,1],
 'An immersive, low-attack ambient field built from slow electronic layers and overlapping loops. The default combines a gently modulated sustained synthesizer with layered sampled texture. This is an authored realization of a documented deep-ambient listening practice, without a mandatory instrument brand or a claimed geographic origin.',
 ['Steve Roach — Nostalgia for the Future (2017)','Steve Roach & Dirk Serries — Low Volume Music (2012)'],['droneModal.modalElectric'],[32.2226,-110.9747,'Tucson','North America'],
 'Tucson is a regional practice anchor: the artist Bandcamp identifies Tucson and the album account documents Timeroom work in Baja Arizona. These rounded city-center coordinates do not purport to locate the private studio.',
 'The current space_ambient row already models Roach’s steady-state Immersion branch. This proposal selects overlapping loops and mild timbral modulation, but these are representative defaults rather than an established exclusive genre boundary. Mapping deep ambient to space_ambient cannot be ruled equivalent until the exact source membership is inspected.',
 [source('https://steveroach.com/product/nostalgia-for-the-future/','Nostalgia for the Future | Steve Roach',['The artist explicitly calls the album deep ambient and describes six interconnected immersions.','The album was created January–July 2017 at the Timeroom in Baja Arizona.']),source('https://steveroach.bandcamp.com/album/nostalgia-for-the-future','Nostalgia for the Future | Steve Roach',['Artist profile identifies Tucson, Arizona.'],'search_result_file_text_read','2017-08-05'),source('https://steveroach.bandcamp.com/album/low-volume-music','Low Volume Music | Steve Roach & Dirk Serries',['Primary release description characterizes deep ambient looping textures and subtle harmonic layers.'],'search_result_read'),source('https://www.steveroach.com/2026/01/01/the-surface-below-immersion-six/','The Surface Below – Immersion Six | Steve Roach',['Artist describes hardware synthesizers, effects and analog-console mixing for long slowly evolving sound fields.'],'page_opened_and_read','2026-01-01')],
 photo('deep_ambient','Deep ambient','Steve Roach portrait.jpg','Sam Howzit; derivative by Keraunoscopia / Wikimedia Commons / CC BY-SA 3.0','CC BY-SA 3.0','Creative Commons Attribution-Share Alike 3.0 Unported','https://creativecommons.org/licenses/by-sa/3.0/',[1675,2225],'Steve Roach',original='https://upload.wikimedia.org/wikipedia/commons/6/61/Steve_Roach_portrait.jpg',date='2010')))
entries[-1]['signature_tokens']=['ambient','layered-ambient','sustained-tone']
entries[-1]['blockers'].append('Deep ambient substantially overlaps current space_ambient; the new-entry versus equivalent-entry decision is provisional pending exact source inspection.')
entries.append(entry(7,'drone','drone','Drone','global',
 'Sustained-tone music treats duration, closely controlled pitch and the interaction of held tones as form. Tony Conrad’s amplified violin work supplies the selected bowed-string practice model. Drone also includes electronic and other instrumental practices; this default is neither dark ambient nor a comprehensive instrument roster for all drone music.',
 ['violin_orchestral'],dict(bowed_technique='bowed_legato_classical',orch_setup_period='modern_setup_violin',orch_bow='modern_bow',orch_articulation='arco_orch'),[],'droneModal.string',[-2,2,-2,-2,0,0,0,1,0,-2,1,-2,-2],
 'Long held pitches and subtle interactions among layered tones foreground sustained sound rather than harmonic progression or a beat. This bowed-string default represents Conrad’s amplified, overdubbed violin practice and uses just intonation. Other drone practices use different tunings and sources; neither darkness nor metallic distortion is a defining requirement.',
 ['Tony Conrad — Four Violins (recorded 1964; issued 1996)'],['droneModal.modalElectric','experimentalElec.ambient'],[40.7128,-74.006,'New York','North America'],
 'The museum record locates the documented Four Violins recording at the artist’s studio on Ludlow Street, New York. The pin is a rounded city-center practice anchor, not an exclusive origin or the artist’s birthplace.',
 'Current drone_dark_ambient combines sustained-tone minimalism and dark atmospheric music. This new row isolates sustained pitch/duration without an obligatory dark/horror atmosphere. Current drone_metal, drone_folk and didgeridoo_drone_practice are specific instrumental or scene branches. No existing bare drone/drone_music id exists in the restored catalog, so no rename or equivalent mapping is proposed.',
 [source('https://www.tableoftheelements.co.uk/tcc-08-four-violins-1964','Tony Conrad — Four Violins (1964) — Table of the Elements',['Conrad’s amplified strings introduced sustained just-intonation drone into minimal music in 1962.','The Dream Syndicate employed long duration and precise pitch; Conrad recorded Four Violins on 19 December 1964.']),source('https://www.centrepompidou.fr/en/ressources/oeuvre/4ajqUIg','Four Violins — Centre Pompidou',['Four sessions of amplified violin were overdubbed.','The artist’s recording studio was 56 Ludlow Street, New York, on 19 December 1964.'])],
 photo('drone','Drone','Tony Conrad 2 - DMS35th.jpg','Dave Pape / Wikimedia Commons / public domain','Public domain','Public domain dedication by copyright holder (PD-self)','https://commons.wikimedia.org/wiki/Template:PD-self',[2735,2592],'Tony Conrad',inspection='indexed_file_page_text_read_direct_page_open_blocked',date='2009-05-02')))
entries[-1]['tradition']['tuning']='just_intonation'
entries[-1]['signature_tokens']=['drone-foundation','sustained-tone','bowed-strings']
entries[-1]['blockers'].append('Tony Conrad photo rights/creator were read from full indexed file-page text; direct file-page opening remained restricted.')
entries.append(entry(8,'drone psych','drone_psych','Drone psych','rock',
 'Psychedelic rock extends guitar sustain and noisy texture into long ensemble improvisation. Bardo Pond’s Philadelphia recordings support a twin-guitar, bass, drums, voice and flute practice; electronics are also documented. The catalog represents the guitar role with one guitar chair, not a claim that the documented band has only one guitarist.',
 ['electric_guitar_humbucker','electric_bass','drum_kit','flute','voice'],dict(voice,electric_technique='electric_feedback_drone',amp_make='amp_unspecified',bass_technique='fingerstyle_locked',drum_technique='sticks_rock',drumhead='single_coated',flute_technique='classical_flute',wind_articulation='wind_continuous_legato',flute_size='concert_flute'),['fuzz_silicon','analog_delay','hall_reverb'],'distortedRock.experimental',[-2,0,-1,-1,1,1,2,1,1,-1,2,0,1],
 'A psychedelic ensemble practice in which sustained amplified guitar and dense noise coexist with open-ended collective playing. The chosen Bardo Pond model adds flute and voice to bass and drums, letting instrumental texture lead the vocal song. Specific pickup, drumhead, flute construction and effects settings are author choices, not documented band equipment.',
 ['Bardo Pond — Bardo Pond (2010)'],['distortedRock.noiseRock','droneModal.modalElectric'],[39.9526,-75.1652,'Philadelphia','North America'],
 'Fire Records identifies the Philadelphia band and its Compound studio. This anchors the selected recorded practice; the label is not geographically exclusive.',
 'Relative to the proposed drone_rock default, this roster foregrounds flute/voice and collective psychedelic improvisation rather than a stripped guitar-feedback rock loop. Relative to psychedelic_rock it emphasizes sustained noise and extended texture. The distinction is a supported exemplar choice, not a claim that the categories are disjoint.',
 [source('https://www.firerecords.com/artists/bardo-pond/','Bardo Pond — FIRE RECORDS',['The band combines twin guitars, bass, drums and Isobel Sollenberger’s voice, flute and violin.','The label describes psychedelic rock and experimental noise practices.']),source('https://www.firerecords.com/product/bardo-pond-bardo-pond/','Bardo Pond — Bardo Pond — FIRE RECORDS',['The 2010 album documents Philadelphia/Compound studio practice.','Credits specify guitars, bass, voice/flute, electronics and drums.'],'page_opened_and_read','2010-12-06')],
 photo('drone_psych','Drone psych','Bardo Pond-4.jpg','furminator / Wikimedia Commons / CC BY 2.0','CC BY 2.0','Creative Commons Attribution 2.0 Generic','https://creativecommons.org/licenses/by/2.0/',[1024,768],'Bardo Pond',original='https://upload.wikimedia.org/wikipedia/commons/a/aa/Bardo_Pond-4.jpg',thumb='https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Bardo_Pond-4.jpg/800px-Bardo_Pond-4.jpg',date='2007-06-30')))
entries[-1]['signature_tokens']=['rock-context','drone-like','sustained-tone','rough']
entries.append(entry(9,'drone rock','drone_rock','Drone rock','rock',
 'A rock practice that builds extended passages from repetitive accompaniment and sustained guitar feedback. Spacemen 3’s live Geneva album is explicitly described as drone rock by its label; Sonic Boom’s firsthand notes describe sustained keys and feedback guitars. The modern recording chain and instrument build choices are representative, not a reconstruction of the 1989 stage rig.',
 ['electric_guitar_single_coil','electric_bass','drum_kit','voice'],dict(voice,electric_technique='electric_feedback_drone',amp_make='amp_unspecified',bass_technique='fingerstyle_locked',drum_technique='sticks_rock',drumhead='single_coated'),['fuzz_silicon','analog_delay'],'distortedRock.experimental',[-2,-1,-2,1,0,1,1,1,1,-1,2,1,2],
 'Repeated bass/drum accompaniment and long amplified guitar tones support extended rock passages. The selected Spacemen 3 model foregrounds feedback and repetition while retaining a vocal chair. The default describes one reusable studio arrangement, not every track or the exact historical live equipment.',
 ['Spacemen 3 — Live at the New Morning, Geneva, Switzerland, 18.05.1989'],['droneModal.modalElectric','distortedRock.noiseRock'],[46.2044,6.1432,'Geneva','Europe'],
 'The label documents the New Morning concert in Geneva on 18 May 1989. Geneva is a performance-practice anchor for this exemplar, deliberately not an assertion of the band’s origin.',
 'Unlike drone_metal, distorted guitar sustain here accompanies repetitive psychedelic rock with ordinary rock drums rather than a mandated slow heavy-metal riff grammar. Compared with the proposed drone_psych row, this model has a leaner guitar/bass/drum/voice roster and more cyclic accompaniment. Genre boundaries still require exact Every Noise artist-map inspection.',
 [source('https://spaceagerecordings.bandcamp.com/album/live-at-the-new-morning-geneva-switzerland-18051989','Live At The New Morning, Geneva, Switzerland 18.05.1989 | Spacemen 3 | Space Age Recordings',['The label describes the band as drone rock and documents the Geneva performance.','Sonic Boom’s firsthand notes describe held keys, guitars feeding back against speaker cabinets and the extended Suicide performance.']),source('https://spacemen3.co.uk/discs/performance/','Performance — spacemen3.co.uk',['Archive lists guitar, organ and vocals, bass, and percussion personnel.'],'search_result_read'),source('https://fatpossum.com/products/lazer-guided-melodies','Lazer Guided Melodies — Spiritualized — Fat Possum Records',['Primary label documents Spiritualized’s early album; Spiritualized photo is a related Jason Pierce practice exemplar, not a photograph of Spacemen 3.'],'search_result_read')],
 photo('drone_rock','Drone rock','Spiritualized 2009.05.29 003.jpg','LivePict.com / Wikimedia Commons / CC BY-SA 3.0','CC BY-SA 3.0','Creative Commons Attribution-Share Alike 3.0 Unported','https://creativecommons.org/licenses/by-sa/3.0/',[4288,2848],'Spiritualized',inspection='indexed_file_page_text_read_direct_page_open_blocked',date='2009-05-29')))
entries[-1]['signature_tokens']=['rock-context','drone-like','sustained-tone','distorted']
entries[-1]['blockers'].append('Selected Spiritualized photo is a related practitioner image, not the documented Spacemen 3 concert; direct file page remains blocked and membership is unverified. Prefer a verified Spacemen 3/Loop photo if available during final verification.')
entries.append(entry(10,'experimental ambient','experimental_ambient','Experimental ambient','electronic',
 'Ambient composition treats recorded sound, acoustic resonance, noise and electronic montage as mutable material. Tim Hecker’s Ravedeath, 1972 was built from improvised pipe-organ recordings in Reykjavik and extended studio transformation in Montreal. The default models the transformed-recording stage with sampling and granular synthesis, not an assertion that Hecker used a particular sampler or granular algorithm.',
 ['sampler_classic','granular_synth'],dict(sampler,electronic_technique='electronic_glitch_textural',sampler_workflow='sampler_field_recordings',granular_use='granular_ambient',granular_synth_source='granular_synth_sampled'),['digital_delay','hall_reverb'],'experimentalElec.ambient',[-1,1,-1,-2,1,0,1,2,0,-2,1,-2,-1],
 'Recorded acoustic tone, noise and electronic processing form a shifting ambient composition rather than a regular beat or a prescribed mellow pad. The sample/granular roster models Hecker’s studio montage of improvised organ recordings. The acoustic pipe organ is the documented source; these catalog chairs represent its transformed recorded material and do not replace that fact with a hardware claim.',
 ['Tim Hecker — Ravedeath, 1972 (2011)','Tim Hecker — Harmony in Ultraviolet (2006)'],['experimentalElec.musiqueConcrete','experimentalElec.industrialNoise'],[45.5019,-73.5674,'Montréal','North America'],
 'Hecker’s firsthand interview describes extensive Montreal studio transformation after recording a Reykjavik church organ. Montréal anchors the composition/montage stage represented by this recipe; Reykjavik remains a documented source-recording location.',
 'Compared with current ambient/space_ambient sustained-pad defaults, this selected practice makes transformed acoustic source recordings and noise/dissonance central. Compared with dark ambient it does not require horror atmosphere. Sampler plus granular processing is a reusable model of the documented montage practice rather than a universal experimental-ambient roster.',
 [source('https://exclaim.ca/music/article/tim_hecker_talks_ravedeath_1972','Tim Hecker Talks Ravedeath, 1972 — Exclaim!',['Firsthand interview documents improvised pipe-organ recording in a wooden church in Reykjavik.','Hecker then worked in his Montreal studio for a month on layering, montage and editing.'],'page_opened_and_read','2011-02-16'),source('https://montreal.mutek.org/en/artists/tim-hecker','Tim Hecker — MUTEK Montréal',['The institution characterizes his work through noise, dissonance and melody structured as ambient composition.','The profile lists Ravedeath, 1972 and Harmony in Ultraviolet.']),source('https://montreal.mutek.org/en/artists/tim-hecker-konoyo-ensemble','Tim Hecker Konoyo Ensemble — MUTEK Montréal',['Institutional program documents synthesis, sequencers, software and static/feedback alongside acoustic ensemble sounds.'],'search_result_read')],
 photo('experimental_ambient','Experimental ambient','Tim Hecker - A-Visions 4 (4690826583).jpg','basic_sounds / Wikimedia Commons / CC BY-SA 2.0','CC BY-SA 2.0','Creative Commons Attribution-Share Alike 2.0 Generic','https://creativecommons.org/licenses/by-sa/2.0/',[1600,1200],'Tim Hecker at MUTEK A/Visions 4',original='https://upload.wikimedia.org/wikipedia/commons/f/f9/Tim_Hecker_-_A-Visions_4_%284690826583%29.jpg',thumb='https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f9/Tim_Hecker_-_A-Visions_4_%284690826583%29.jpg/960px-Tim_Hecker_-_A-Visions_4_%284690826583%29.jpg',date='2010-06-08')))
entries[-1]['signature_tokens']=['ambient','layered-ambient','rough','sustained-tone']
entries[-1]['acoustic_source_model_note']='The pipe_organ catalog currently defaults to historical voicing/school/context not established in the Hecker interview. This proposal represents recorded organ material in sample/granular chairs to avoid presenting arbitrary organ-maker defaults as evidence. If integration requires a live source-organ chair, add explicit non-default, auto:false, empty-descriptor unspecified variants for the organ-specific dimensions and verify zero existing recipe drift first.'
for e in entries:
 for which,url in [('full',e['photo']['manifest']['image_url']),('thumbnail',e['photo']['manifest']['thumb_url'])]:
  res=subprocess.run(['curl','--location','--max-time','10','--silent','--show-error','--output','/dev/null','--write-out','%{http_code}|%{url_effective}|%{content_type}',url],capture_output=True,text=True)
  e['photo']['verification'][which+'_fetch_receipt']=dict(method='GET',requested_url=url,exit_code=res.returncode,curl_result=res.stdout,stderr=res.stderr.strip(),success=False)
  e['photo']['verification'][which+'_fetch_result']='shell_proxy_connection_failure' if res.returncode==7 else 'unverified_fetch_failure'
packet=dict(schema_version=1,group_id='001',allocation_ordinals=[6,7,8,9,10],checked_date=checked,status='researched_proposals_with_explicit_verification_blockers',shared_files_modified=False,entries=entries,prerequisite_proposals=[],completion_blocked=True)
(p/'06-10.json').write_text(json.dumps(packet,ensure_ascii=False,indent=2)+'\n')
print('Wrote',p/'06-10.json', 'entries',len(entries))
